=== Removing redundant scenarios

Welcome back to Cucumber School.

shot::[1,feature file from end of Ch 4]
[source,gherkin]
----
include::../../04/code/js/13-replace-hardcoded-sean-instance/features/hear_shout.feature[]
----

Last time we worked on cleaning up the Shouty features to keep them in sync with the current status of the project. We stripped the scenarios back to only specify the behaviour of passing messages between people. We made it clear that the proximity rule had not yet been implemented.

You’ll already remember from the Cucumber expressions chapter how important it is to be expressive in your scenarios, and keep them readable. In this chapter we’re going to learn some new tricks with Gherkin that will give you even more flexibility about how you write scenarios.

Once again the Shouty developers -- have been hard at work implementing that proximity rule. Let’s have a look at how they got on. shot::[2, Show chapter 5 initial checkin feature file]

Right, so those two scenarios we just left as placeholders: the one where the listener is within range,shot::[3, "show in feature file"] and the one where the listener is out of range shot::[4, "show in feature file"] are passing. shot::[5, "Show output from Cucumber showing the in-range/out-of-range results"] Fantastic! If we look at our step definitions, we can see how they have been implemented. shot::[6, "show the in-range/out-of-range scenarios in the step definitions"]

[source,gherkin]
----
include::../code/ruby/00-starting-code/features/hear_shout.feature[lines=23..35]
----

Let’s review the changes to the feature file in more detail.

We now have four scenarios:shot::[7] our original two from the last time we looked at the code,shot::[8] and the two placeholders we wrote as reminders.shot::[9]

[source,gherkin]
----
include::../code/ruby/00-starting-code/features/hear_shout.feature[]
----

We used the second scenario - Listener hears a different message shot::[10,Highlight second scenario] - to triangulate and force us to replace the hard-coded message output with a proper implementation. Now we have a domain model that uses a variable for the message, there's an insignificant chance of this behaviour regressing, so we can safely remove the second scenario. shot::[11,removes second scenario: Listener hears a different message]

[source,gherkin]
----
include::../code/ruby/00-starting-code/features/hear_shout.feature[lines=14..20]
----

Keeping excess scenarios is wasteful: they clutter up your feature files, distracting your readers. When you run your features as tests, excess scenarios make them take longer to run than necessary. The one where a "listener hears a "message" is a perfectly good way of checking that the message has been sent correctly.
