=== Dependency Injection

A fundamental concept for organising your support code in a Cucumber-JVM project is *dependency injection*.

Dependency injection is how you access other objects from your step defintion classes. They could be objects from the system under test, or objects from your support layer.

Dependency injection allows you to share the same collaborator objects between multiple step definition classes (or other Cucumber utility classes, like those defining a custom parameter type). When you ask dependency injection to give you an instance of a particular object, you'll always get the same instance of that object for the duration of each scenario.

This gives you a similar capability as you get with the "World" in Ruby or JavaScript Cucumbers - you can inject an object to contain context state through the life of a scenario, or to contain useful helper methods.

In this lesson we'll show you how to introduce dependency injection into your Cucumber-JVM project, and use a simple World object to share some state with a parameter type class.

==== Exclude `@todo` scenarios

When we refactor, we want to make sure our tests are all green. Since we have one scenario that's not currently finished, let's change our `RunWith` configuration to exclude any scenarios tagged as `@todo`:
shot::[1, "Add `tags = \"not @todo\"`"]

[source,java]
include::../code/java/01-only-run-tests-we-expect-to-pass/shouty/src/test/java/shouty/RunCucumberTest.java[lines=7..10]


Good, now when we run Cucumber we should expect to see everything pass. 
shot::[2, "Run Cucumber"]

==== Adding a World class

Let's start by trying to inject a `ShoutyWorld` instance into the contructor of our `StepDefinitions` class. shot::[3]

[source,java]
----
include::../code/java/02-introduce-world-class/shouty/src/test/java/shouty/StepDefinitions.java[lines=17]
    ...
include::../code/java/02-introduce-world-class/shouty/src/test/java/shouty/StepDefinitions.java[lines=25..27]
----

We don't have one yet, so we can let the IDE help us to create one. shot::[4]

[source,java]
----
include::../code/java/02-introduce-world-class/shouty/src/test/java/shouty/support/ShoutyWorld.java[lines=1..4]
----

If we run Cucumber now, we'll see an error,shot::[5] because we need to let Cucumber know which framework we want to use for Dependency Injection. You can choose your project's own DI framework here, or you can use Cucumber's own lightweight `picocontainer` framework. shot::[6]

[source,xml]
----
include::../code/java/03-add-dependency-on-picocontainer/shouty/pom.xml[lines=49..54]
----

shot::[7, "Run mvn test - should be green"]Ok, so we've now introduced an empty World object which we can access from a field in our step definition class, but it doesn't do anything yet.. Now we can start moving code out of the step definitions and onto the World.

==== Move Network onto World

In order to be able to access the same `Network` instance everywhere, let's move that field onto our new `ShoutyWorld`.

[source,java]
----
include::../code/java/00-initial-commit/shouty/src/test/java/shouty/StepDefinitions.java[lines=45..48]
----

We can start by writing the code we want to have. Imagine we already had a `network` field on the World, and we could just set it here like this: shot::[8]

[source,java]
----
include::../code/java/04-move-network-onto-world/shouty/src/test/java/shouty/StepDefinitions.java[lines=48..51]
----

We don't have that field on our World object yet, so let's create it. shot::[9]
and we need to move the default range here too. shot::[10]

[source,java]
----
include::../code/java/04-move-network-onto-world/shouty/src/test/java/shouty/support/ShoutyWorld.java[lines=1..8]
----

We should also use the same `network` in this step where we create a new `Person` instance: shot::[11]

[source,java]
----
include::../code/java/04-move-network-onto-world/shouty/src/test/java/shouty/StepDefinitions.java[lines=53..57]
----

Now we can delete the old `network` field on the `StepDefintions class` shot::[12].
[source,java]
----
include::../code/java/02-introduce-world-class/shouty/src/test/java/shouty/StepDefinitions.java[lines=17..20]
----

Let's check everything is still green. shot::[13, "run mvn test"]. Good.
