=== Dependency Injection

A fundamental concept for organising your support code in a Cucumber-JVM project is dependency injection.

Dependency injection is how you access other objects from your step defintion classes. In particular, it allows you to share those objects between multiple step definition classes, so that if you've started to organise your step definitions into different classes, they can still access the same objects.

This gives you a similar capability as you get with the "World" in Ruby or JavaScript Cucumbers - you can inject an object to store context state through the life of a scenario, or to contain useful helper methods.

In this lesson we'll show you how to introduce dependency injection into your Cucumber-JVM project, and use a simple World object to share some state with a parameter type class.

==== Exclude `@todo` scenarios

When we refactor, we want to make sure our tests are all green. Since we have one scenario that's not currently finished, let's change our `RunWith` configuration to exclude any scenarios tagged as `@todo`:
shot::[1, "Add `tags = \"not @todo\"`"]

[source,java]
include::../code/java/01-only-run-tests-we-expect-to-pass/shouty/src/test/java/shouty/RunCucumberTest.java[lines=7..10]


Good, now when we run Cucumber we should expect to see everything pass. 
shot::[1, "Run Cucumber"]

==== Adding a World class

Let's start by trying to inject a `ShoutyWorld` class into the contructor of our `StepDefinitions` class. shot::[]

[source,java]
----
include::../code/java/02-introduce-world-class/shouty/src/test/java/shouty/StepDefinitions.java[lines=30..31]
----

We don't have one yet, so we can let the IDE help us to create one. shot::[]

[source,java]
----
include::../code/java/02-introduce-world-class/shouty/src/test/java/shouty/support/ShoutyWorld.java[lines=1..4]
----

If we run Cucumber now, we'll see an error,shot::[] because we need to let Cucumber know which framework we want to use for Dependency Injection. You can choose your project's own DI framework here, or you can use Cucumber's own lightweight `picocontainer` framework. shot::[]

[source,xml]
----
include::../code/java/03-add-dependency-on-picocontainer/shouty/pom.xml[lines=49..54]
----

shot::[1, "Run mvn test - should be green"]. Great. Now we can start moving code onto the World.

===== Move Network onto World

In order to be able to access the same `Network` instance everywhere, let's move that field onto our new `ShoutyWorld`.

We can start by writing the code we want to have. Imagine we already had a `network` field on the World, and we could just set it here like this: shot::[]

[source,java]
----
include::../code/java/04-move-network-onto-the-world/shouty/src/test/java/shouty/StepDefinitions.java[lines=56]
----

We don't have that field yet, so let's create it. shot::[]
and we need to add the default range here too. shot::[]

[source,java]
----
include::../code/java/04-move-network-onto-the-world/shouty/src/test/java/shouty/support/ShoutyWorld.java[lines=1..8]
----






- move network field onto context class
- introduce person parameter type