==== Lesson 3 - Questions

===== Why did we write a test for behaviour that had already been implemented?

* When we are going to fix the bug, we want to make sure we don't break existing behaviour (*Correct*)
* Our manager wants us to achieve 100% test coverage
* We're getting paid by the hour so it gives us something to do to keep busy
* It will help us move from ice-cream-cone to pyramid (*Correct*)

Explanation:

If we had been doing TDD, we would have already implemented this test. Still, _better late than never_ as my mum used to say.

===== Why did we force the test to fail?

* We don't trust tests that pass right away: we want to see it fail for the right reason (*Correct*)
* We want to see what it will look like when it fails, and how readable the error is (*Correct*)
* This is what test-driven development looks like
* So that we will have an ice-cream cone distribution of tests

Explanation:

This is not _quite_ test-driven development, but it's as close as we can get when we're retro-fitting tests for existing behaviour.

It's really important to see an automated test fail, otherwise you have no confidence that you've implemented it correctly, and that it will
actually save you from introducing bugs. So deliberately introduce a bug, and see if the test catches it.