=== Tidy up the bug report Gherkin

Let's start by running our failing scenario.

We have it marked with a `@todo` tag on it,shot::[1] but those scenarios are filtered out in our default `npm test` command.

[source,gherkin]
----
    @todo
    Scenario: BUG #2789
----

We're going to start work on the scenario now, so let's change that tag to a `@wip` to indicate that it's "Work In Progress":

[source,gherkin]
----
include::../code/js/00-initial-commit/features/premium_shouts.feature[lines=27..31]
----

Now when we run our regular `npm test` command, we should see the failing scenario: shot::[2]

[source, sh]
----
$ npm test
----

OK. We'll work outside-in and start by tidying up the Gherkin specification.

Right now, the scenario is still in the raw form it was in when the bug was first reported, with a name that references an ID in our bug tracking system.shot::[3] This doesn't make for very good documentation about the intended behaviour.

[source,gherkin]
----
include::../code/js/00-initial-commit/features/premium_shouts.feature[lines=27..31]
----

It also isn't sitting under the right rule.

Let's start by moving it here, under the rule about charging for mentioning the word "buy" shot::[4, move scenario under first rule, run tests]

[source,gherkin]
----
include::../code/js/01-move-scenario-under-the-right-rule/features/premium_shouts.feature[lines=11..31]
----

Now let's find a better name for the scenario.

Using our Friends Episode naming convention that we introduced in Chapter 7, we could call it something like "(the one where Sean) mentions “buy” several times in one shout"? shot::[5, change the scenario title]shot::[6, run tests]

[source,gherkin]
----
include::../code/js/02-rename-scenario/features/premium_shouts.feature[lines=20]
----

You might be worried about losing this bug ID. We could keep it in a comment shot::[7], a tag shot::[8], or in the description of the Scenario.

Just like under a `Feature` keyword, you can write any arbitrary text you want beneath a `Scenario` keyword, before the first `Given`, `When` or `Then` keyword. 

So let's do that. shot::[9, write the bug number in the scenario description, run tests]

[source,ghekrin]
----
include::../code/js/02-rename-scenario/features/premium_shouts.feature[lines=19..22]
----

We think the values in the example could be changed to make it a little more expressive. If we start Sean off with 100 credits,shot::[10] and end him with 95,shot::[11] it more clearly illustrates the rule that only five credits should be deducted. shot::[12, run tests]

[source,gherkin]
----
include::../code/js/03-changed-values-in-scenario/features/premium_shouts.feature[lines=19..25]
----

OK great, so now we have a failing test we're more happy with.

The trouble is, although this test tells us what's wrong with the behaviour of the system - the wrong number of credits are being deducted - it doesn't give us any clues as to *why*.

This is why we need a balance of unit tests _and_ acceptance tests: when they fail, acceptance tests tell you what is wrong with the system, but unit tests should tell you where you need to go to fix it.

That's what we'll look at in the next lesson.
