=== Basic Filtering

shot::[1, "Animation"]
Hello, and welcome back to Cucumber School.

Last time we learned about two very different kinds of loops. First, we used DataTables to loop over data in your scenarios.

Then we learned about BDD cycles. We saw how the outer loop of BDD helps you to build the right thing while the inner loop helps you build the thing right.

In this lesson, we’re going to teach you all about how to run different SpecFlow scenarios.

shot::[2, "Scroll through shout.feature, end by showing scenario 'Message too long'"]
When we start working on a new scenario we often take a dive down to the inner TDD loop where we use a unit testing tool to drive out new classes or modify the behaviour of existing ones. When our unit tests are green and the new code is implemented we return to the SpecFlow scenarios to verify whether we have made overall progress or not.

If we have lots of SpecFlow scenarios, it can be distracting to run all of them each time we do this. We often want to focus on a single scenario - or perhaps just a couple - to get feedback on what we’re currently working on.

There are several ways to do this. SpecFlow converts the scenarios to tests that can be executed by the test execution framework we configured for the project, which is xUnit in our case. Because of that the SpecFlow scenarios appear as regular coded tests in the test runner tools you use, for example in the Visual Studio Test Explorer window. These tools usually provide several filtering options.

Probably the easiest way to filter is to run only the scenario with a specified name.

shot::[3, "type 'Message too long' into the VS test explorer search box"]

Simply typing the name of the scenario to the Test Explorer window search box filters the list to that particular scenario. shot::[4, "Select test and show context menu"] You can run or debug the selected scenario from the context menu but the easiest is shot::[5.1, "click run all"] to hit *Run All* that runs all scenarios in the filtered view. It is worth spending a few minutes learning the keyboard shortcut of that, shot::[5.2, "hover over run all"] Ctrl R,V by default, as it can speed up your loops drastically.

You can filter for the scenario name as you have seen but you can use the search box to filter for keywords as well. Let's use it to run all scenarios with the text "range" in their name. shot::[6, "type 'range' to the search box, open up hierarchy nodes, and run all"]

The Test Explorer window can also be used shot::[7, "clear search and hover over failing test filter"] to filter for the outcome, for example if you want to re-run all failing tests, shot::[8, "click through hierarchy nodes"] or you can also run tests based on their hierarchy. Since the feature files appear as a separate node in the hierarchy, shot::[9.1, "run scenarios from HearShoutyFeature node"] you can use this to run all scenarios from a particular feature file.

The search box can contain complex search expressions. You can discover these options shot::[9.2, "show links"] by clicking on the *Add search filter* links or by checking out the documentation. We'll use this to show you how to filter using tags.

shot::[10, "show 'Listener is out of range' scenario"]
Let's say we want to work on this scenario for the next couple of hours. First, we’ll put a focus tag right here, above this scenario. shot::[11, "add a @focus tag to the 'Listener is out of range' scenario"] Tags start with an at-sign and are case sensitive.

As we said, SpecFlow converts the scenarios to tests. This conversion happens at compile-time, so I need to build my solution to be able to have the changes applied. shot::[12, "build"]

SpecFlow converts the tags to test categories or *traits* as the Test Explorer window calls these. So to be able to filter for a particular tag, we have to enter a trait expression.

shot::[13, "type Trait:focus into the search box"] Trait expressions start with the word *Trait* followed by a colon and the name of the tag without the at sign.

[source]
----
Trait:focus
----

Now we can run only the scenarios tagged with focus... shot::[14, "run all"]

It’s entirely up to you what you name your tags. When we’re working on a particular area of the application it is common to use a temporary tag like this - we’ll remove it before we check our code into source control.

Tags can be used for other purposes as well. If you have lots of scenarios it can be time-consuming to run them all every time. For example, you can tag a few of them with @smoke and run only those before you check in code to source control. shot::[15, tag first and third scenario with @smoke] Running just the smoke tests will give you a certain level of confidence that nothing is broken without having to run them all. shot::[16, "filter for smoke"]

[source]
----
Trait:smoke
----

We filtered the Test Explorer window but as you can see no scenarios are shown. This is because the list haven't refreshed yet. In fact we haven't even saved the file yet! We could save the file, build the project and run the tests, but the *Run All* command does all of these steps. shot::[17.1, "run all and open up hierarchies"]

Here it is! Now you probably understand better why learning the keyboard shortcut for this command helps a lot. shot::[17.2, "hover over run all"] Ctrl R,V!

Running the smoke tests gives you a quick feedback. If you’re running SpecFlow on a Continuous Integration Server as well, you could run all the scenarios there, detecting any regressions you might have missed by only running the smoke tests.

Tags give you a way to organize your scenarios that cut across feature files. You can think of them like sticky labels you might put into a book to mark interesting pages that you want to refer back to.

Some teams also use tags to reference external documents, for example, tickets in an issue tracker or planning tool. Let’s pretend we are using an issue tracker while working on Shouty and all the behaviour we built so far is related to the issue number 15. We could tag the whole feature file with this single line at the top. shot::[18, tag feature with @issue:15] All the scenarios within that file now inherit that tag, so if we filter for this tag, Visual Studio will run all the scenarios in the feature file. shot::[19, "filter for issue:15 and run all"]

You can use more complex tag expressions to select the scenarios you want to run. For example, you could use a trait expression to exclude all the scenarios tagged as @slow. Let's mark a few of them as slow... shot::[20, "tag last two scenarios with @slow"] and this time I build the project to show the filtering results. shot::[21, "build"] Then rewrite the trait expression in the search box to filter for the slow scenarios. shot::[22, "type expression: Trait:slow"] Now if I add a dash ("-") to the front you can see all that are not slow. shot::[23, "change expression: -Trait:slow"] Now when we run the tests, the "@slow" scenarios won't be run. shot::[24, "run all"]

[source]
----
-Trait:slow
----

You can read about how to build more complicated filter expressions in Visual Studio in the https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019#search-and-filter-the-test-list[Visual Studio documentation]

There's one more thing to learn about tags. They can be combined with hooks, so that you can be selective about which hooks to run when. We'll cover that in a future chapter.
