include::./title.adoc[]

shot::[1, "Animation"]
Hello, and welcome back to Cucumber School.

Last time we learned about two very different kinds of loops. First, we used DataTables to loop over data in your scenarios.

Then we learned about TDD cycles. We saw how the outer loop of TDD helps you to build the right thing while the inner loop helps you build the thing right.

In this lesson, we’re going to teach you all about how to configure Cucumber.

shot::[2, "Scroll through shout.feature, end by showing scenario 'Message too long'"]


When we start working on a new scenario we often take a dive down to the inner TDD loop where we use a unit testing tool to drive out new classes or modify the behaviour of existing ones. When our unit tests are green and the new code is implemented we return to the Cucumber scenarios to verify whether we have made overall progress or not.

shot::[3, "Scroll through shout.feature, end by showing scenario 'Message too long'"]
[source]
----
bundle exec cucumber
----

If we have lots of Cucumber scenarios, it can be distracting to run all of them each time we do this. We often want to focus on a single scenario - or perhaps just a couple - to get feedback on what we’re currently working on.

There are several ways to do this in Cucumber - and your IDE may offer other options. We'll start by showing some basic filtering on the command line, before showing you some alternatives.

Probably the easiest way to filter is to tell Cucumber to run only a scenario with a particular name.

shot::[4, "type bundle exec command in console, show output and highlight that it has only run the one scenario 'Message too long'"] shot::[5]
We can pass arguments to Cucumber using the `--name` option, which tells Cucumber to only run scenarios with a name matching "Message is too long".

[source]
----
bundle exec cucumber --name "Message is too long"
----

The value of the `--name` option is actually a regular expression, so you can use your imagination here to run more than one scenario. Let's use it to run all scenarios with the text "range" in their name. shot::[6, "type bundle exec command in console, show output and highlight that it has run the two scenarios containing the word 'range'"]shot::[7]

[source]
----
bundle exec cucumber --name "range"
----

We can also use the abbreviated form of `--name`, `-n` shot::[8]

[source]
----
bundle exec cucumber -n "range"
----

We can accomplish the same thing by adding some configuration on the `cucumber.yml` file, but we'll talk about that at the end of the lesson.

Another way to tell Cucumber to run a specific scenario is to specify the line number of the scenario within a feature file. The 'Message too long' scenario starts on line 44 in the feature file. shot::[9, "in feature file show that 'Message too long' starts on line 44"]

We can use that line number when we run Cucumber. shot::[10, "use line number on comand line"] shot::[11] shot::[12]

[source]
----
bundle exec cucumber features/hear_shout.feature:44
----

You can even specify multiple line numbers for each file. Let's run 'Two shouts' as well. [shot::[13, "in feature file, show 'Two shouts' starts on line 33"]

Let's add that line number when we run Cucumber. shot::[14, "type bundle exec command in console, show output and highlight that it has run two scenarios - 'Two shouts' and 'Message too long'"]shot::[15]

[source]
----
bundle exec cucumber features/hear_shout.feature:33:44
----

You can list several files and lines together like this if you have a specific set of scenarios you want to run.

The examples that you've just seen set a Ruby property on the command line. If you're working in an IDE this is less than ideal, but fortunately there are other ways to achieve exactly the same outcome.

Let's look at using a property file to set the system properties. Create a property file called `cucumber.yml` in the root path of the project shot::[16] and add `default: --name range` shot::[17]

When we run Cucumber, it picks up the property setting from the file and only runs the "range" scenarios. shot::[18, "type `bundle exec cucumber` in console, show output and highlight that it has run the two scenarios containing the word 'range'"]shot::[19]

[source]
----
bundle exec cucumber
----

The benefit of a properties file is that it gets checked in with your code, which means that any settings can be shared by all team members.

In this lesson you've learnt how to filter the set of scenarios to run using scenario names and line numbers from the command line and using property files.
