=== Cleaning up

video::https://drive.google.com/uc?id=1arEP_-0Fi5CK7EC8IYCJWrc67I_XF34Z[]
=======
shot::[0.1, "04.01.animation.mp4"]

In the previous chapter, we talked about the importance of having readable scenarios, and you learned some new skills with regular expressions to help you achieve that goal. Those skills will give you the confidence to write scenarios exactly the way you want, knowing you’ll be able to match the Gherkin steps easily from your step definition code.

We emphasise readability because from our experience, writing Gherkin scenarios is a software design activity. Cucumber was created to bridge the communication gap between business domain experts and development teams. When you collaborate with domain experts to describe behaviour in Gherkin, you’re expressing the group’s shared understanding of the problem you need to solve. The words you use in your scenarios can have a deep impact on the way the software is designed, as we’ll see in later episodes.

The more fluent you become in writing Gherkin, the more useful a tool it becomes to help you facilitate this communication. Keeping your scenarios readable means you can get feedback at any time about whether you’re building the right thing. Over time, your features become living documentation about your system. We can’t emphasize enough how important it is to see your scenarios as more than just tests.

Maintaining a living document works both ways: you’ll drive your solution design from your scenarios, but you may also have to update your Gherkin to reflect the things you learn as you build the solution. This dance back and forth between features and solution code is what BDD is all about.

Today, we’ll learn about feature descriptions, the Background keyword, and about keeping scenarios and code up-to-date with your current understanding of the project.

First, let’s catch up with what’s been happening on the Shouty project.
