=== Split the obscure unit test into new, pending, independent tests
This last one here is a bit weird. It’s sort of about broadcasting to listeners, but it has this odd hack in it which needs further investigation [highlight the comment on the first line] . This test is quite obscure, and seems to be attempting to cover several aspects of Network’s behaviour all at once. Let’s document those individual behaviours as new tests and we can come back to deal with this one later.
Re-organise the unit tests for Person around responsibilities
<ruby>
We can see we’ll need something under the responsibility of broadcasting to listeners to ensure long messages aren’t broadcast for people with no credits, so we can express that using a pending RSpec example. We can fill this out later.
</ruby>
<java>
We can see we’ll need something similar under the responsibility of broadcasting to listeners, to ensure long messages aren’t broadcast for people with no credits, so we can express that using a test annotated with @Ignore for the time being. We can fill this out later.
</java>
[add pending/ignored example]
It’s clear we’ll also need to test that we charge two credits for an over-long message.
<ruby>Let’s add another pending example for that.</ruby>
<java>Let’s add another ignored test for that.</java>
[add pending example]
Write out two pending specs for the behaviour in the gnarly spec
Once those two tests are implemented, we won’t need this obscure one any more. We’re not confident enough to just remove it until we’ve seen those tests fleshed out, so we can mark it as <ruby>pending</ruby><java>ignore</java> for now. That will remind us we need to come back and clean this up soon.
Disable the gnarly test - we'll remove it soon

=== Decide to split Network’s responsibilities
At this point it is becoming clear that Network has too many responsibilities. We have two different sources of feedback telling us this:
With the unit tests laid out by responsibility, we can see more clearly that while broadcasting to listeners is a responsibility that fits, there’s no real reason why the Network needs be responsible for charging for shouts.
[GoAnimate sequence diagram of how a shout is currently done]
Secondly, the communication protocol between Network and Person, exposed by the mocks, is very noisy: we’re making lots of method calls to Person in order to determine whether they can afford the shout and to deduct payment:
First Sean calls Network#broadcast
then Network asks Sean how many credits he has
then Network tells Sean the new value of his credits, with the fee for the message deducted
then Network asks Sean how many credits he has again, in order to check whether he can afford to send the message!
We could get all sad and angry that if only we’d test-driven this code in the first place we might have got this feedback sooner, but that would be futile: it’s not too late to clean this code up!
How about we make Sean responsible for organising his own payment?

