==== Lesson 2 - Questions

===== Why did we remove any reference to range or location from the first scenario "Listener hears a message"?

* They are essential to system behaviour
* They are incidental to the rule being illustrated -- TRUE
* They were only needed to triangulate the implementation
* They made the scenario too long

Explanation:
The first scenario exists to illustrate the rule "Listener hears a message." Since the behaviour is not affected by the range of a shout, neither the range nor the distance between the shouter and the listener is relevant. The information is therefore _incidental_ and should be omitted from the scenario.

===== Why do we need to know the names of people using Shouty?

* It's important that every person in the system has a real name
* It's necessary to use _persona_, where the shouter is called Sean and the listeners are called Lucy or Larry
* It doesn't matter what we call them -- but the automation code does need to be able to tell them apart -- TRUE
* The automation code has been written to recognise the names Sean, Lucy, and Larry

Explanation:
It's necessary to be able to distinguish the people that are involved in the scenario. We have called them Sean, Lucy, and Larry, but we could have called them Shouter, Listener1, and Listener2 (or even User1, User2, and User3).

We find that using _persona_ (where the name gives an indication of the person's purpose in the scenario) can be a useful way of conveying information, without cluttering up the scenario. If the names conveyed no information at all, they would not contribute to the readability of the scenario, and could be considered incidental.

===== Which pieces of information are incidental in this scenario?

Rule: Offer is only valid for Shouty users
  Scenario: Customer is not a Shouty user
    Given Nora is not a Shouty user
    And Sean shouted "free bagels until midday"
    When Nora orders a bagel and a coffee at 11:00am
    Then she should be charged 75¢ for the bagel

* Nora is not a Shouty user
* Sean is offering "free bagels!"
* Sean's offer is only valid until midday -- TRUE
* Nora orders a bagel
* Nora orders a coffee -- TRUE
* Nora places her order at 11:00am -- TRUE
* Nora gets charged for the bagel
* Nora get charged 75¢ for the bagel -- TRUE

Explanation:
This scenario is illustrating the rule that the "offer is only valid for Shouty users". It's therefore essential to know that Nora is not a Shouty user, because this means that she is not eligible for the offer.

We don't need to know that Nora orders a coffee, because that has no relevance to the rule. Nor do we need to know when the offer expires, when Nora places the order, or how much she will be charged -- there will be other rules (and other scenarios) that illustrate that behaviour.

Although it's incidental that the offer is for bagels, it is necessary to illustrate that Nora has ordered the item that is on offer to Shouty users -- and that she will be charged for that item. We use "bagels" as an example to make the scenario easier to read, not because there's something inherently special about bagels!
