=== Incidental details

The first scenario has changed since we last looked at it - it now specifies the range of a shout and the location of Sean and Lucy. This scenario exists to illustrate that a listener hears the message exactly as the shouter shouted it. All the additional details are incidental and make the scenario harder to read.

shot::["Highlight the first three line of the first scenario"]

shot::["Edit context of first scenario"]
Let's ensure that this scenario includes only essential information for the reader and remove all references to location and range.


shot::[]
We'll need to make changes to the step definitions to make sure that a Network class is always create - which we can do using a Before hook.

shot::[]
We've defaulted the range to 100. If a scenario needs to document specific range, that can still be done.

shot::[]
We'll also need to add a step definition that can create a person without the scenario needing to specify where they are located. The step definition gives each person created this way a default location of 0.

shot::[]
Let's run Cucumber to check we haven't broken anything... and we're good!

shot::[]
Looking at the two new scenarios - Listener is within range & Listener is out of range - we can see that they also contain incidental details. Since their purpose is to illustrate the "Shouts should only be heard if listener is within range" rule, there's no need to actually document the content of the shout.

shot::[]
Let's remove the details that aren't relevant to the range rule.

shot::[]
Next we fix up the step definitions

shot::[]
And finally run Cucumber - and we're still green.
