include::./title.adoc[]

shot::["hear_shout.feature"]
The first scenario has changed since we last looked at it shot::["Highlight the first three line of the first scenario"] - it now specifies the range of a shout and the location of Sean and Lucy. This scenario exists to illustrate that a listener hears the message exactly as the shouter shouted it. All the additional details are incidental and make the scenario harder to read.

[source,gherkin]
----
include::../code/java/00--step00-starting-code/shouty/src/test/resources/shouty/hear_shout.feature[lines=7..12]
----

shot::["Edit context of first scenario"]
Let's ensure that this scenario includes only essential information for the reader and remove all references to location and range.

[source,gherkin]
----
include::../code/java/02--step02-edit-first-scenario-to-remove-inessential-details/shouty/src/test/resources/shouty/hear_shout.feature[lines=7..11]
----

shot::["Add Network creation"]
We'll need to make changes to the step definitions to make sure that a Network class is always created - which we can do using an instance variable.

.StepDefinitions.java
[source,java]
----
include::../code/java/03--step03-edit-step-definitions-to-get-back-to-green/shouty/src/test/java/shouty/StepDefinitions.java[lines=22..22]
----

shot::["Highlight DEFAULT_RANGE"]
We've defaulted the range to 100. If a scenario needs to document specific range, that can still be done by explicitly including a "Given the range is ..." step.

shot::["Create new step definition"]
We'll also need to add a step definition that can create a person without the scenario needing to specify where they are located. The step definition gives each person created this way a default location of 0.

.StepDefinitions.java
[source,java]
----
include::../code/java/03--step03-edit-step-definitions-to-get-back-to-green/shouty/src/test/java/shouty/StepDefinitions.java[lines=35..38]
----

shot::["run Cucumber"]
Let's run Cucumber to check we haven't broken anything... and we're good!

shot::["Highlight message text in last two scenarios"]
Looking at the two new scenarios - Listener is within range & Listener is out of range - we can see that they also contain incidental details. Since their purpose is to illustrate the "Shouts should only be heard if listener is within range" rule, there's no need to actually document the content of the shout.

.hear_shout.feature
[source,gherkin]
----
include::../code/java/03--step03-edit-step-definitions-to-get-back-to-green/shouty/src/test/resources/shouty/hear_shout.feature[lines=15..27]
----

shot::["Delete message text"]
Let's remove the details that aren't relevant to the range rule.

.hear_shout.feature
[source,gherkin]
----
include::../code/java/04--step04-remove-incidental-details-from-range-scenarios-and-fix-stepdefs/shouty/src/test/resources/shouty/hear_shout.feature[lines=15..27]
----

shot::["Add new step definition"]
Next we add a step definition that allows Sean to shout, without needing us to specify the exact message.

.StepDefinitions.java
[source,java]
----
include::../code/java/04--step04-remove-incidental-details-from-range-scenarios-and-fix-stepdefs/shouty/src/test/java/shouty/StepDefinitions.java[lines=45..48]
----

shot::["Run Cucumber"]
And finally run Cucumber - and we're still green.

shot::["Show hear_shout.feature"]
That's better. We've removed inessential details, so that each scenario contains only the information needed to illustrate its business rule.

The scenarios would still run green if we removed the steps that set the range of a shout shot::["Highlight in last two scenarios"] , because the range already has a default value. We're not going to, because since those scenarios are illustrating the rule that deals with the range of a shout, it's an essential part of context for anyone reading them.
