==== Lesson 5 - Questions

===== We recommend you name your scenarios like which TV series?

* Cheers
* The Simpsons
* Family Guy
* Friends (*Correct*)
* Brooklyn 99

Explanation:

"The one where... " is a great way to frame the name of each of your scenarios.

===== Which of these scenario names follows the advice we gave you in this episode?

* Scenario: The one where the user logs in
* Scenario: User logs in (*Correct*)
* Scenario: User tries to log in with the wrong password (*Correct*)
* Scenario: User tries to log in with the wrong password three times (*Correct*)
* Scenario: User tries to log in with the wrong password three times and gets locked out

Explanation:

You don't actually put the words "The one where" into the scenario title - it would appear everywhere otherwise! Just imagine that it's there.

We suggest you avoid putting the _outcome_ into your scenario name, and instead just describe the context and action.

===== How many scenarios should you normally have per business rule?

* None
* Exactly one
* At least one (*Correct*)

Explanation:

Rules generalise examples, so each rule needs one or more examples to illustrate it.

===== In this episode we discovered two potentially missing scenarios. Why?

* We're constantly learning about the problem domain, and working together on the Gherkin helped us to discover some new scenarios we hadn't previously considered. (*Correct*)
* Tamsin the tester has been absent from work and wasn't doing any testing.
* We wanted to delete a scenario, and discussed the idea with our colleage who had an objection. Listening to that objection lead us to a new insight. (*Correct*)
* Paula the product owner has been too busy to pay attention to what we were doing.
* We asked the question "Is there another context that would result in a different outcome here" (*Correct*)

Explanation:

Software development is a constant process of discovery. When we can embrace this ignorance, instead of trying to pretend we know everything, and we listen to each other's perspetives, we can get insights about gaps in our knowledge, helping us to see things we hadn't considered before.