== Example Mapping

shot::[1, "Animation of Matt talking to camera"]

In the last lesson we saw how easily incidental details can creep into your scenarios, talked about why they’re a problem, and showed you some techniques for massaging them back out again.
But, as we pushed the details out of our scenarios, we made the step definition code more complicated. We promised to show you how to deal with that extra complexity, and we're going to get to that in Chapter 9.

First though, we want to look at how we could have prevented the Premium Accounts feature from getting into such a mess in the first place.

We're going to learn about a practice called Example Mapping, a way to structure the conversation between the _Three Amigos_ - Tester, Developer and Product Owner - to develop shared understanding before you write any code.

=== Example Mapping: Why?

shot::[2, "BDD circles diagram"]
In terms of the three practices we introduced in Chapter 1 - Discovery, Formulation and Automation - what went wrong with the Premium Accounts feature?

Thinking about it, we can see that the development team
shot::[3, "BDD circles diagram - (1) pointing to Automation"]
jumped straight into _Automation_ - writing the implementation of the feature. They did the bare minimum of 
shot::[4, "BDD circles diagram - (2) pointing to Formulation"]
_Formulation_ - just enough to automate a test for the feature, but really we did a lot of the Formulation later on as we cleaned it up. Finally, much of the 
shot::[5, "BDD circles diagram - (3) pointing to Discovery"]
_Discovery_ happened at the end once Tamsin had a chance to test the feature by hand.

shot::[6, "BDD circles diagram - draw a red 'X' over the three arrows"]
So in essence, they did everything backwards.

shot::[7, "Animation ending with 'Deliberate Discovery'"]
In software projects, it’s often the unknown unknowns that can make the biggest difference between success and failure. In BDD, we always try to assume we’re ignorant of some important information and try to _deliberately discover_ those unknown unknowns as early as possible, so they don’t surprise us later on.

A team that invests just a little bit extra in Discovery, before they write any code, saves themselves a huge amount of wasted time further down the line.

shot::[8, "Animation introducing three people, showing them talking"]
In lesson 1, we showed you an example of the _Three Amigos_ - Tester, Developer and Product owner - having a conversation about a new user story.

Nobody likes long meetings, so we’ve developed a simple framework for this conversation that keeps it quick and effective. We call this 
shot::[9, "Example Mapping"]
_Example Mapping_.

shot::[10, "diagram: User Story -> Example Mapping"]
An Example Mapping session takes a single User Story as input, and aims to produce four outputs:

shot::[11, "diagram: -> Rules"]
* Business Rules, that must be satisified for the story to be implemented correctly
shot::[12, "diagram: -> Examples"]

* Examples of those business rules playing out in real-world scenarios
shot::[13, "diagram: -> Questions"]

* Questions or Assumptions that the group of people in the conversation need to deal with soon, but cannot resolve during the immediate conversation
shot::[14, "diagram: -> New User Stories"]

* New User Stories, sliced out from the one being discussed in order to simplify it.

We capture these, as we talk, using index cards, or another virtual equivalent.

Working with these simple artefacts rather than trying to go straight to formulating Gherkin, allows us to keep the conversation at the right level - seeing the whole picture of the user story without getting lost in details.

=== Example Mapping: How?

shot::[1, "index cards and pens"]

We first developed example mapping in face-to-face meeting using a simple a multi-colour pack of index cards and some pens. For teams that are working remotely, there are many virtual equivalents of that nowadays.

We use the four different coloured cards to represent the four main kinds of information that arise in the conversation. 

We can start with the easy stuff: Take a yellow card and write down the name of the story.

shot::[2, "write 'premium accounts' on a yellow card"]

Now, do we already know any rules or acceptance criteria about this story?

Write each rule down on a blue card:

shot::[3, "write two rules on blue cards"]

They look pretty straightforward, but let’s explore them a bit by coming up with some examples.

shot::[4, "Show male character, with text appearing on their left"]

Darren the developer comes up with a simple scenario to check he understands the basics of the “buy” rule: I start with 10 credits, I shout “buy my muffins” and then “I want to buy some socks”, then I have zero credits. Correct?

Yes, says Paula. 
shot::[5, "Write up Darren's example on a green card"]

Darren writes this example up on a green card, and places it underneath the rule that it illustrates.

shot::[6, "Show female character"]
Tammy the tester chimes in: how about the one where you shout a word that contains “buy”, like “buyer” for example. 
shot::[7, "Show female character with text appearing"]
If you were to shout “I need a buyer for my house”. Would that lose credits too?

shot::[8, "Show second female character in foreground"]
Paula thinks about it for a minute, and 
shot::[9, "Second female character opens arms and smiles"]
decides that no, only the whole word “buy” counts. They’ve discovered a new rule! 
shot::[10, "Modify text on blue card, add new green card"]
They write that up on the rule card, and place the example card underneath it.

shot::[11, "Show male character in foreground, talking"]
Darren asks: how do the users get these credits? Are we building that functionality as part of this story too?

shot::[12, "Show female character in foreground, talking"]
Paula tells him that’s part of another story, and they can assume the user can already purchase credits. They write that down as a rule too.

shot::[13, "Write 'assumption: credit purchase has already been implemented'"]

This isn’t a behaviour rule - it’s a rule about the scope of the story. It’s still useful to write it down since we’ve agreed on it. But it won’t need any examples.

shot::[14, "Female character speaking, blank background; writing appears"]
Still focussed on the “buy” rule, Tammy asks: What if they run out of credit? Say you start with 10 credits and shout “buy” three times. What’s the outcome?

Paula looks puzzled. I don’t know. She says. I’ll need to give that some thought.

shot::[15, "Write out red card: 'What should happen when one runs out of credits?"]
Darren takes a red card and writes this up as a question.

shot::[16, "More (empty) cards appearing"]
They apply the same technique to the other rule about long messages, and pretty soon the table is covered in cards, reflecting the rules, examples and questions that have come up in their conversation. Now they have a picture in front of them that reflects back what they know, and still don’t know, about this story.

=== Example Mapping: Conclusions

[show black box diagram]

The purpose of an example mapping session is to achieve a shared understanding and agreement about the precise scope of a user story. 

We take a user story, together with some initial idea of the acceptance criteria or business rules, and try to produce examples that illustrate the behaviour. As we do that, we often end up refining the, or even slicing out new user stories to make the current one smaller. We also identify any questions that will need to be answered before the story can be turned into working software.

Although there’s no doubt of the power of examples for exploring and talking through requirements, it’s the rules that will go into the code. If you understand the rules, you’ll be able to build an elegant solution.

shot::[show feedback arrow of rules being refined]

Each time you come up with an example, try to understand what underlying rules are. If you discover an example that doesn’t fit your rules, you’ll need to reconsider your rules. In this way, the scope of the story is refined by the group.

Many people think they need to produce formal Gherkin scenarios from their three amigos conversations, but in our experience that’s only occasionally necessary. In fact, it can often slow the discussion down.

As you’ve just seen, an example mapping session should go right across the breadth of the story, trying to get a complete picture of the behaviour. Inviting all three amigos - product owner, tester and developer - is important because each perspective adds something to the conversation.

By talking through the details of the behaviour, we ensure that the tester, developer and product owner are all in agreement about what needs to be built. A shared understanding emerges between them. They also learn a little more about one another’s perspective. Some people tell us the three amigos has helped to build empathy within their team!

Sometimes, you’ll come across questions that nobody can answer. Instead of getting stuck trying to come up with an answer, just write down the question. Congratulations! You’ve just turned an unknown unknown into a known unknown. That’s progress.

[show feedback arrow of questions coming out of the black box]

Deciding what a story is not - and maximising the amount of work not done - is one of the most useful things you can do in a three amigos session. Small stories are the secret of a successful agile team. 

With this goal in mind, make sure the session isn’t just a rubber-stamping exercise, where one person does all the talking. Notice how in our example, everyone in the group was asking questions and writing new cards.

One last tip is to run your three amigos sessions in a timebox. When you’re practiced at it, you should be able to analyse a story within 25 minutes. If you can’t, it’s either too big, or you don’t understand it well enough yet. Either way, it’s not ready to play.

At the end of the 25 minutes, you can check whether everyone thinks the story is ready to start work on. If lots of questions remain, it would be risky to start work, but people might be comfortable taking on a story with only a few minor questions to clear up. Check this with a quick thumb-vote.
