==== Lesson 1 - Questions

===== What are the two domains we described in this chapter?

* Problem domain (*Correct*)
* Test domain
* Solution domain (*Correct*)
* Data domain
* User interface domain
* Core domain

Explanation:

While the word "domain" is applicable in lots of ways when talking about software, the two we're focussed on in this lesson are the *problem domain*, where our users and customer live, and the *solution domain* where our development teams and their technical tools live.

===== Imagine we're building a system for a healthcare provider. Which of these concepts are likely from the *solution* domain?

* Java (*Correct*)
* Patient
* Database (*Correct*)
* Doctor
* Message broker (*Correct*)
* Flight
* Medicine
* CSS class (*Correct*)
* Checkup
* JavaScript (*Correct*)
* Airport
* Blood pressure
* XML (*Correct*)
* Bed
* JSON (*Correct*)
* Air miles
* Availability
* REST endpoint (*Correct*)
* Waiting list

Explanation:

Words matter. You might have found this difficult because you're someone who works in the solution domain, *and* you're also probably someone who's been to a hospital, so you can speak the language of both of these domains.

Remember that for people who come from the problem domain, these words from the solution domain can be confusing.

===== Imagine we're building a system for a healthcare provider. Which of these concepts are likely from the *problem* domain?

* Java 
* Patient (*Correct*)
* Database
* Doctor (*Correct*)
* Flight
* Message broker
* Medicine (*Correct*)
* CSS class
* Checkup (*Correct*)
* JavaScript
* Airport
* Blood pressure (*Correct*)
* XML
* Bed (*Correct*)
* JSON
* Air miles
* Availability (*Correct*)
* REST endpoint
* Waiting list (*Correct*)

Explanation:

Problem domain language is the language you'll hear people say when they talk about the system from a user's perspective.

===== What's the right term for words that have the same meaning in both the problem and solution domains?

* Unique language 
* Ubiquitous language (*Correct*)
* Programming language
* Proper language
* Enterprise domain
* General language

Explanation:

The term 'ubuquitous language' comes from Eric Evans' brilliant book, Domain Driven Design.

As a consulting who worked on multiple projects, Eric noticed that a common factor between the projects that went well, was that *people used the same words for stuff*.

So if the business people referred to "Blood pressure" in their conversations, the database table where we stored records of those measurements would also be called `BloodPressure` and not something that the engineers made up, like `tbl_user_metric_items`