=== Problem and Solution Domains

When we build software, we’re always working across two domains.

[picture of the two overlapping circles]

There’s the problem domain, where our customers and business stakeholders live, and there’s a solution domain, where we solve those business problems using technology.

Each domain has its own jargon, it’s own dialect. That’s fine: specialized language helps domain experts to communicate. Often though, this jargon can prevent us from understanding one another across the two domains.

As BDD practitioners, we’re focussed on trying to grow this area in the middle, where we have a common or ubiquitous language. We know that the bigger this shared vocabulary is, the quicker the team can communicate ideas between the business and technology-facing sides of the team.

We’ve also heard it said that if you model the problem well enough, the solution will take care of itself.

Certainly, we believe that the better an understanding you have of the problem domain, the better a solution you can build. That’s why Cucumber is so powerful, because it helps you to stay rooted in the problem domain.