include::./title.adoc[]

////
Overview: 
* Automate: Given Lucy is located 15m from Sean (create Person class)
* Automate: When Sean shouts "free bagels at Sean's" (move declarations to instance field)
* Automate: Then Lucy hears Sean's message (add assertion)
////

// *** Automate: Given Lucy is located 15m from Sean (create Person class) ***

shot::[1, "still"]
Now that we have the step definitions matching, we can start working on our solution. We like to use our scenarios to _guide_ our development, so we'll start designing the objects we'll need by sketching out some code in our step definitions.

The scenario will be failing while we do this, but we should see the error messages gradually progressing as we drive out the interface to our object model.

Our next goal is for the scenario to fail because we need to implement the actual business logic. _Then_ we can work on changing the business logic inside our objects to make it pass.

.StepDefinitions.cs
[source,csharp]
----
[Binding]
public class StepDefinitions
{
    [Given("Lucy is located {int}m from Sean")]
    public void GivenLucyIsLocatedMFromSean(int distance)
    {
        throw new PendingStepException();
    }

    [When("Sean shouts {string}")]
    public void WhenSeanShouts(string p0)
    {
        throw new PendingStepException();
    }

    [Then("Lucy hears Sean's message")]
    public void ThenLucyHearsSeanSMessage()
    {
        throw new PendingStepException();
    }
}
----

To implement the first step, we need to create a couple of `Person` objects, one for Lucy shot::[2, "declare var for lucy"] and one for Sean.shot::[3, "paste var for sean"]

[source,csharp]
----
[Given(@"Lucy is located {int}m from Sean")]
public void GivenLucyIsLocatedMFromSean(int distance)
{
    var lucy = new Person();
    var sean = new Person();

    // ...
}
----


Then we create the `Person` class into our production project to remove the errors.shot::[4, "add new class in Shouty"] To make it visible for the SpecFlow project, shot::[5, "add public"] we need to make it _public_.

[source,csharp]
----
namespace Shouty
{
    public class Person
    {
    }
}
----

shot::[6, "go back to step defs"] In order to complete the step definition for the _Given_ step, we need to specify the distance between Lucy and Sean.

shot::[6.1, "02.05.animation.mp4"]

To keep things simple, we're going to assume all people are situated on a line: a one-dimensional co-ordinate system. We can always introduce proper geo-locations later. We'll place Sean in the centre, and Lucy 15 metres away from Sean.

This might not be the design we'll end up with once this is all working, but it's a decent place to start.

shot::[7, "back at stepdefs, still"]We can implement our simple distance concept by introducing a `MoveTo` method like this:shot::[8, "add MoveTo call"]

[source,csharp]
----
[Given(@"Lucy is located {int}m from Sean")]
public void GivenLucyIsLocatedMFromSean(int distance)
{
    var lucy = new Person();
    var sean = new Person();
    lucy.MoveTo(distance);

    throw new PendingStepException();
}
----

We have two instances of person, one representing Lucy, shot::[9, "select lucy"]and one representing Sean. shot::[10, "select sean"]Then we call a method to move Lucy to the position specified in the scenario.shot::[11, "select MoveTo call"]

As this seems to be complete like this, we can remove the pending exception.shot::[12]

There is no `MoveTo` method yet, shot::[13, "move mouse to the error"] so Visual Studio reports a compilation error. To fix it, we can create the method on the `Person` class, shot::[14, "use lightbulb"] but at this stage we don't bother with the correct implementation. shot::[15, "remove exception"] It is enough if it compiles, so an empty method is just fine for now.

[source,csharp]
----
namespace Shouty
{
    public class Person
    {
        public void MoveTo(int distance)
        {
        }
    }
}
----


shot::[16, "back to stepdefs, run tests"]
When we run the scenario, the first step should be passing! The easiest way to see this is to open the test output by clicking on the "Open additional output for this result" link shot::[17, "click link"] and check the "Standard Output" section. Here you can see all steps executed by SpecFlow with their results. The first step is "done" shot::[18, "select first step"] and the two others are still pending shot::[19, "select the other steps"].

[source,bash]
----
Given Lucy is located 15m from Sean
-> done: StepDefinitions.GivenLucyIsLocatedMFromSean(15) (0.0s)
When Sean shouts "free bagels at Sean's"
-> pending: StepDefinitions.WhenSeanShouts("free bagels at Se...")
Then Lucy hears Sean''s message
-> skipped because of previous errors
----

We're making progress!

We'll keep working like this until we see the scenario failing for the right reasons.



// *** Automate: When Sean shouts "free bagels at Sean's" (move declarations to instance field) ***

shot::[20, "back to stepdefs"]
In the second step definition, we want to tell Sean to shout something.

In order to send instructions to Sean from the "When" step, we need to store him shot::[21, "select var decl"] in an _instance field_, so that he'll be accessible from all of our step definitions. Let's move both declarations up to class level together with the initializations. shot::[22, "move lines up, fix var, private"] 

shot::[23, "scroll to When"]
In the `When` step, we're capturing Sean's message using shot::[24, "select {string}"] _this_ pattern that is mapped to the parameter shot::[25, "select p0"] `p0`. Let's give it a more meaningful name.shot::[26, "rename to 'message'"]
Don't worry if the pattern sounds unfamiliar to you, we will look at that in detail in the next chapter.

And now we can tell Sean to _shout_ the message: shot::[27, "add sean.Shout(message) and remove throw"]

[source,csharp]
----
[Binding]
public class StepDefinitions
{
    private Person lucy = new Person();
    private Person sean = new Person();

    //...

    [When(@"Sean shouts ""([^""]*)""")]
    public void WhenSeanShouts(string message)
    {
        sean.Shout(message);
    }

    //...
}
----

We eliminate the compilation error by declaring the `Shout` method in the `Person` class. shot::[28, "use lightbulb"] shot::[28.1, "remove throw"]

[source,csharp]
----
namespace Shouty
{
    public class Person
    {
        public void MoveTo(int distance)
        {
        }

        public void Shout(string message)
        {
        }
    }
}
----

When we run the scenario again, shot::[29, "run"] the second step shot::[30, "open output, select second step"] is also passing!.

[source,bash]
----
Given Lucy is located 15m from Sean
-> done: StepDefinitions.GivenLucyIsLocatedMFromSean(15) (0.0s)
When Sean shouts "free bagels at Sean's"
-> done: StepDefinitions.WhenSeanShouts("free bagels at Se...") (0.0s)
Then Lucy hears Sean''s message
-> pending: StepDefinitions.ThenLucyHearsSeanSMessage()
----



// *** Automate: Then Lucy hears Sean's message (add assertion) ***

shot::[31, "back to stepdefs"]
The last step definition is where we implement a check, or assertion. We'll verify that what Lucy has heard is exactly the same as what Sean shouted.

Once again we're going to write the code we wish we had. shot::[32, "paste assert statement"] In that we are going to use an assertion from the `Xunit` library, so we need to add the necessary namespace usages.

shot::[33, "add xunit namespace using"]

[source,csharp]
----
[Then(@"Lucy hears Sean's message")]
public void ThenLucyHearsSeanSMessage()
{
    Assert.Contains(messageFromSean, lucy.GetMessagesHeard());
}
----

So we need a way to ask Lucy what messages she has heard, and we also need to know what it was that Sean shouted.

We can record what Sean shouts shot::[34, "select message in when"] by storing it in an instance field as the `When` step runs. shot::[35, "declare a field and update"] This is a common pattern to use in SpecFlow step definitions when you don't want to repeat the same test data in different parts of a scenario. Now we can use that in the assertion check. shot::[36, "select messageFromSean in Then"]

[source,csharp]
----
[When(@"Sean shouts {string}")]
public void WhenSeanShouts(string message)
{
    sean.Shout(message);
    messageFromSean = message;
}
----

We also need to add a `GetMessagesHeard` method to our Person class.shot::[37, "use lightbulb"] Let's just return null for now.shot::[38, "add return null"]

[source,csharp]
----
public class Person
{
    public void MoveTo(int distance)
    {
    }

    public void Shout(string message)
    {
    }

    public IList<string> GetMessagesHeard()
    {
        return null;
    }
}
----

...and watch SpecFlow run the tests again.shot::[39, "run, open result"]

[source,bash]
----
Given Lucy is located 15m from Sean
-> done: StepDefinitions.GivenLucyIsLocatedMFromSean(15) (0.0s)
When Sean shouts "free bagels at Sean's"
-> done: StepDefinitions.WhenSeanShouts("free bagels at Se...") (0.0s)
Then Lucy hears Sean's message
-> error: Value cannot be null. (Parameter 'collection')
----

This is great! Whenever we do BDD, getting to our first failing test is a milestone. Seeing the test fail proves that it is capable of detecting errors in our code!

Never trust an automated test that you haven't seen fail!

Now all we have to do is write the code to make it do what it's supposed to.
