include::./title.adoc[]

When writing scenarios, occasionally we want to use a really long piece of data. shot::[1,"Show feature file"]

For example, let’s introduce a new rule about the maximum length of a message shot::[2,"New rule"]

.hear_shout.feature
[source,gherkin]
----
include::../code/ruby/16-max-length-rule/features/hear_shout.feature[lines=42]
----

...and add a scenario to illustrate it shot::[3,"New scenario"], making the string just over the boundary of the rule:

[source,gherkin]
----
include::../code/ruby/16-max-length-rule/features/hear_shout.feature[lines=44..48]
----

That’s pretty ugly isn’t it!

Still, we’ll press on and get it to green, then we’ll show you how to clean it up.

shot::[4,"run Cucumber"] Our existing step definition handles that ugly step with the long message just fine, but the last outcome step is undefined. We could either add a new step definition, or parameterise "Larry should not hear a shout". Let's modify the existing step definition shot::[5,"Modify stepdef"]

.steps.rb
[source,ruby]
----
include::../code/ruby/17-parameterise-stepdef/features/step_definitions/steps.rb[lines=45..47]
----

shot::[6,"run cucumber"]

OK, so we have a failing acceptance test.shot::[7] Let’s dive down into our solution and implement this new rule. It seems like the Network should be responsible for implementing this rule, so let’s go to its unit tests shot::[8,show NetworkTest] As we explain in more detail in the next lesson, we start by adding a new example to specify this extra responsibility. shot::[9, start creating new unit test]

We’ll create a 181-character message like this shot::[10,finish implementing unit test] and then assert that the message should not be heard when it’s broadcast.shot::[11]

.network_spec.rb
[source,ruby]
----
include::../code/ruby/18-add-test-to-networktest/spec/network_spec.rb[lines=36..46]
----

Let’s run that test shot::[12,"run Cucumber - show the unit test results"]shot::[13]. Good, it fails. Lucy’s still getting the message at the moment. Now how are we going to implement this?

It looks like we’re already implementing the proximity rule here shot::[14,"Network proximity logic"] in the broadcast method. Let’s add another if statement here about the message length. shot::[15,"add message length logic"] 

.shouty.rb
[source,ruby]
----
include::../code/ruby/19-implement-maximum-length/lib/shouty.rb[lines=35..37]
----

Run the unit test again… and it’s passing.shot::[16]

And cucumber is green as well shot::[17,"run cucumber"]

Great.

The code here has got a little bit messy and hard to read. shot::[18,"show the modified logic in the Network class"]
One very basic move we could make to improve it would be to just extract a couple of temporary variables, one for the range rule shot::[19,"extract range temporary variable"] and one for the length rule. shot::[20,"extract length temporary variable"]

.shouty.rb
[source,ruby]
----
include::../code/ruby/20-tidy-up-network-logic/lib/shouty.rb[lines=33..42]
----

That’s better. This code could be improved even further of course, but at least we haven’t made it any worse.

Let’s just run the tests to check. shot::[21,"run cucumber"] Great - everything’s still green.

Now we have everything passing again, we can tidy up the Gherkin to use a new piece of syntax we’ve been wanting to tell you about: a DocString. shot::[22,"show message length scenario in feature file"]

DocStrings allow you to specify a text argument for a step that spans over multiple lines. We could change our step to look like this instead: shot::[23,"convert message to DocString"]

[source,gherkin]
----
include::../code/ruby/21-docstring/features/hear_shout.feature[lines=44..55]
----

Now the scenario is much more readable. shot::[24,"show existing stepdef code"]

shot::[25,"show existing stepdef code"]
We have to add a new step definition too shot::[26,"sean_shouts_the_following_message"]. It doesn't need a parameter in the Cucumber Expression shot::[27] -- the DocString gets passed as a string argument to the step definition automatically.shot::[28]

Now we can fill out the rest of our new step definition. shot::[29]

.steps.rb
[source,ruby]
----
include::../code/ruby/21-docstring/features/step_definitions/steps.rb[lines=33..36]
----

Let's check that we're still green shot::[30,"run cucumber"]shot::[31] -- and we are!

We don’t use DocStrings very often - having such a lot of data in a test can often make it quite brittle. But when you do need it, it's useful to know about.
