=== Organinizing step definitions into multiple files

include::./script.common-intro.adoc[]

To show you how this works, we can move all the steps to do with shouting over to a separate class.

First, create a file called `shout_steps.rb` shot::[1]

Now we can cut and paste those steps from the existing `steps.rb` file into this new one: shot::[2]

[source,ruby]
----
include::../code/ruby/10-extract-shout-steps/features/step_definitions/shout_steps.rb[]
----

And run Cucumber shot::[] to check everything's still working. Great.

Breaking apart your step definitions into multiple files is more of an art than a science, but we can give you a couple of pieces of advice. We've seen teams try to organise their step definitions by feature so that, for example, the premium accounts feature would have its own steps file. We find that tends to work out badly, since while feature files live in the problem domain, step definitions are closer to the solution domain. Usually multiple features will need to carry out common actions against the system (think of logging in, for example), so this leaves us with low cohesion: step definitions that sit together in the same file, but don't have much in common with each other.

We find it's better to organise your steps by which part of the system they act on. This is a bit hard to illustrate in a tiny solution like Shouty, but bear this in mind when you're working on your own projects.

We could continue to move code from our step definitions into the support layer. For example, we could write a support method for generating messages of a certain length shot::[1, "Highlight lines 15-16"], 

[source,ruby]
----
include::../code/ruby/10-extract-shout-steps/features/step_definitions/shout_steps.rb[lines=13..19]
----

or a method for asserting that a person has heard certain messages. shot::[1, "Highlight lines 22-24"]

[source,ruby]
----
include::../code/ruby/10-extract-shout-steps/features/step_definitions/steps.rb[lines=21..25]
----

Ideally, each step definition shot::[3] should only contain one or two lines that delegate to your support code. 

[source,ruby]
----
include::../code/ruby/10-extract-shout-steps/features/step_definitions/steps.rb[lines=9..11]
----

include::./script.common-end.adoc[]
