==== Lesson 3 - Questions


===== Which of the following first lines changes the language of a feature file?

* # language: en-lol ----TRUE
* ! language: en-lol
* language: en-lol
* # i18n: en-lol

Explanation:
Gherkin supports lots of languages on a per feature file basis. It has to be the first line in the feature file, and has to be a comment with the content `language: <language_identifier>`

===== What conventions for method naming does Cucumber support when generating snippets? ** MULTIPLE-CHOICE **

* allcaps
* pascalcase
* snakecase ----TRUE
* rhinocase
* camelcase ----TRUE
* hyphenated

Explanation:
Camel-case is the idiomatic Java naming convention with the first letter of all words (except the first) capitalised e.g. thisIsAStepDefinitionMethodName

Snake-case uses underscores to separate words and was popularised by C e.g. this_is_a_step_definition_method_name

===== Why would you choose to execute scenarios in a random order?

* For fun
* To help discover memory leaks
* The best documentation is always sorted randomly
* To ensure scenarios are isolated from each other ----TRUE
* Scenarios, when run in parallel, are always executed in a random order

Explanation:
Scenarios should be isolated from each other - which means that one scenario should never rely on the behaviour of any other scenario for it to behave as expected. Cucumber is implemented to facilitate the cleaning of state after each scenario, but cannot guarantee this. Random execution order can help identify unintentional dependencies between scenarios.
