include::./title.adoc[]

Cucumber is first and foremost a tool that facilitates a common understanding between people on a project. Imagine our customers were cats. We could write our features in English, but the cats would obviously not understand that, so I'll show you how to write a scenario in LOLCAT instead.

You can get a list of all the supported languages with --i18n help. shot::[1]

[source]
----
mvn exec:java -Dexec.mainClass=io.cucumber.core.cli.Main -Dexec.classpathScope=test -Dexec.args="--i18n help"
----

Cucumber supports over 70 different languages, thanks to contributions from people from all over the world.

To see the translation of the Gherkin keywords for a particular language, just replace 'help' with the language code. shot::[2]

[source]
----
mvn exec:java -Dexec.mainClass=io.cucumber.core.cli.Main -Dexec.classpathScope=test -Dexec.args="--i18n en-lol"
----

Now create a new feature file in src/test/resources called cat.feature shot::[3]

The first line tells Cucumber which language the feature file is written in. shot::[4]
.cat.feature
[source,gherkin]
----
include::../code/java/08-add-lolcat-feature/shouty/src/test/resources/shouty/cat.feature[lines=1]
----

Cucumber then expects the Gherkin keywords to be in LOLCAT shot::[5]

.cat.feature
[source,gherkin]
----
include::../code/java/08-add-lolcat-feature/shouty/src/test/resources/shouty/cat.feature[lines=3..]
----

The step is undefined, but we can quickly generate it by running Cucumber shot::[6, run new scenario] Cucumber has generated a step definition name in 'snake case' - each word separated by an underscore. shot::[7, "highlight stepdef name"] Although we prefer this naming convention for test names, it's more idiomatic to use camel case naming in Java. Let's add a line to our property file. shot::[8, "add 'cucumber.snippet-type=camelcase'"]

.cucumber.properties
[source,java]
----
include::../code/java/09-choose-camelcase-snippet-generation/shouty/src/test/resources/cucumber.properties[]
----

Now when we run Cucumber shot::[9], the snippet method name is generated in CamelCase.shot::[10] Implementing step definitions in non-english languages is exactly the same, so we won't go any further with LOLCAT just now. Let's delete the cat.feature file shot::[11] and check that we're still green shot::[12]

Notice that the scenarios in hear_shout.feature are being run in the order that the occur in the feature file shot::[13, expand/highlight the test results] That's fine, but there's a chance that since they always run in the same order we might accidentally make one scenario dependent on some other scenario.

Each scenario should be isolated - it's result should not depend on the outcome of any other scenario. To help you catch any dependencies between your scenarios, Cucumber can be told to run your scenarios in a random order.


To do this, set the cucumber.execution.order propoerty in the property file shot::[14, "add line to cucumber.properties"]

.cucumber.properties
[source,java]
----
include::../code/java/11-randomise-scenario-execution-order/shouty/src/test/resources/cucumber.properties[]
----

Now when we run Cucumber, the scenarios are run in a random order shot::[15, run Cucumber & show new order of scenario execution]. Now there's almost no chance of a dependency between scenarios slipping through without being noticed.

shot::[16, "show 'List configuration options' section of website"]
A full list of Cucumber's configuration properties can be found on the https://cucumber.io/docs/cucumber/api/#options[Cucumber website]. shot::[17, show list of properties on website] There's also a help page included with Cucumber, which can be printed using Maven. shot::[18, "run maven in console, highlight the OPTIONS help text"]shot::[19]. This lists both the names of the command line options shot::[20, highlight top of output] and the system properties shot::[21, scroll down output]

[source]
----
mvn exec:java -Dexec.mainClass=io.cucumber.core.cli.Main -Dexec.classpathScope=test -Dexec.args="--help"
----

That's quite a lot to digest, but to make Cucumber really useful to your team, it’s good to spend some time learning the details of how to configure it. In this lesson, we showcased two of Cucumber’s configuration options and you learned how to write your scenarios in different spoken languages.
