=== More Control

shot::[1, "feature file is open"]

SpecFlow is first and foremost a tool that facilitates a common understanding between people on a project. To be able to express the domain requirements of projects implemented specifically for a non-English speaking local market, translating everything to English might be a barrier. In this case it is better to describe the requirements in the spoken language the stakeholders speak.

SpecFlow supports over 70 different languages, thanks to contributions from people from all over the world.

To see the translation of the Gherkin keywords for a particular language, check out the https://cucumber.io/docs/gherkin/languages/[Gherkin syntax documentation]. shot::[2.1, "open docs"] For example, this is how the keywords translate to Hungarian. shot::[2.2, "scroll to Hungarian"]

Let's see how someone would create a feature file written in a different spoken language. I will do this for the Hungarian language, but you can choose another language you speak.

For that we can add a new feature file first... and make it empty. shot::[3, "add feature file, delete content"]

The first line tells SpecFlow which language the feature file is written in. shot::[4]

.Hungarian.feature
[source, gherkin]
----
#language: hu-HU
----

Now we can start writing our feature file. Remember, it should start with the feature keyword. The auto-complete feature of the Visual Studio integration is for your help. shot::[5, "invoke auto-complete, choose 'Jellemző'"] It shows which keyword I should use. shot::[6, "finish line"]

.Hungarian.feature
[source, gherkin]
----
#language: hu-HU

Jellemző: Kiáltás meghallása
----

We can keep editing the file by adding a scenario. In the selected language, of course... shot::[7, "add scenario"]

.Hungarian.feature
[source, gherkin]
----
#language: hu-HU

Jellemző: Kiáltás meghallása

Forgatókönyv: A hallható meghall egy üzenetet
	Adott egy ember Sean
	És egy ember Lucy
	Ha Sean azt kiáltja, hogy "Ingyen bagel a Sean's-nál"
	Akkor Lucynak meg kell hallania Sean üzenetét
----

This is Cucumber School and not a Hungarian lesson, but you might have guessed that my scenario tells the same story that we described in the "Listener hears a message" scenario earlier. shot::[8, "show 'Listener hears a message' scenario"] But if we look at this new scenario shot::[9, "switch back to the hungarian, highlight orange steps"] we can see that Visual Studio reports the steps as undefined. This is because we have used the English step texts in our Cucumber Expressions. shot::[10, "jump to stepdef GivenAPersonNamed"] In order to make this pass, we would need to add step definitions with Hungarian texts in the expressions or add an additional Given, When or Then attribute to our step definition methods with the Hungarian text, like this. shot::[11, "add hun Given attribute to the method"]

.StepDefinitions.cs
[source,c#]
----
[Given("egy ember {word}")]
[Given("a person named {word}")]
public void GivenAPersonNamed(string name)
{
    people.Add(name, new Person(network, 0));
}
----

If we build the project, the first two steps appear to be defined now. shot::[12, "build and see the feature file coloring changing"]

We can fix the other two step definitions as well... shot::[13, "add the two other attributes, run tests"] and we have our first Hungarian shouty scenario pass! shot::[14, "show new scenario in the test explorer window"]

.StepDefinitions.cs
[source,c#]
----
[When("Sean azt kiáltja, hogy {string}")]
[When("Sean shouts {string}")]
[When("Sean shouts the following message")]
public void WhenSeanShoutsAMessage(string message)
{
    people["Sean"].Shout(message);
    messageFromSean = message;
}

[Then("Lucynak meg kell hallania Sean üzenetét")]
[Then("Lucy should hear Sean's message")]
public void ThenLucyShouldHearSeansMessage()
{
    Assert.Contains(messageFromSean, people["Lucy"].GetMessagesHeard());
}
----


Usually the feature file languages are not mixed within a project. If you don't want to add the same language header line shot::[15, "highlight #language"] to all of the feature files, you can also change the default feature file language in SpecFlow.

For that we need to add a SpecFlow configuration file to our project. The SpecFlow configuration file is a simple JSON file, named `specflow.json`. shot::[16, "add specflow.json"]. This file needs to be copied to the output directory. shot::[17, "set 'copy to output directory' to 'copy if newer'"]

As there is no auto-complete support for this file, it's easiest to check out the https://docs.specflow.org/projects/specflow/en/latest/Installation/Configuration.html[SpecFlow documentation]. shot::[18, "open doc"] The first example here does exactly what we want, so we can just copy and paste it into our project, shot::[19, "copy paste sample"] and change the language to the one we have chosen. shot::[20, "set lang to hu-hu"]

.specflow.json
[source,json]
----
{
  "language": {
    "feature": "hu-HU"
  }
}
----

When we build the project, shot::[21, "build, show errors"] we got lots of errors from our English feature file. This is because we changed the default and this file does not have a language setting at the top. shot::[22, "show eng feature file, fix by adding #language: en-US"] But the new file works without the language setting now... shot::[23, "switch to hun, remove language setting"]

In Chapter 3 we talked about step definition parameters and that SpecFlow helps you to convert them to a .NET data type. SpecFlow performs these conversions using the feature file language. So for example if you include a fractional number that needs to be converted to double, SpecFlow will expect the decimal separator character used in the language of your feature file. In the Hungarian language for example, a comma is used as the decimal separator instead of a dot. This is also important for date conversions.

This default behavior can be changed by explicitly declaring what culture setting SpecFlow should use for conversions. For example we can force the conversions to be made using US English culture even in Hungarian feature files. shot::[24, "change config file to"]

.specflow.json
[source,json]
----
{
  "language": {
    "feature": "hu-HU"
  },
  "bindingCulture": {
    "name": "en-US"
  }
}
----

There are a few other things you can configure that you can find in the documentation. shot::[25, "switch to doc, scroll through to the bottom"] It's worth highlighting the one that can instruct SpecFlow to load step definitions from other external projects as well. shot::[26, "highlight stepAssemblies"] This is useful in bigger applications with multiple SpecFlow projects.

For the rest of this chapter, let's remove the non-English feature file and reset the configuration by removing the `specflow.json` file. shot::[27, "remove Hungarian.feature, specflow.json"]

That's quite a lot to digest, but to make SpecFlow really useful to your team, it’s good to spend some time learning the details of how to configure it. In this lesson, we showcased the SpecFlow configuration options and you learned how to write your scenarios in different spoken languages.
