==== Lesson 3 )Ruby, Java, JS)

===== Which of the following is NOT a built in Cucumber Expression parameter type?

* float - FALSE
* integer - TRUE
* string - FALSE
* word - FALSE

Answer: The Cucumber Expression parameter type that matches an integer is `{int}`, not `{integer}`

===== Which of the following statements is true?

* You cannot create your own Cucumber Expression parameter types - FALSE
* Cucumber discards the value that matches a Cucumber Expression parameter type - FALSE
* Your step definition code will be passed the value that matched the Cucumber Expression parameter type - TRUE
* Cucumber always passes the matched parameter as a string - FALSE

Answer: Cucumber will pass the step definition a parameter for each Cucumber Expression parameter type. Cucumber will attempt to convert the text that matched into a suitable format. Using the `{int}` parameter type will result in a number being passed to the step definition. You can extend the predefined Cucumber Expression parameter types, by creating your own.

==== Lesson 3 - Questions (SpecFlow/C#/Dotnet)

===== Which of the following is NOT a built in Cucumber Expression parameter type?

* float - FALSE
* integer - TRUE
* string - FALSE
* word - FALSE

Answer: The Cucumber Expression parameter type that matches an integer is `{int}`, not `{integer}`

===== Which of the following statements is true?

* You cannot create your own Cucumber Expression parameter types - FALSE
* Cucumber discards the value that matches a Cucumber Expression parameter type - FALSE
* Your step definition code will be passed the value that matched the Cucumber Expression parameter type - TRUE
* SpecFlow always passes the matched parameter as a string - FALSE

Answer: SpecFlow will pass the step definition a parameter for each Cucumber Expression parameter type. SpecFlow will attempt to convert the text that matched into a suitable format. Using the `{int}` parameter type will result in a number being passed to the step definition. You can extend the predefined Cucumber Expression parameter types, by creating your own.
