include::./title.adoc[]

Sometimes, we want to write step definitions that allow us to use different values in our Gherkin scenarios. For example, we might want to have other scenarios that place Lucy a different distance away from Sean. shot::[1]

.hear_shout.feature
[source,gherkin]
----
include::../code/js/03-matching-an-integer-value/features/hear_shout.feature[]
----

To capture interesting values from our step definitions, we can use a feature of Cucumber Expressions called _parameters_.

For example, to capture the number of metres, we can use the `{int}` parameter: shot::[2] which is passed as an argument to our step definition: shot::[3]

.steps.js
[source,js]
----
include::../code/js/03-matching-an-integer-value/features/step_definitions/steps.js[lines=3..3]
----

Now we’re capturing that value as an argument. The value `100` will be passed to our code automatically by Cucumber.

Because we've used Cucumber Expressions' built-in `{int}` parameter type, the value has been cast to a Number for us automatically, so we can do maths with it if we want.shot::[4]

.steps.js
[source,js]
----
include::../code/js/03-matching-an-integer-value/features/step_definitions/steps.js[lines=3..8]
----

Cucumber has a bunch of built-in parameter types: `{int}`, `{float}`, `{word}` and `{string}`. You can also define your own, as we'll see later.
