==== Lesson 4 - Questions


===== Which of the commands below would run all scenarios and save the execution results to a file 'result.trx'?

* dotnet test --logger trx
* dotnet test --out result.trx
* dotnet test --logger trx;logfilename=result.trx ----TRUE
* TRX file format is not supported by `dotnet test`

Explanation:
The test output of the `dotnet test` command can be configured by specifying a logger. The trx logger can be used for saving the results to a TRX file. By default it saves the result to a file name containing the current timestamp. To use a deterministic filename, the `logfilname` parameter has to be provided.


===== Why is it valuable to generate reports about the SpecFlow test execution results? ** MULTIPLE-CHOICE **

* The readable report can help the business stakeholders follow the progress of the implementation and therefore increases trust. ----TRUE
* Without HTML reports, the test execution results cannot be checked.
* It is easier to assess the impact of a test failure when it is connected to the business expectations. ----TRUE
* It is easier to quickly react to failures coming from the Continuous Integration Server (CI) when you don't need special tools, like Visual Studio to view the results. ----TRUE
* The reports are not directly valuable, they are just required to fulfill the policies of the development process.
