include::./title.adoc[]

shot::[1, "Animation"]
Hello, and welcome back to Cucumber School.

Last time we learned about two very different kinds of loops. First, we used DataTables to loop over data in your scenarios.

Then we learned about TDD cycles. We saw how the outer loop of TDD helps you to build the right thing while the inner loop helps you build the thing right.

In this lesson, we’re going to teach you all about how to work effectively with Cucumber.

shot::[2, "Scroll through shout.feature, end by showing scenario 'Message too long'"]
When we start working on a new scenario we often take a dive down to the inner TDD loop where we use a unit testing tool to drive out new classes or modify the behaviour of existing ones. When our unit tests are green and the new code is implemented we return to the Cucumber scenarios to verify whether we have made overall progress or not.

If we have lots of Cucumber scenarios, it can be distracting to run all of them each time we do this. We often want to focus on a single scenario - or perhaps just a couple - to get feedback on what we’re currently working on.

There are several ways to do this in Cucumber - and your IDE may offer other options. We'll start by showing some basic filtering using Maven on the command line, before showing you some alternatives.

Probably the easiest way to filter is to tell Cucumber to run only a scenario with a particular name.

shot::[3, "type mvn command in console, show output and highlight that it has only run the one scenario 'Message too long'"]
We can pass arguments to Cucumber using the property cucumber.filter.name. This property tells Cucumber to only run scenarios with a name that matches the string provided, in this case "Message is too long".

[source]
----
mvn test -Dcucumber.filter.name="Message is too long"
----

The value of the cucumber.filter.name option is actually a regular expression, so you can use your imagination here to run more than one scenario. Let's use it to run all scenarios with the text "range" in their name. shot::[4, "type mvn command in console, show output and highlight that it has run the two scenarios containing the word 'range'"]shot::[5]

[source]
----
mvn test -Dcucumber.filter.name="range"
----

Another way to tell Cucumber to run a specific scenario is to specify the line number of the scenario within a feature file. The 'Message too long' scenario starts on line 44 in the feature file. shot::[6, "in feature file show that 'Message too long' starts on line 44 (ART: Highlight this in editing)"]

We can use that line number when we run Cucumber. shot::[7, "add entry to mvn command"]shot::[8]

[source]
----
mvn test -Dcucumber.features="src/test/resources/shouty/hear_shout.feature:44"
----

shot::[9, "type mvn command in console, show output and highlight that it has only run the scenario called 'Message too long'"]

You can even specify multiple line numbers for each file. Let's run 'Two shouts' as well. [shot::[10, "in feature file, show 'Two shouts' starts on line 33 (ART: Highlight this in editing)"]

Let's add that line number to the Maven command.shot::[11, "type mvn command in console, show output and highlight that it has run two scenarios - 'Two shouts' and 'Message too long'"]shot::[12]shot::[13]

[source]
----
mvn test -Dcucumber.features="src/test/resources/shouty/hear_shout.feature:33:44"
----

You can list several files and lines together like this if you have a specific set of scenarios you want to run.

The examples that you've just seen use the -D option to set a Java system property on the command line. If you're working in an IDE this is less than ideal, but fortunately there are other ways to achieve exactly the same outcome.

Let's look at using a property file to set the system properties. Create a property file called cucumber.properties in src/test/resources (or open it if it already exists in your project). shot::[14] Add the line `cucumber.filter.name=range` shot::[15]

.cucumber.properties
[source]
----
include::../code/java/01-filter-by-name-using-properties-file/shouty/src/test/resources/cucumber.properties[]
----

When we run maven, Cucumber picks up the property setting from the file and only runs the "range" scenarios. shot::[16, "type `mvn test` in console, show output and highlight that it has run the two scenarios containing the word 'range'"]shot::[17]shot::[18]

[source]
----
mvn test
----

The property file is also picked up if you run Cucumber from within your IDE shot::[19, use IntelliJ to run all scenarios in `hear_shout.feature` and then highlight that only the range scenarios have been run]

The benefit of a properties file is that it gets checked in with your code, which means that any settings can be shared by all team members.


The final thing I want to show you in this lesson is how to run a single scenario directly from IntelliJ. Right click on the scenario and select "Run Scenario:" shot::[20,"right click, show that there are many options to choose from, click 'Run Scenario' and highlight that it has only run the scenario called 'Message too long'"]

In this lesson you've learnt how to filter the set of scenarios to run using scenario names and line numbers from the command line and using property files.
