=== Running the scenarios from the command line

shot::[1, "show feature file with tagged scenarios"]

In the previous lesson, we ran the SpecFlow scenarios in Visual Studio. That gives you the quick feedback that you need during development.

But we also would like to regularly ensure that the changes we made didn't cause any regressions. For that we can kick off the full test execution on a Continuous Integration Server or from a console on your local machine so we can keep working on other things while it's finished.

It does not matter whether you need to configure your Continuous Integration build or you want to run the test from a console locally, the .NET command line tools have to be used for this. But fortunately it is pretty easy.

Let's open a CMD console or a PowerShell window and change the directory to the folder of your project. shot::[2, "open cmd and cd to project folder"]

Now use the `dotnet test` command. shot::[3, "type 'dotnet test' and run"]

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet test
----

The *dotnet test* command is part of the cross-platform .NET framework, so you can do the same on Linux or on macOS as well. And also inside a Docker container of course.

[source]
----
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     5, Skipped:     0, Total:     5, Duration: 99 ms - Shouty.Specs.dll (netcoreapp3.1)
----

The output is not very verbose but it clearly shows that all of our test were passing, so our changes did not cause any unwanted side-effects. Good to know.

We wanted to perform a full regression test by running the tests from the command line, therefore we did not apply any filters. But sometimes we need to. Maybe we just want to run the smoke tests.

The *dotnet test* command provides a `--filter` option where you can specify a filter expression. In the previous lesson we discussed that SpecFlow converts tags to test categories or traits. In Visual Studio we used a trait expression, but unfortunately the same expression won't work here. The exact expression syntax that has to be used depends on the test execution framework you use. Since we're use xUnit, we have to filter using the `Category=smoke` expression. shot::[4, "type dotnet test --filter Category=smoke"] In MsTest and NUnit we would have to say `TestCategory` instead of `Category`, shot::[5, "change to dotnet test --filter TestCategory=smoke"] but the expression is otherwise the same. Let's fix this for xUnit and run the tests. shot::[6, "change back to dotnet test --filter Category=smoke, run"]

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet test --filter Category=smoke
----

[source]
----
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 77 ms - Shouty.Specs.dll (netcoreapp3.1)
----

As you can see, only two tests ran, so the filtering worked.

You can also use the filter expression to exclude tagged scenarios from the execution. For that you have to use the not equal operator. Let's exclude the slow tests now. shot::[7.1, "type --filter Category!=slow"]

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet test --filter Category!=slow
----

Again, with MsTest or NUnit you would need to use TestCategory here. shot::[7.2, "run"] You can compose even more complex filter expressions for dotnet test. It is worth checking out the https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=xunit[documentation] for details. 

[source]
----
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     3, Skipped:     0, Total:     3, Duration: 99 ms - Shouty.Specs.dll (netcoreapp3.1)
----

Teams often use such filters on the Continuous Integration Server if they write - or we can say formulate - the scenarios some time before the actual implementation work starts. Having these scenarios in source control would cause the build fail although there is nothing wrong with the implementation. We just have tests that are not supposed to pass yet. If the team agree to tag these scenarios, for example with `@formulated` than they can easily exclude them on the build server with this expression. shot::[8, "type dotnet test --filter TestCategory!=formulated and run"].

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet test --filter Category!=formulated
----

[source]
----
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     5, Skipped:     0, Total:     5, Duration: 99 ms - Shouty.Specs.dll (netcoreapp3.1)
----

Seeing all these scenarios pass means that we are progressing well. Just don't forget to remove the @formulated tag once you are done!

In this lesson you've learnt how to run scenarios from the command line and how to filter the set of scenarios to run using tags. On the Continuous Integration Server we probably also want to preserve and publish the test results. We'll cover that in lesson 4.
