include::./title.adoc[]

shot::[1]
In the previous lesson, we modified Cucumber's behavior using scenario names and line numbers. In this lesson I'm going to show you how to filter scenarios using tags.

First, let's delete the contents of the  `cucumber.yml` file. shot::[2]. We'll leave `default --quiet` for now. We'll explain what's it about in a later lesson.

If we run Cucumber, it will run all scenarios. shot::[3, run Cucumber]


We’ll put a focus tag right here, above this scenario. shot::[4, "add a @focus tag to the 'Listener is out of range' scenario"] Tags start with an at-sign and are case sensitive.

Now, after re-creating the `cucumber.yml`file, let's add a tag expression to the default key, which Cucumber will use to filter the scenarios run shot::[5]

[source,yaml]
----
default: --quiet --tags @focus
----

Now Cucumber will run only the scenarios tagged with focus - there should be only one... shot::[6, "run Cucumber, then highlight that only 'Listener is out of range' scenario was run"]shot::[7]

Yep.

It’s entirely up to you what you name your tags. When we’re working on a particular area of the application it is common to use a temporary tag like this - we’ll remove it before we check our code into source control.

Tags can be used for other purposes as well. If you have lots of scenarios it can be time-consuming to run them all every time. For example, you can tag a few of them with @smoke and run only those before you check in code to source control. shot::[8, tag first and third scenario with @smoke]shot::[9]

[source, yaml]
----
default: --quiet --tags @smoke
----

Running just the smoke tests will give you a certain level of confidence that nothing is broken without having to run them all. shot::[10, "run Cucumber, then highlight that only first and third scenarios were run"]shot::[11]

If you’re running Cucumber on a Continuous Integration Server as well, you could run all the scenarios there, detecting any regressions you might have missed by only running the smoke tests.

Tags give you a way to organise your scenarios that cut across feature files. You can think of them like sticky labels you might put into a book to mark interesting pages that you want to refer back to.

Some teams also use tags to reference external documents, for example, tickets in an issue tracker or planning tool. Let’s pretend we are using an issue tracker while working on Shouty and all the behaviour we built so far is related to the issue number 11. We could tag the whole feature file with this single line at the top. shot::[12, tag feature with @SHOUTY-11] All the scenarios within that file now inherit that tag, so if we change the tag expression in cucumber.yml shot::[13, edit YML file],

[source, yaml]
----
default: --quiet --tags @SHOUTY-11
----

Cucumber will run all the scenarios in the feature file. shot::[14, "run Cucumber, then show that all scenarios were run"]shot::[15]

You can use more complex tag expressions to select the scenarios you want to run. For example, you could use a tag expression to exclude all the scenarios tagged as @slow. shot::[16, "tag last two scenarios with @slow""] Then rewrite the tag expression in cucumber.yml using the `not` keyword shot::[17, "modify Cucumber.yml] Now when you run Cucumber, the "@slow" scenarios won't be run. shot::[18, "run Cucumber, then show that the slow scenarios were not run"]


[source, js]
----
default: --quiet --tags "not @slow"
----

Note the need to add quotes around `"not @slow"`.shot::[19] If they're not added, running `bundle exec cucumber` will result in an error.

You can read about how to build more complicated tag expressions on the https://cucumber.io/docs/cucumber/api/#tag-expressions[Cucumber website] shot::[20, "open the link and show the Cucumber website"]

There's one more thing to learn about tags. They can be combined with hooks, so that you can be selective about which hooks to run when. We'll cover that in a future chapter.

