include::./title.adoc[]

shot::[1]
In the previous lesson, we modified Cucumber's behavior using scenario names and line numbers. In this lesson I'm going to show you how to filter scenarios using tags.

First, let's delete the `--name` parameter from `cucumber.js`. shot::[2]

.cucumber.js
[source,js]
----
include::../code/js/03-remove-name-filter-from-default-export/cucumber.js[]
----


Now, Cucumber will run all scenarios. shot::[3, run Cucumber from IntelliJ]

shot::[4, "show 'Listener is out of range' scenario"]
We’ll put a focus tag right here, above this scenario. shot::[5, "add a @focus tag to the 'Listener is out of range' scenario"]

.hear-shout.feature
[source,gherkin]
----
include::../code/js/04-add-focus-tag/features/hear_shout.feature[lines=23..30]
----

Tags start with an at-sign and are case sensitive.

Now let's add a tag expression to the default key,shot::[6] which Cucumber will use to filter the scenarios run

.cucumber.js
[source,yaml]
----
include::../code/js/04-add-focus-tag/cucumber.js[]
----

Now we can run only the scenarios tagged with focus - there should be only one... shot::[7, "npm test, then highlight that only 'Listener is out of range' scenario was run"]shot::[8]

Yep.

Remember, tags are case sensitive, so if we change the tag in the feature file to be @Focus shot::[9] and then run Cucumber shot::[10, npm test & show output]shot::[11] you can see that Cucumber found no scenarios that matched the tag expression.

.hear-shout.feature
[source,gherkin]
----
include::../code/js/05-change-to-focus/features/hear_shout.feature[lines=23..30]
----

It’s entirely up to you what you name your tags. When we’re working on a particular area of the application it is common to use a temporary tag like this - we’ll remove it before we check our code into source control.

Tags can be used for other purposes as well. If you have lots of scenarios it can be time-consuming to run them all every time. For example, you can tag a few of them with @smoke and run only those before you check in code to source control. shot::[12, tag first, second and third scenario with @smoke]

.hear-shout.feature
[source,gherkin]
----
include::../code/js/06-add-smoke-tag/features/hear_shout.feature[lines=5..30]
----

And we change the tag in the configuration file. shot::[13]

.cucumber.js
[source,yaml]
----
include::../code/js/06-add-smoke-tag/cucumber.js[]
----

Running just the smoke tests will give you a certain level of confidence that nothing is broken without having to run them all. shot::[14, "run Cucumber, then highlight that three scenarios were run"]shot::[15]


If you’re running Cucumber on a Continuous Integration Server as well, you could run all the scenarios there, detecting any regressions you might have missed by only running the smoke tests locally.

Tags give you a way to organise your scenarios that cut across feature files. You can think of them like sticky labels you might put into a book to mark interesting pages that you want to refer back to.

Some teams also use tags to reference external documents, for example, tickets in an issue tracker or planning tool. Let’s pretend we are using an issue tracker while working on Shouty and all the behaviour we built so far is related to the issue number 11. We could tag the whole feature file with this single line at the top. shot::[16, tag feature with @SHOUTY-11]

.hear-shout.feature
[source,gherkin]
----
include::../code/js/07-add-feature-level-tag/features/hear_shout.feature[lines=1..5]
----

All the scenarios within that file now inherit that tag, so if we change the tag expression in cucumber.js,shot::[17]

.cucumber.js
[source,js]
----
include::../code/js/07-add-feature-level-tag/cucumber.js[lines=1]
----


Cucumber will run all the scenarios in the feature file. shot::[18, "run Cucumber, then show that all scenarios were run"]


You can use more complex tag expressions to select the scenarios you want to run. For example, you could use a tag expression to exclude all the scenarios tagged as @slow. shot::[19, "tag last two scenarios with @slow""]

.hear-shout.feature
[source,gherkin]
----
include::../code/js/08-boolean-logic-with-tags/features/hear_shout.feature[lines=35..]
----

Then rewrite the tag expression in cucumber.js using the `not` keyword shot::[20, "modify Cucumber.JS]

.cucumber.js
[source,js]
----
include::../code/js/08-boolean-logic-with-tags/cucumber.js[]
----

Now when you run Cucumber, the "@slow" scenarios won't be run. shot::[21, "run Cucumber, then show that the slow scenarios were not run"]

Let's tidy up be removing the tag filter from cucumber.js. shot::[22]

.cucumber.js
[source,js]
----
include::../code/js/09-remove-boolean-tag-logic/cucumber.js[]
----


You can read about how to build more complicated tag expressions on the https://cucumber.io/docs/cucumber/api/#tag-expressions[Cucumber website] shot::[23, "open the link and show the Cucumber website"]

There's one more thing to learn about tags. They can be combined with hooks, so that you can be selective about which hooks to run when. We'll cover that in a future chapter.

