==== Lesson 1 - Questions (Ruby, Java, JS)

===== Which of the following statements are true?

* Step definitions translate human-readable scenarios into concrete actions in code - TRUE
* BDD practitioners think of "step definitions" and "automation code" as distinct concepts - TRUE
* Cucumber only supports automation through the user interface - FALSE

Answer: A step definition is a piece of code that is called by Cucumber in response to a step in a scenario. You can write any code you like inside a step definition, but we've found it easier to maintain if we keep them short. This leads to step definitions calling dedicated automation code to perform concrete actions against the system under construction. That automation code can manipulate the user interface, make a REST call, or drive the domain model directly.

===== Which of the following statements are true?

* Regular Expressions are exactly the same as Cucumber Expressions - FALSE
* Modern versions of Cucumber only support both Cucumber Expressions and Rregular Expressions - TRUE
* Cucumber Expressions are more intimidating than Regular Expressions - FALSE

Answer: Regular Expressions are a powerful tool that have been in use in computer science for many decades. They can be hard understand and maintain, so the Cucumber team created a simplified mechanism, called Cucumber Expressions. However, Cucumber remains backwards compatible, so you can use both Regular Expressions and Cucumber Expressions with modern releases of Cucumber.


==== Lesson 1 - Questions (SpecFlow/C#/Dotnet)

===== Which of the following statements are true?

* Step definitions translate human-readable scenarios into concrete actions in code - TRUE
* BDD practitioners think of "step definitions" and "automation code" as distinct concepts - TRUE
* SpecFlow only supports automation through the user interface - FALSE

Answer: A step definition is a piece of code that is called by SpecFlow in response to a step in a scenario. You can write any code you like inside a step definition, but we've found it easier to maintain if we keep them short. This leads to step definitions calling dedicated automation code to perform concrete actions against the system under construction. That automation code can manipulate the user interface, make a REST call, or drive the domain model directly.

===== Which of the following statements are true?

* Regular Expressions are exactly the same as Cucumber Expressions - FALSE
* In modern versions of SpecFlow steps can be defined using Cucumber Expressions but this feature has to be enabled first - TRUE
* Cucumber Expressions are more intimidating than Regular Expressions - FALSE
* Regular expressions can still be used even in modern versions of SpecFlow even if Cucumber Expressions are enabled - TRUE

Answer: Regular Expressions are a powerful tool that have been in use in computer science for many decades. They can be hard understand and maintain, so the Cucumber team created a simplified mechanism, called Cucumber Expressions that is now also available for SpecFlow. SpecFlow remains backwards compatible, so you can use both Regular Expressions and Cucumber Expressions with modern releases of SpecFlow.
