==== Lesson 1 - Questions (Ruby, Java, JS)

===== Which aspects of Cucumber help bridge the communication gap between business domain experts and development teams?

* The readability of Gherkin scenarios - TRUE
* Cucumber's availability for different programming languages - FALSE
* Being able to express scenarios using your own domain language - TRUE

Answer: The feature files that Cucumber understands are written using Gherkin, so that you can create scenarios that utilise your own domain language, so that they can be read and understood by everyone involved in specifying and delivering your software.

===== How do Cucumber feature files differ from more traditional automated tests?

* The purpose of feature files is to create readable specifications that can be understood by the whole team, not to provide test coverage
* Business-readable specifications make it easier to obtain feedback about what you're building while you're building it, rather than waiting for a later test cycle
* Feature files become "living documentation" when they are automated, providing a single source of truth for the whole team
* Feature files should be written collaboratively by business and delivery, not in isolation by testers
* There is no difference - FALSE

Answer: BDD is the collaborative approach to developing software that Cucumber was created to support. Although Cucumber scenarios do act as tests when they are automated, this is not their primary purpose. Their primary purpose is to provide a single, shared specification, written in the domain language of your business -- facilitating collaboration, feedback, and
reliable documentation. The primary purpose of traditional automated tests, on the other hand, is to check that the software behaves as expected.

==== Lesson 1 - Questions (SpecFlow/C#/Dotnet)

===== Which aspects of SpecFlow help bridge the communication gap between business domain experts and development teams?

* The readability of Gherkin scenarios - TRUE
* Gherkin scenarios can be automated in different programming languages - FALSE
* Being able to express scenarios using your own domain language - TRUE

Answer: The feature files that SpecFlow understands are written using Gherkin, so that you can create scenarios that utilise your own domain language, so that they can be read and understood by everyone involved in specifying and delivering your software.

===== How do SpecFlow feature files differ from more traditional automated tests?

* The purpose of feature files is to create readable specifications that can be understood by the whole team, not to provide test coverage
* Business-readable specifications make it easier to obtain feedback about what you're building while you're building it, rather than waiting for a later test cycle
* Feature files become "living documentation" when they are automated, providing a single source of truth for the whole team
* Feature files should be written collaboratively by business and delivery, not in isolation by testers
* There is no difference - FALSE

Answer: BDD is the collaborative approach to developing software that SpecFlow was created to support. Although SpecFlow scenarios do act as tests when they are automated, this is not their primary purpose. Their primary purpose is to provide a single, shared specification, written in the domain language of your business -- facilitating collaboration, feedback, and
reliable documentation. The primary purpose of traditional automated tests, on the other hand, is to check that the software behaves as expected.
