=== The importance of readability

video::https://drive.google.com/uc?id=1arEP_-0Fi5CK7EC8IYCJWrc67I_XF34Z[]

shot::[0.1, "04.01.animation.mp4"]

In the previous chapter, we talked about the importance of having readable scenarios, and you learned some new skills with Cucumber Expressions to help you achieve that goal. Those skills will give you the confidence to write scenarios exactly the way you want, knowing you’ll be able to match the Gherkin steps easily from your step definition code.

We emphasise readability because from our experience, writing Gherkin scenarios is a software design activity. Cucumber was created to bridge the communication gap between business domain experts and development teams. When you collaborate with domain experts to describe behaviour in Gherkin, you’re expressing the group’s shared understanding of the problem you need to solve. The words you use in your scenarios can have a deep impact on the way the software is designed, as we’ll see in later chapters.

The more fluent you become in writing Gherkin, the more useful a tool it becomes to help you facilitate this communication. Keeping your scenarios readable means you can get feedback at any time about whether you’re building the right thing. Over time, your features become living documentation about your system. We can’t emphasize enough how important it is to see your scenarios as more than just tests.

Maintaining a living document works both ways: the scenarios will guide your solution design, but you may also have to update your Gherkin to reflect the things you learn as you build the solution. This dance back and forth between features and solution code is an important part of BDD.

In this chapter, we’ll learn about feature descriptions, the Background keyword, and about keeping scenarios and code up-to-date with your current understanding of the project.

First, let’s catch up with what’s been happening on the Shouty project.

==== Continuity Annoucement

Before we start, I need to explain about a continuity error between the previous chapter and this next one.

In the last chapter we showed you how to use _parameter types_ to automatically create an instance of our `Person` class whenever we used it in a step defintion.

Now the first version of video series was first created many years ago, before we had added parameter types to Cucumber. Although we updated the previous chapter to demonstrate parameter types to you, we haven't yet updated this one. So you'll notice as you follow along here that there's no mention of parameter types anymore.

Some of the things we'll be doing to clean up the code in this chapter would be even cleaner if we used parameter types, and we hope to update this video someday to incorporate them into the story. In the meantime we'll leave it as an exercise for you to think about how you would change the work we do in this episode to make the most of them.

Have fun, and don't forget to come on https://cucumberbdd.slack.com/archives/C9C3FSGRE[the #school community Slack channel] to ask if you need any guidance!
