include::./title.adoc[]

Before we get started make sure you have a modern version of Ruby installed,
and the Bundler gem. Open a command-prompt and check the Ruby version, shot::[1] and the version of Bundler, Ruby's package manager: shot::[2]

[source,bash]
----
$ ruby -v
$ bundle -v
----
If you see an error message when you run these commands, you’ll need to fix your Ruby installation.

shot::[3]
Go back to the command prompt and create a new directory for our project:

[source,bash]
----
$ mkdir shouty
----

Use `cd` to go into that directory. shot::[4] If you want to, you can open the directory up in your favourite text editor at this point.

[source,bash]
----
$ cd shouty
----

shot::[5] shot::[6]
First we’ll create a Gemfile that describes the Ruby gems we need for our project.
shot::[7] We’ll add Cucumber and shot::[8] RSpec-Expectations.

.Gemfile
[source,ruby]
----
source "https://rubygems.org"

gem 'cucumber'
gem 'rspec'
----

Now go back to the command-line shot::[9] and run `bundle install` to install those gems.

[source,bash]
----
$ bundle install
----

Now we’re ready! If we run `cucumber` at this point shot::[10], we’ll see it’s telling us to create a features directory.

[source,bash]
----
$ bundle exec cucumber
No such file or directory - features. You can use `cucumber --init` to get started.
----

Good, we've installed Cucumber.

shot::[11]
As instructed, we can use the `cucumber --init` command to create the conventional folder structure for our Gherkin specifications and the code that will let Cucumber test them:

[source,bash]
----
$ cucumber --init
  create   features
  create   features/step_definitions
  create   features/support
  create   features/support/env.rb
----

Now we’re ready to create our first feature file.


shot::[12]
[source,bash]
----
$ bundle exec cucumber
0 scenarios
0 steps
0m0.000s
----
