=== Creating our first feature

As instructed, we can use the `cucumber --init` command to create the conventional folder structure for our Gherkin specifications and the code that will let Cucumber test them:

[source,bash]
----
$ cucumber --init
  create   features
  create   features/step_definitions
  create   features/support
  create   features/support/env.rb
----

Now we’re ready to create our first feature file. Call the file `hear_shout.feature`

[source,bash]
----
$ touch features/hear_shout.feature
----

shot::[]
All feature files start with the keyword `Feature:`
shot::[]
followed by a name.
It’s a good convention to give it a name that matches the file name.

shot::[]
Let’s write out our first scenario.

.hear_shout.feature
[source,gherkin]
----
Feature: Hear shout
  Scenario: Listener is within range
    Given Lucy is located 15m from Sean
    When Sean shouts “free bagels at Sean’s”
    Then Lucy hears Sean’s message
----

==== Run Feature

shot::[]
Switch back to the command-prompt and run `cucumber`. You’ll see Cucumber has found our feature file and read it back to us. We can see a summary of the results at the bottom: one scenario, three steps - all undefined.

[source,bash]
----
$ bundle exec cucumber
Feature: Hear shout

  Scenario: Listener is within range         # features/listening.feature:2
    Given Lucy is located 15m from Sean      # features/listening.feature:3
    When Sean shouts “free bagels at Sean’s” # features/listening.feature:4
    Then Lucy hears Sean’s message           # features/listening.feature:5

1 scenario (1 undefined)
3 steps (3 undefined)
0m0.005s

You can implement step definitions for undefined steps with these snippets:

Given("Lucy is located {int}m from Sean") do |int|
  pending # Write code here that turns the phrase above into concrete actions
end

When("Sean shouts “free bagels at Sean’s”") do
  pending # Write code here that turns the phrase above into concrete actions
end

Then("Lucy hears Sean’s message") do
  pending # Write code here that turns the phrase above into concrete actions
end
----

shot::[]
`Undefined` means Cucumber doesn’t know what to do for any of the three steps we wrote in our Gherkin scenario. It needs us to provide some _step definitions_.

shot::[]
Step definitions translate from the plain language you use in Gherkin into Ruby code.

shot::[]
When Cucumber runs a step, it looks for a step definition that matches the text in the step. If it finds one, then it executes the code in the step definition.

If it doesn’t find one… well, you’ve just seen what happens. Cucumber helpfully prints out some code snippets that we can use as a basis for new step definitions.
shot::[]
Let’s copy those.

shot::[]
We’ll paste them into a Ruby file under a new directory called `step_definitions` underneath the `features` directory. We'll just call it `steps.rb`.

.steps.rb
[source,ruby]
----
Given("Lucy is located {int}m from Sean") do |int|
  pending # Write code here that turns the phrase above into concrete actions
end

When("Sean shouts “free bagels at Sean’s”") do
  pending # Write code here that turns the phrase above into concrete actions
end

Then("Lucy hears Sean’s message") do
  pending # Write code here that turns the phrase above into concrete actions
end
----

shot::[]
Now run Cucumber again.

shot::[]
This time the output is a little different. We now have a pending step and two skipped ones. This means Cucumber found all our step definitions, and executed the first one.
shot::[]
But that first step definition throws a `PendingException`, which causes Cucumber to stop, skip the rest of the steps, and mark the scenario as pending. 

[source,bash]
----
$ bundle exec cucumber
Feature: Hear shout

  Scenario: Listener is within range         # features/listening.feature:2
    Given Lucy is located 15m from Sean      # features/step_definitions/steps.rb:2
      TODO (Cucumber::Pending)
      ./features/step_definitions/steps.rb:3:in `"Lucy is located {int}m from Sean"'
      features/listening.feature:3:in `Given Lucy is located 15m from Sean'
    When Sean shouts “free bagels at Sean’s” # features/step_definitions/steps.rb:6
    Then Lucy hears Sean’s message           # features/step_definitions/steps.rb:10

1 scenario (1 pending)
3 steps (2 skipped, 1 pending)
0m0.008s
----

It’s time to start work on our solution. At this point we need to do a little domain modelling. The words in the step provide us some good hints about some names that will appear in our domain model. Our scenario mentions two people, Lucy and Sean. So it looks like we need a couple of person objects at least. Each person will also need to know their own location.

Cucumber is telling us to write the code we wish we had. Let’s do it!

shot::[]
We’ll start by renaming the `int` parameter to something that better reflects its meaning. We’ll call it `distance`.

shot::[]
And we can print it to the terminal to see the captured result.

To keep things simple we’re going to assume all people are situated on a line - in a one-dimensional coordinate system. We can always introduce proper geo locations later. We’ll place Sean in the centre and Lucy 15 metres away from Sean.

[source,ruby]
----
Given("Lucy is located {int}m from Sean") do |distance|
  p distance
  pending # Write code here that turns the phrase above into concrete actions
end

When("Sean shouts “free bagels at Sean’s”") do
  pending # Write code here that turns the phrase above into concrete actions
end

Then("Lucy hears Sean’s message") do
  pending # Write code here that turns the phrase above into concrete actions
end
----

shot::[]
If we run `cucumber` again on our terminal, we can see the number 15 pop up in the output

[source,bash]
----
$ bundle exec cucumber 
Feature: Hear shout

15
  Scenario: Listener is within range         # features/hear_shout.feature:2
    Given Lucy is located 15m from Sean      # features/step_definitions/steps.rb:2
      TODO (Cucumber::Pending)
      ./features/step_definitions/steps.rb:4:in `"Lucy is located {int}m from Sean"'
      features/hear_shout.feature:3:in `Given Lucy is located 15m from Sean'
    When Sean shouts “free bagels at Sean’s” # features/step_definitions/steps.rb:7
    Then Lucy hears Sean’s message           # features/step_definitions/steps.rb:11

1 scenario (1 pending)
3 steps (2 skipped, 1 pending)
0m0.005s
----

Notice that the number 15 does not appear anywhere in our Ruby code. The value 15 is automatically passed from the Gherkin step to the step definition. If you are curious, that’s the `{int}` in the step definition pattern or _cucumber expression_. We’ll explain these patterns in detail in a future lesson.
