include::./title.adoc[]

shot::[1]
We need to create a `features` directory. This is the conventional place to store your Gherkin specifications.

[source,bash]
----
$ mkdir features
----

shot::[2]
Now we’re ready to create our first feature file. Call the file `hear_shout.feature`

[source,bash]
----
$ touch features/hear_shout.feature
----

All feature files start with the keyword `Feature:` shot::[3] followed by a name. shot::[4]
It’s a good convention to give it a name that matches the file name.

Now let’s write out our first scenario.

This is the one where the listener is within range, shot::[5] Lucy is located 15 metres from Sean, shot::[6] Sean shouts "free bagels at Sean's", shot::[7] Lucy hears Sean's message. shot::[8]

.hear_shout.feature
[source,gherkin]
----
include::../code/js/02-feature-file-created/features/hear_shout.feature[]
----

Save the file, switch back to the command-prompt and run `npm test`. shot::[9]

shot::[10]
The first thing we notice is a big green box right at the end of the output.

[source,sh]
----
┌──────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io │
│                                                                          │
│ Command line option:    --publish                                        │
│ Environment variable:   CUCUMBER_PUBLISH_ENABLED=true                    │
│                                                                          │
│ More information at https://reports.cucumber.io/docs/cucumber-js         │
│                                                                          │
│ To disable this message, add this to your ./cucumber.js:                 │
│ module.exports = { default: '--publish-quiet' }                          │
└──────────────────────────────────────────────────────────────────────────┘
----

We don't want this warning to distract us right now, so we'll follow the instructions mentioned at the end of the warning and add the "publish-quiet" option...

[source,js]
----
module.exports = { default: '--publish-quiet' }
----

...to the `cucumber.js` file.shot::[11]shot::[12]

Now when we run cucumber again, the warning isn't there anymore. shot::[13]

You’ll see Cucumber has found our feature file and read it back to us. We can see a summary of the results at the bottom: one scenario,shot::[14] three steps - all undefined.shot::[15]

[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty-js/shouty
> cucumber-js

UUU

Failures:

1) Scenario: Listener is within range # features/hear_shout.feature:2
   ? Given Lucy is located 15 metres from Sean
       Undefined. Implement with the following snippet:

         Given('Lucy is located {int} metres from Sean', function (int) {
         // Given('Lucy is located {float} metres from Sean', function (float) {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });
       
   ? When Sean shouts "free bagels at Sean's"
       Undefined. Implement with the following snippet:

         When('Sean shouts {string}', function (string) {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });
       
   ? Then Lucy hears Sean's message
       Undefined. Implement with the following snippet:

         Then('Lucy hears Sean\'s message', function () {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });
       

1 scenario (1 undefined)
3 steps (3 undefined)
0m00.006s (executing steps: 0m00.000s)
npm ERR! Test failed.  See above for more details.
----

_Undefined_` means Cucumber doesn’t know what to do for any of the three steps we wrote in our Gherkin scenario. It needs us to provide some _step definitions_.

shot::[16, "02.04.animation.mp4"]

Step definitions translate from the plain language you use in Gherkin into JavaScript code.

When Cucumber runs a step, it looks for a step definition that matches the text in the step. If it finds one, then it executes the code in the step definition.

If it doesn’t find one… well, you’ve just seen what happens. Cucumber helpfully prints out some code snippets that we can use as a basis for new step definitions.

Let’s copy those to create our first step definitions. shot::[17]

shot::[18]shot::[19]shot::[20]
We’ll paste them into a JavaScript file under a new directory called `step_definitions` underneath the `features` directory. I’ll just call it `steps.js`.

We need to import the `Given`, shot::[21] `When` shot::[22] and `Then` shot::[23] keywords from the `cucumber` package.shot::[24]

.steps.js
[source,js]
----
include::../code/js/04-pending-steps/features/step_definitions/steps.js[]
----

shot::[25]
Now we run Cucumber again.

This time the output is a little different. We now have a pending step shot::[26] and two skipped ones.shot::[27] This means Cucumber found all our step definitions, and executed the first one.

shot::[28]
But that first step definition returns `'pending'`, which causes Cucumber to stop, skip the rest of the steps, and mark the scenario as pending. 

[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty-js/shouty
> cucumber-js

P--

Warnings:

1) Scenario: Listener is within range # features/hear_shout.feature:2
   ? Given Lucy is located 15 metres from Sean # features/step_definitions/steps.js:3
       Pending
   - When Sean shouts "free bagels at Sean's" # features/step_definitions/steps.js:8
   - Then Lucy hears Sean's message # features/step_definitions/steps.js:13

1 scenario (1 pending)
3 steps (1 pending, 2 skipped)
0m00.007s (executing steps: 0m00.001s)
npm ERR! Test failed.  See above for more details.
----

Now that we've wired up our step definitions to the Gherkin steps, it's almost time to start working on our solution. First though, let's tidy up the generated code.

We'll rename the `int` parameter to something that better reflects its meaning. Let's call it `distance`.shot::[29]

shot::[30]
And we can print it to the terminal to see the captured result

[source,js]
----
include::../code/js/05-output-stepdef-argument-to-console/features/step_definitions/steps.js[lines=3..6]
----

shot::[31]
If we run `cucumber` again on our terminal, we can see the number 15 pop up in the output.

[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty-js/shouty
> cucumber-js

15
P--

Warnings:

1) Scenario: Listener is within range # features/hear_shout.feature:2
   ? Given Lucy is located 15 metres from Sean # features/step_definitions/steps.js:3
       Pending
   - When Sean shouts "free bagels at Sean's" # features/step_definitions/steps.js:8
   - Then Lucy hears Sean's message # features/step_definitions/steps.js:13

1 scenario (1 pending)
3 steps (1 pending, 2 skipped)
0m00.009s (executing steps: 0m00.002s)
npm ERR! Test failed.  See above for more details.
----

Notice that the number 15 does not appear anywhere in our code. The value is automatically passed from the Gherkin step to the step definition. If you're curious, that’s the shot::[32]`{int}` in the step definition pattern or _cucumber expression_. We’ll explain these patterns in detail in a future lesson.
