include::./title.adoc[]

So we have our failing scenario: shot::[1]

[source,bash]
----
bundle exec cucumber
Feature: Hear shout

  Scenario: Listener is within range         # features/hear_shout.feature:2
    Given Lucy is located 15m from Sean      # features/step_definitions/steps.rb:4
    When Sean shouts "free bagels at Sean's" # features/step_definitions/steps.rb:10
    Then Lucy hears Sean’s message           # features/step_definitions/steps.rb:15
      expected [] to include "free bagels at Sean's" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/steps.rb:16:in `"Lucy hears Sean’s message"'
      features/hear_shout.feature:5:in `Then Lucy hears Sean’s message'

Failing Scenarios:
cucumber features/hear_shout.feature:2 # Scenario: Listener is within range

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
0m0.032s
----

Lucy is expected to hear Sean's message, but she hasn't heard anything: we got an empty Array back from the `messages_heard` method.shot::[2]

shot::[3]
In this case, we’re going to cheat. We have a one-line fix that will make this scenario pass, but it’s not a particularly future-proof implementation. Can you guess what it is?shot::[4]

[source,ruby]
----
module Shouty
  class Person
    def move_to(distance)
      
    end

    def shout(message)
      
    end

    def messages_heard
      ["free bagels at Sean's"]
    end
  end
end
----

I told you it wasn’t very future proof!

shot::[5]
[source,bash]
----
$ bundle e xec cucumber
Feature: Hear shout

  Scenario: Listener is within range         # features/hear_shout.feature:2
    Given Lucy is located 15m from Sean      # features/step_definitions/steps.rb:4
    When Sean shouts "free bagels at Sean's" # features/step_definitions/steps.rb:10
    Then Lucy hears Sean’s message           # features/step_definitions/steps.rb:15

1 scenario (1 passed)
3 steps (3 passed)
0m0.028s
----

Woohoo! Our scenario is passing for the first time. As long as this is the only message anyone ever shouts, we're good to ship this thing!

Now, the fact that such a poor implementation can pass our tests shows us that we need to work on our tests. A more comprehensive set of scenarios would guide us towards a better implementation.

It's also a good habit to look for the most simple solution. We can trust that, as our scenarios evolve, so will our solution.

This is the essence of Behaviour-Driven Development. Examples of behaviour drive the development. We do just enough to make the next scenario pass, and no more.

Instead of writing a note on our TODO list, let's write another scenario that shouts a different message. shot::[6]

[source,gherkin]
----
Feature: Hear shout
  Scenario: Listener is within range
    Given Lucy is located 15m from Sean
    When Sean shouts "free bagels at Sean's"
    Then Lucy hears Sean’s message

  Scenario: Listener hears a different message
    Given Lucy is located 15m from Sean
    When Sean shouts "Free coffee!"
    Then Lucy hears Sean's message
----

It fails, reminding us we need to find a solution that doesn't rely on hard-coding the message. shot::[7]
Now when we come back to this code, we can just run the tests and Cucumber will remind us what we need to do next. We're done for today!

[source,bash]
----
$ bundle exec cucumber
Feature: Hear shout

  Scenario: Listener is within range         # features/hear_shout.feature:2
    Given Lucy is located 15m from Sean      # features/step_definitions/steps.rb:3
    When Sean shouts "free bagels at Sean's" # features/step_definitions/steps.rb:9
    Then Lucy hears Sean's message           # features/step_definitions/steps.rb:14

  Scenario: Listener hears a different message # features/hear_shout.feature:7
    Given Lucy is located 15m from Sean        # features/step_definitions/steps.rb:3
    When Sean shouts "Free coffee!"            # features/step_definitions/steps.rb:9
    Then Lucy hears Sean's message             # features/step_definitions/steps.rb:14
      expected ["free bagels at Sean's"] to include "Free coffee!" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/steps.rb:15:in `"Lucy hears Sean's message"'
      features/hear_shout.feature:10:in `Then Lucy hears Sean's message'

Failing Scenarios:
cucumber features/hear_shout.feature:7 # Scenario: Listener hears a different message

2 scenarios (1 failed, 1 passed)
6 steps (1 failed, 5 passed)
0m0.039s
----

Of course, if you're in the mood, you can always try to implement a solution yourself that makes both scenarios pass. Have fun!
