==== Lesson 4 - Questions

===== What do step definitions do? (choose one) ::

* Provide a glossary of domain terms for your stakeholders
* Give Cucumber/SpecFlow a way to automate your gherkin steps - TRUE
* Add extra meaning to our Gherkin steps
* Generate code from gherkin documents

Explanation:
<java>
Step definitions are Java methods that actually do what's described in each step of a Gherkin scenario.

When it tries to run each step of a scenario, Cucumber will search for a step definition that matches. If there's a matching step definition, it will call the method to run it.
</java>

<js>
Step definitions are JavaScript functions that actually do what's described in each step of a Gherkin scenario.

When it tries to run each step of a scenario, Cucumber will search for a step definition that matches. If there's a matching step definition, it will call the function.
</js>

<ruby>
Step definitions are Ruby blocks that actually do what's described in each step of a Gherkin scenario.

When it tries to run each step of a scenario, Cucumber will search for a step definition that matches. If there's a matching step definition, it will execute the code in the block.
</ruby>

<C#>
Step definitions are C# methods that actually do what's described in each step of a Gherkin scenario.

When it tries to run each step of a scenario, SpecFlow will search for a step definition that matches. If there's a matching step definition, it will call the method to run it.
</C#>

===== What does it mean when Cucumber/SpecFlow says a step is Pending? (choose one) ::

* The step took too long to execute and was terminated
<java> * The step threw a `PendingException`, meaning we're still working on implementing that step.</java>
<js> * The step returned pending, meaning we're still working on implementing that step.</js>
<ruby> * The step definition threw a Pending error, meaning we're still working on implementing that step.</ruby>
<C#> ASK GASPAR </C#>
* Cucumber/SpecFlow was unable to find the step definitions
* The scenario is passing
* The scenario is failing

Explanation:

<java>
Cucumber tells us that a step (and by inference the Scenario that contains it) is Pending when the automation code throws a PendingException.

The PendingException is a special type of exception provided by Cucumber to allow the development team to signal that automation for a step is a work in progress. This makes it possible to tell the difference between steps that aren't finished yet and steps that are failing due to a defect in the system.

For example, when we run our tests in a Continuous Integration (CI) environment, we can choose to ignore pending scenarios.
</java>

<js>
Cucumber tells us that a step (and by inference the Scenario that contains it) is Pending when the automation code throws a Pending error.

This allows the development team to signal that automation for a step is a work in progress. This makes it possible to tell the difference between steps that are still being worked on and steps that are failing due to a defect in the system.

For example, when we run our tests in a Continuous Integration (CI) environment, we can choose to ignore pending scenarios.
</js>

<ruby>
Cucumber tells us that a step (and by inference the Scenario that contains it) is Pending when the automation code throws a Pending error.

This allows the development team to signal that automation for a step is a work in progress. This makes it possible to tell the difference between steps that are still being worked on and steps that are failing due to a defect in the system.

For example, when we run our tests in a Continuous Integration (CI) environment, we can choose to ignore pending scenarios.
</ruby>

<C#> ASK GASPAR </C#>


===== Which of the following might you want to consider when using a snippet generated by Cucumber/SpecFlow?

* Does the name of the method correctly describe the intent of the step? - TRUE
* Do the parameter names correctly describe the meaning of the arguments? - TRUE
* Does the snippet correctly automate the gherkin step as described? - FALSE

Explanation:
When Cucumber/SpecFlow generates a snippet, it has no idea of the business context of the undefined step. The implementation that Cucumber/SpecFlow generates will definitely not automate what's been written in your Gherkin - that's up to you! Also, the name of the method and the parameters are just placeholders. It's the job of the person writing the code to rename the method and parameters to reflect the business domain.

===== What’s the next step in BDD after we’ve pasted in the step definition snippet and seen it fail with a `pending` status?

* Check with our project manager about the requirement
* Implement some code that does what the Gherkin step describes - TRUE
* Create a test framework for modelling our application
* Run a manual test to check what the system does

Explanation:
If you read the comment in the generated snippet, Cucumber/SpecFlow is telling you to "turn the phrase above into concrete actions".

You need your step definition to call your application and do whatever the Gherkin step describes. In the case of our first step here, we want to tell the system that there are two people in certain locations.

We can use the act of fleshing out the body of our step definition as an opportunity to do some software design. We can think about what we want the interface to our system to look like, from the point of view of someone who needs to interact with it. Should we interact with it through the User Interface, or make a call to the programmer API directly? How would we like that interface to work?

We can do all of this without writing any implementation yet.

This is known as "outside-in" development. It helps us to ensure that when we do come to implementing our solution, we're implementing it based on real needs.
