include::./title.adoc[]

////
TODO: 
[x] Add new scenario
[x] Show undefined and explain step definitions
[x] Add step definition snippets
[x] Explain pending
[ ] Rename param, print disctance
////


// *** Add new scenario ***

Let's create our first feature file shot::[1] using the "Add / New Item..." command. Call the file `HearShout.feature` 

shot::[2]
All feature files start with the keyword `Feature:`
shot::[3]
followed by a name.
It’s a good convention to give it a name that matches the file name. shot::[4]

.HearShout.feature
[source,gherkin]
----
Feature: Hear shout
----

shot::[5]
Now let’s write out our first scenario.

.HearShout.feature
[source,gherkin]
----
Scenario: Listener is within range
	Given Lucy is located 15m from Sean
	When Sean shouts "free bagels at Sean's"
	Then Lucy hears Sean’s message
----


// *** Show undefined and explain step definitions ***

Build the solution. shot::[6]

As you can see shot::[7] our new scenario has appeared in the "Test Explorer" window. 

If you don't have a "Test Explorer" in your Visual Studio, you can open it shot::[8] using the "Test Explorer" command from the "Build" manu.

Run the tests. shot::[9]

The test execution failed with the error message shot::[10] that says "No matching step definition found for one or more steps". This is because some of our steps are _undefined_. 
shot::[11] Undefined steps are also higlighted in Visual Studio with an orange color.

_Undefined_ means SpecFlow doesn’t know what to do for any of the three steps we wrote in our Gherkin scenario. It needs us to provide some _step definitions_.

// animation start
video::02.04.animation.mp4[]

Step definitions translate from the plain language you use in Gherkin into Ruby code.

When Cucumber runs a step, it looks for a step definition that matches the text in the Gherkin step. If it finds one, then it executes the code in the step definition.
// animation end

If it doesn’t find one… well, you’ve just seen what happens. shot::[12] SpecFlow prints out some code snippets that we can use as a basis for new step definitions, 
but you can get the same snippets from Visual Studio, shot::[13] using the "Define steps..." command in the editor. 


// *** Add step definition snippets ***

The dialog can help us to create a new class in the `Shouty.Specs` project and paste the selected snippets. shot::[13] We'll just call the class `Steps`. shot::[14]

shot::[15] The wizard detected that we had a `StepDefinitions` folder and saved the new class there. SpecFlow would find it anywhere within the same project, but it is better this way.

Now run the tests again.
shot::[16]


// *** Explain pending ***

This time we've got another error message. shot::[17] It says "One or more step definitions are not implemented yet". 

The step definition snippets we have copied into the project shot::[18] have thrown a `PendingStepException` that at the end caused this error.

Now our scenario and our steps are pending, meaning that we have to implement the automation code to have an automated scenario. 
You can think of the `PendingStepException` as a reminder for that.


// *** Rename param, print disctance ***