==== Lesson 2 - Questions

===== What’s an advantage of using  Gherkin to express our examples in BDD? (choose one) ::
* We can get Cucumber to test whether the code does what the scenario describes.
* We can easily automate tests even if we don't know much about programming.
* We can use tools to generate the scenarios.

Explanation:
Gherkin is just one way of expressing examples of how you want your system to behave. The advantage of using this particular format is that you can use Cucumber to test them for you, making them into Living Documentation.

===== Which of these are Gherkin keywords? (choose multiple)::
* Scenario
* Story
* Given
* Only
* If
* When
* Before
* Then
* While
* Check

Explanation:
We’ve introduced four Gherkin keywords so far:
  * `Scenario` tells Cucumber we’re about to describe an example that it can execute.
  * `Given`, `When` and `Then` identify the steps of the scenario.
There are a few other keywords which will be introduced later in the course.

===== The Gherkin keywords Given, When and Then, allow us to express three different components of a scenario. Which of these statements correctly describes how each of these keywords should be used? (Choose multiple)::

* Given describes something that has already happened before the interesting part of the scenario starts. (Correct)
* Then describes an action you want to take.
* When explains what should happen at the end of the scenario.
* Then explains what should happen at the end of the scenario. (Correct)
* When expresses an action that changes the state of the system. (Correct)
* Given describes the context in which the scenario occurs. (Correct)
* Explanation:
* Given is the context for the scenario. We’re putting the system into a specific state, ready for the scenario to unfold.
* When is an action. Something that happens to the system that will cause something else to happen: an outcome.
* Then is the outcome. It’s the behaviour we expect from the system when this action happens in this context.

Explanation:
*Given* is the context for the scenario. We’re putting the system into a specific state, ready for the scenario to unfold.

*When* is an action. Something that happens to the system that will cause something else to happen: an outcome.

*Then* is the outcome. It’s the behaviour we expect from the system when this action happens in this context.

===== Why did our scenario not mention anything about Lucy walking into Sean’s store and making a purchase?

* It's a business goal which does not belong in a Gherkin document.
* As BDD practitioners, we're focussed on the behaviour of the system, so we don't care about the people who use the software.
* Including details about these two people would be distracting from the main point of our scenario.
* Executable scenarios need to stay focussed on the behaviour of the system itself. We can document business goals elsewhere in our Gherkin to provide context. - TRUE

Explanation:
Behaviour-Driven Development practitioners definitely do care about business goals, but when we're writing the Scenario part of our Gherkin, we need to focus on the observable, testable behaviour of the system we're building.

Later in the course we'll show you how you can use other parts of Gherkin documents to add other relevant details, like business goals, to make great executable specifications.
