==== Lesson 5 - Questions (SpecFlow)

===== What role do Regular Expressions play in Cucumber Expressions?

* None
* Cucumber Expressions provide a subset of Regular Expression syntax
* Cucumber Expressions are exactly the same as Regular Expressions
* A Regular Expression is used to restrict the text to be matched when using a custom parameter type (StepArgumentTransformation) - TRUE

Answer: We use a Regular Expression to restrict the text that should be matched when a custom parameter type (StepArgumentTransformation) is used in a Cucumber Expression. You can find more examples of how to use `StepArgumentTransformation` in the https://docs.specflow.org/projects/specflow/en/latest/Bindings/Step-Argument-Conversions.html#step-argument-transformation[SpecFlow documentation].

===== How would you use the custom Parameter Type defined by the following code?
[StepArgumentTransformation("(activated|deactivated)")]
public Status ConvertState(string activationState) 
{
    return new Status(activationState);
}

* {activated} or {deactivated}
* {activationState}
* {Status} - TRUE
* {ConvertState}

Answer: The name of a custom Parameter Type is defined by the name of the return type in the method that is decorated with the `[StepArgumentTransformation]` annotation.

