include::./title.adoc[]

shot::[1]
We can start with the step definition, which would look something like this:

[source, java]
----
include::../code/java/06--step06-sketch-out-parameter-type/shouty/src/test/java/shouty/StepDefinitions.java[lines=22..25]
----

shot::[2]
If we run Cucumber at this point we'll see an error, because we haven't defined the `{person}` parameter type yet.

[source]
----
TODO
----

Here's how we define one.

shot::[3] shot::[4]
Let's import `io.cucumber.java.ParameterType`:


[source, java]
----
include::../code/java/06--step06-sketch-out-parameter-type/shouty/src/test/java/shouty/StepDefinitions.java[lines=3]
----

We use the `ParameterType` annotation from Cucumber to define our new parameter type. shot::[5]

We need to give it a `name` which is the name we'll use inside the curly brackets in our step definition expressions. shot::[6]

We also need to define -- gasp! -- a regular expression. shot::[7] This is neccesary to tell cucumber expressions what text to match when searching for this parameter in a Gherkin step. We won't go into the details of regular expressions in this video, but in this case we're just matching on either of the names of the people we're using in our scenario. shot::[8]

Finally, we write a method, shot::[9], which, takes the text captured from the Gherkin step that matched the regular expression pattern as its argument. shot::[10] The return value is what will be passed to the step definition. In this case, we'll receive the name of the person (as a string) shot::[11] and return a new instance of the `Person` class. shot::[12]

If we wanted to, we could be more sophisticated here, and insert a record into our database for example.

[source, java]
----
include::../code/java/06--step06-sketch-out-parameter-type/shouty/src/test/java/shouty/StepDefinitions.java[lines=17..20]
----

shot::[13]
All of this means that when we run our step, we'll be passed an instance of `Person` into our step definition automatically.

[source]
----
TODO
----

Custom parameters allow you to bring your domain _model_ - the names of the classes and objects in your solution - and your domain _language_ - the words you use in your scenarios and step defintions - closer together.

