include::./title.adoc[]

shot::[1]
We can start with the step definition, which would look something like this:

[source, js]
----
include::../code/js/06-added-person-parameter/features/step_definitions/steps.js[lines=5..5]
----
shot::[2]
If we run Cucumber at this point we'll see an error, because we haven't defined the `{person}` parameter type yet.

----
$ npm test

> shouty@1.0.0 test /home/fedex/cucumber/chapter-03-code-js
> cucumber-js -f node_modules/cucumber-pretty

Error: Undefined parameter type {person}
    at UndefinedParameterTypeError.CucumberExpressionError [as constructor] (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber-expressions/dist/src/Errors.js:19:42)
    at new UndefinedParameterTypeError (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber-expressions/dist/src/Errors.js:47:23)
    at /home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber-expressions/dist/src/CucumberExpression.js:101:23
    at String.replace (<anonymous>)
    at CucumberExpression.processParameters (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber-expressions/dist/src/CucumberExpression.js:93:27)
    at new CucumberExpression (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber-expressions/dist/src/CucumberExpression.js:46:21)
    at buildStepDefinitionFromConfig (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:158:22)
    at /home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber/lib/support_code_library_builder/index.js:83:134
    at Array.map (<anonymous>)
    at SupportCodeLibraryBuilder.finalize (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber/lib/support_code_library_builder/index.js:83:71)
    at Cli.getSupportCodeLibrary (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber/lib/cli/index.js:120:50)
    at Cli.run (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber/lib/cli/index.js:141:37)
    at async Object.run [as default] (/home/fedex/cucumber/chapter-03-code-js/node_modules/cucumber/lib/cli/run.js:30:14)
npm ERR! Test failed.  See above for more details.
----

Here's how we define one.

shot::[3] shot::[4]
Let's create a new JS file in `features/support` called `person_parameter.js`:

.person_parameter.js
[source, js]
----
include::../code/js/06-added-person-parameter/features/support/person_parameter.js[lines=3..3]
----

We use the `defineParameterType` function from Cucumber to define our new parameter type. shot::[5]

We need to give it a `name` which is the name we'll use inside the curly brackets in our step definition expressions. shot::[6]

We also need to define -- gasp! -- a regular expression. shot::[7] This is necessary to tell Cucumber Expressions what text to match when searching for this parameter in a Gherkin step. We won't go into the details of regular expressions in this video, but in this case we're just matching on either of the names of the people we're using in our scenario. shot::[8]

Finally, there's a transformer block, shot::[9] which takes the text captured from the Gherkin step that matched the regular expression pattern, and runs some code. The return value of this block is what will be passed to the step definition. In this case, the block is passed the name of the person (as a string) shot::[10] which we can then pass to the `Person` class's constructor. shot::[11]

.person_parameter.rb
[source, js]
----
include::../code/js/06-added-person-parameter/features/support/person_parameter.js[]
----

shot::[12]
All of this means that when we run our step, an instance of `Person` will be passed into our step definition automatically.

[source]
----
$ npm test

> shouty@1.0.0 test /home/fedex/cucumber/chapter-03-code-js
> cucumber-js -f node_modules/cucumber-pretty

Feature: Hear shout

  Scenario: Listener is within range
    Given Lucy is located 1 metres from Sean
Person {}
Lucy is 100 centimetres from Sean
    ? pending
    When Sean shouts "free bagels at Sean's"
    - skipped
    Then Lucy hears Sean's message
    ? undefined

Warnings:

1) Scenario: Listener is within range # features/hear_shout.feature:2
   ? Given Lucy is located 1 metres from Sean # features/step_definitions/steps.js:5
       Pending
   - When Sean shouts "free bagels at Sean's" # features/step_definitions/steps.js:16
   ? Then Lucy hears Sean's message
       Undefined. Implement with the following snippet:

         Then('{person} hears {person}\'s message', function (person, person2) {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });


1 scenario (1 undefined)
3 steps (1 undefined, 1 pending, 1 skipped)
0m00.002s
npm ERR! Test failed.  See above for more details.
----

Custom parameters allow you to bring your domain _model_ - the names of the classes and objects in your solution - and your domain _language_ - the words you use in your scenarios and step definitions - closer together.
