==== Lesson 5 - Questions (Ruby)

===== Why did the Cucumber team create Cucumber Reports?

* To enable the removal of the HTML formatter
* To make it easier to share living documentation between stakeholders and team members (*Correct*)
* To make money from Cucumber users
* To get a chance to play with cloud platforms

Explanation:

The output from running Cucumber forms the basis of a system's "living documentation". There are lots of tools that let you do publish and share this living documentation, but they require effort to set up and configure. Now it's as simple as asking Cucumber to publish it.

===== How does the output from the HTML formatter differ from that displayed by Cucumber Reports?

* Cucumber Reports has much less detail that the HTML formatter
* Cucumber Reports uses animated GIFs and emojis to make the living documentation more exciting and fun
* Cucumber Reports are identical to the HTML output, but include some extra information about the build environment (*Correct*)

Explanation:

The same underlying library generates the output for both Cucumber Reports and the HTML formatter. Cucumber Reports also displays some extra information about that run of Cucumber, summarising the execution context and scenario outcomes.

===== What extra information can be published by Cucumber Reports? (*MULTIPLE_CHOICE*)

* Username of last committer
* Version of Cucumber that generated the report (*Correct*)
* Identifier (SHA) of the last git commit (*Correct*)
* Version of operating system that Cucumber ran on (*Correct*)
* Timestamp of when the report was generated
* Cucumber configuration properties used
* Number of scenarios that ran (*Correct*)
* Percentage of scenarios that passed (*Correct*)
* Version of CI tool that ran Cucumber (*Correct*)
* Code coverage statistics for run

Explanation:

Cucumber Reports always publishes:

* High level statistics of scenarios run and their status
* Elapsed time since the report was generated
* The time it took to run the scenarios and generate the report
* Operating system version
* Language version used for stepdefs
* Cucumber version

If Cucumber Reports was run by a supported CI tool, it also publishes:

* CI tool version
* Identifier (SHA) of the last commit

===== What happens to reports that are not associated with a "publish token"

* The report is not published
* The report is published and cannot be deleted
* The report is published and will be deleted automatically (*Correct*)

Explanation:

Reports that are not associated with a publish token will be deleted approximately 24 hours after being published. Once published, a report can be associated with a publish token, which will then preserve the report until it is explicitly deleted.

For more details on publish tokens, authentication, and association with Github repositories, see https://reports.cucumber.io
