include::./title.adoc[]

Sometimes, we want to write step defintions that allow us to use different values in our Gherkin scenarios. For example, we might want to have other scenarios that place Lucy a different distance away from Sean.

.hear_shout.feature
[source,gherkin]
include::../code/ruby/04-capture-int-parameter/features/hear_shout.feature[]

To capture interesting values from our step definitions, we can use a feature of Cucumber Expressions called _parameters_.

For example, to capture the number of metres, we can use the `{int}` parameter: shot::[] which is passed as an argument to our step definition: shot::[]

.steps.rb
[source,ruby]
----
include::../code/ruby/04-capture-int-parameter/features/step_definitions/steps.rb[lines=3..3]
----

Now we’re capturing that value as an argument. The value `100` will be passed to our code automatically by Cucumber.

Because we've used Cucumber Expressions' built-in `{int}` parameter type, the value has been cast to an `Integer` data type for us automatically, so we can do maths with it if we want.shot::[]

.steps.rb
[source,ruby]
----
include::../code/ruby/04-capture-int-parameter/features/step_definitions/steps.rb[lines=3..6]
----

Cucumber has a bunch of built-in parameter types: `{int}`, `{float}`, `{word}` and `{string}`. You can also define your own, as we'll see later.

