=== Capturing parameters

Sometimes, we want to write step defintions that allow us to use different values in our Gherkin scenarios. For example, we might want to have other scenarios that place Lucy a different distance away from Sean.

// TODO: snippet of scenario with distance of 1000 metres

To capture interesting values from our step definitions, we can use a feature of Cucumber Expressions called _parameters_.

For example, to capture the number of metres, we can use the `{int}` parameter: shot::[] which is passed as an argument to our step definition block: shot::[]

[source, ruby]
----
Given 'Lucy is {int} metres from Sean' do |distance|
  # TODO: automation code to place Lucy and Sean goes here
  puts "Lucy is #{distance / 100}km from Sean"
end
----

Now we’re capturing that value as an argument. The value 30 will be passed to our code automatically by Cucumber.

Because we've used Cucumber Expressions' built-in `{int}` parameter type, the value has been cast to an `Integer` data type for us automatically, so we can do maths with it if we want.shot::[]

Cucumber has a bunch of built-in parameter types: `{int}`, `{float}`, `{word}` and `{string}`. You can also define your own, as we'll see later.

