==== Lesson 3 - Questions

===== What do we mean when we say that BRIEF is a set of "heuristics"?

* We should follow them precisely or the BDD police will surely come and arrest us
* We can use them to guide our work, but we may find times when they're not approriate in our context (*Correct*)
* They are complicated and hard to remember

Explanation:

Heuristics are mental shortcuts - general guidelines that are easy to remember and can be trusted to work in most (but not all!) contexts.

===== B in "BRIEF" is for...

* Behaviour Describing - scenarios should describe behaviour
* Big - scenarios should have as many steps as possible
* Business Lanaguage - the language in your scenario should come from the business problem domain (*Correct*)
* Basic - keep it simple, don't add extraneous information

Explanation:

"B" is for *Business language:* The words used in a scenario should be drawn from the business domain, otherwise you will not be able to engage your business colleagues painlessly. The language you use should use terms that business team members understand unambiguously.

===== "R" in BRIEF stands for "Real Data". In the context of an ATM, which of these steps follow this heuristic?

* When Bobby makes a withdrawl of $50 (*Correct*)
* Given "User A" has opened an account
* Given an account with an arranged overdraft of $1
* When the user changes their PIN to 0000 (*Correct*)
* Given a cheque for $19.99 was deposited on 2021-04-01 (*Correct*)
* Given the book "Zen and the Art of Motorcyle Maintenance" has been on loan since 2021-06-01

Explanation:

"R" is for *Real data:* When you're first discussing the details of a story, your examples should use concrete, real data. This helps bring the scenarios to life, and expose boundary conditions and underlying assumptions early in the development process. When writing scenarios, we should also use real data whenever this helps reveal intention and make them move vivid.

Arguably, the PIN of 0000 is not very realistic, but if this step is being used in a scenario to describe validation rules for new PIN numbers, this could be entirely appropriate real-world data for an invalid PIN.

===== "I" in BRIEF stands for "Intention Revealing". Which of these steps are good at revealing their intention?

* When Bobby makes a withdrawl of $50 (*Correct*)
* When I click on ".btn-primary"
* When I submit the login form (*Correct*)
* Then the response should match "data/test_response-4591.json"
* Then the response should contain an overdraft limit of $50
* Given a book ""
* When the user changes their PIN to 0000 (*Correct*)
* Given a cheque for $19.99 was deposited on 1st April 2021 (*Correct*)

Explanation:

"R" is for *Real data:* When you're first discussing the details of a story, your examples should use concrete, real data. This helps bring the scenarios to life, and expose boundary conditions and underlying assumptions early in the development process. When writing scenarios, we should also use real data whenever this helps reveal intention and make them move vivid.

Arguably, the PIN of 0000 is not very realistic, but if this step is being used in a scenario to describe validation rules for new PIN numbers, this could be entirely appropriate real-world data for an invalid PIN.