=== Refactor the tests
Refactor: Clean up dead tests and code for Network
We’re green, so it’s refactoring time again!   
Now we can give that messy old test in Network’s unit tests the treatment it deserves [deletes it] because this behaviour is now on Person. We won’t be needing this pending test.  [deletes it] <ruby> and we don’t need to stub credits here anymore. </ruby>
Refactor: delete redundant unit tests
Deleting code is my favourite kind of refactoring! Let’s keep going and strip back all that crazy boolean login in Network#broadcast. I think we can just remove this whole clause about the message being too short or having enough credits or whatever. Let’s try it and see what the tests tell us.
Refactor: remove dead code
Excellent, much better!

=== Refactor Network
Now, can we do any refactoring in Network?
This method would read a lot better if we extract a method that returns only the listeners within range of the shouter. Let’s do that.
[extracts method]
We don’t need to use this shouter_location temporary variable either. Let’s inline it.
Refactor: Extract method to simplify Network#broadcast

