=== TDD our fix with a unit test

Now that we've added a unit test for charging when we mention the word "buy", we can add another one for when we mention it multiple times, which is the bug we were trying to solve in the first place.

We'll just copy and paste the previous spec and add buy three times.shot::[1]

The result should be the same.

[source,rb]
----
include::../code/ruby/07-write-test-for-mentioning-the-word-buy-more-than-once/spec/network_spec.rb[lines=83..93]
----

Now we make sure it fails.shot::[2]

[source,sh]
----
$ rspec
.......F.....

Failures:

  1) Shouty::Network credits deducts 5 credits even if you mention the word 'buy' several times
     Failure/Error: expect(sean.credits).to eq(95)
     
       expected: 95
            got: 85
     
       (compared using ==)
     # ./spec/network_spec.rb:92:in `block (3 levels) in <top (required)>'

Finished in 0.01892 seconds (files took 0.06003 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/network_spec.rb:83 # Shouty::Network credits deducts 5 credits even if you mention the word 'buy' several times
----

With this in place, we can focus on fixing the bug.shot::[3]

[source,rb]
----
include::../code/ruby/08-fix-the-bug/lib/shouty.rb[lines=54..57]
----

Removing this `g` flag means the regular expression won't match "globally" - so it will return just the first match, rather than all of them.

And run the specs.shot::[4]

[source,sh]
----
$ rspec
.............

Finished in 0.00798 seconds (files took 0.05958 seconds to load)
13 examples, 0 failures
----
Well look at that. One character! Just one little extra character caused us to do so much work! Sometimes computers can be so picky!

Aaannyway.

With our unit test suit all green, we're confident to remove the BUG reference and the `@wip` tag.shot::[5]

[source,gherkin]
----
include::../code/ruby/09-remove-wip-tag-and-bug-from-scenario/features/premium_shouts.feature[lines=19..22]
----

And we can run the full test suite to make sure everything's working as expected.shot::[6]

[source,sh]
----
$ rake
bundle exec rspec
.............

Finished in 0.00609 seconds (files took 0.06971 seconds to load)
13 examples, 0 failures

bundle exec cucumber --tags 'not @todo' --format progress
.........................................

7 scenarios (7 passed)
41 steps (41 passed)
0m0.019s

Randomized with seed 42310
----

And they all pass.

Fantastic.
