=== Dealing with execution results

shot::[1, "show output of the test execution in a command line shell, Hungarian feature file and specflow.json removed from the project"]

In the previous lessons we've learnt how to configure SpecFlow and how to run scenarios from Visual Studio and from the command line. The test output we have seen there contains a brief summary of the execution and the failures. If the test were executed on a Continuous Integration Server we probably also want to preserve and publish the test results. This is what we will look at in this lesson.

The `dotnet test` tool outputs the execution results through configurable loggers. The logger can be specified using the `--logger` option. There are multiple logger providers you can choose from. You can even write your own. But most of the teams use the TRX logger, that saves the execution results into a *Visual Studio Test Results* or TRX file. Let's use this. shot::[2, "type dotnet test --logger trx, run"]

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet test --logger trx
----

[source]
----
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Results File: W:\CucumberSchool\bdd-with-cucumber-code-dotnet\Shouty\Shouty.Specs\TestResults\gaspar_SPECSOL-D01_2021-01-22_15_46_29.trx

Passed!  - Failed:     0, Passed:     5, Skipped:     0, Total:     5, Duration: 137 ms - Shouty.Specs.dll (netcoreapp3.1)
----

The execution finished and reported that the results shot::[3, "highlight test result file"] have been saved to a file that has the current timestamp inside the TestResults folder of the project. Let's look at this file.

shot::[4, "open file explorer by typing `explorer .`, go to TestResults folder, highlight trx file"]
Visual Studio has been associated to this file extension, so if I open this file from file explorer shot::[5, "double-click on the file"], it opens it in Visual Studio. shot::[6, "show test results"] We can see all the individual test executions and even the details shot::[7, "show details of one of that"] of each of them where we see the step execution results.

The TRX files are XML files so it is easy to make any tools that processes the results and converts them to another format. It is, for example, a common expectation to present the execution results as an HTML file that can be checked by all stakeholders even if they don't have Visual Studio.

There are many small open source tools that can do such a conversion. shot::[8, "show github project in a browser"] For example the https://github.com/stevencohn/trxer[fork of the Trxer project by @stevencohn] on GitHub is a nice one that provides some dedicated styling for SpecFlow results.

shot::[9, "back to console"]
This one is a .NET assembly that I downloaded earlier, so now I can invoke it with the dotnet command we have seen already. shot::[10, "type command and run"]

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet <TrxReporter-path>\TrxReporter\TrxReporter.dll --input TestResults\gaspar_SPECSOL-D01_2021-01-22_15_46_29.trx
----

The result is a single HTML file that I could publish to my team workspace or just open locally. shot::[11, "open HTML by typing start path-to-html"] It shows the execution summary shot::[12, "show summary and highlight details"] as well as the individual scenario results grouped by features.

The TRX file format is also understood by most of the Continuous Integration platforms as well, so they can show the details included in the build results or even highlight whether the same tests were failing for the first time.

Processing the TRX file on the build server is not that easy with non-deterministic file names. In this case it is more useful to specify the output file name for the TRX logger. This can be done by specifying the `logfilename` parameter of the TRX logger like this. shot::[13, "type command and run"]

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet test --logger trx;logfilename=shouty-result.trx
----

shot::[14, "show soecflow+ livingdoc page"]
The https://specflow.org/blog/introducing-the-specflow-plus-livingdoc-generator/[SpecFlow+ LivingDoc Generator] from the Tricentis SpecFlow team uses a slightly different approach. This free tool does not process the TRX file, but produces its own result file and from that it is able to generate comprehensive documentation of your requirements based on the feature files and the scenarios you defined. Although the generated documentation also contains the test results, its primary focus is to produce the so-called *Living Documentation* -- documentation that shows whether the application currently fulfills the requirements.

In order to setup SpecFlow+ LivingDoc Generator, we need to install the `SpecFlow.Plus.LivingDocPlugin` NuGet package. shot::[15.1, "invoke dotnet add package command"]

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet add package SpecFlow.Plus.LivingDocPlugin
----

Now let's run the tests. We don't need the TRX file now, so running `dotnet test` is enough. shot::[15.2, "invoke dotnet test command"] The SpecFlow+ LivingDoc plugin generates a result file in the output folder, named `TestExecution.json` by default. shot::[16, "dir in folder, highlight TestExecution.json"]

[source]
----
C:\...\Shouty\Shouty.Specs>dir bin\Debug\netcoreapp3.1
----

Here it is!

Now we need to run the actual generator. The generator has to be installed as a .NET tool for the project.

Since this is the first .NET tool that we have install for this project, we need to first initialize the .NET tool configuration. For that we need to go up to the solution folder in our console window shot::[17, "invoke cd .."] and invoke `dotnet new tool-manifest` shot::[18, "invoke command"]. This creates a file named  `dotnet-tools.json` in the `.config` folder of the solution. You should add this file to your source control.

[source]
----
C:\...\Shouty\Shouty.Specs>cd ..
C:\...\Shouty>dotnet new tool-manifest
Getting ready...
The template "Dotnet local tool manifest file" was created successfully.
----

Now we can install the SpecFlow+ LivingDoc Generator. This can be done, using the `dotnet tool install` command that pulls the generator from NuGet.org and installs it for this project. shot::[20, "invoke command"]

[source]
----
C:\...\Shouty>dotnet tool install SpecFlow.Plus.LivingDoc.CLI

You can invoke the tool from this directory using the following commands: 'dotnet tool run livingdoc' or 'dotnet livingdoc'.
Tool 'specflow.plus.livingdoc.cli' (version '3.5.286') was successfully installed. Entry is added to the manifest file W:\CucumberSchool\bdd-with-cucumber-code-dotnet\Shouty\.config\dotnet-tools.json.
----

As the message says, the tool has been installed successfully and can be used with shot::[21, "highlight dotnet livingdoc"] the `dotnet livingdoc` command. 

First, let's step back to our SpecFlow project folder and start with `dotnet livingdoc`. shot::[22.1, "cd to specs"]shot::[22.2, "start typing"] Now we need to specify a couple of settings for the generator. If you get lost, you can always call dotnet livingdoc help or check the https://docs.specflow.org/projects/specflow-livingdoc/en/latest/LivingDocGenerator/Generating-Documentation.html[documentation].

We need to say `test-assembly`, shot::[23, "type test-assembly"] because we want to generate the result from an assembly, and we have to shot::[24, "type assembly name"] specify the compiled assembly of our Shouty project.

Finally we need to shot::[25, "type rest of the command"] provide the path of the generated TestExecution.json file using the `--test-execution-json` option. And run. shot::[26, "run"]

[source]
----
C:\...\Shouty\Shouty.Specs>dotnet livingdoc test-assembly bin\Debug\netcoreapp3.1\Shouty.Specs.dll --test-execution-json bin\Debug\netcoreapp3.1\TestExecution.json

W:\CucumberSchool\bdd-with-cucumber-code-dotnet\Shouty\Shouty.Specs\LivingDoc.html was successfully generated.
----

We've got the generated HTML file. shot::[27, "open html with start"] As you can see, the result focuses on the feature structure, shot::[28, "open structure, highlight results"] but the details are also displayed.

Since the result is a single HTML file, it is easy to share it with all stakeholders. If you use Azure DevOps to track your work items, you can use the integrated version of SpecFlow+ LivingDoc as well.

There are more and more tools that can help you to implement living documentation for SpecFlow, shot::[29, "show page"] like https://www.picklesdoc.com/[Pickles Doc], shot::[30, "show page"]https://github.com/Augurk/Augurk[Augurk] or shot::[31, "show page"] https://www.specsolutions.eu/specsync/[SpecSync for Azure DevOps]. The SmartBear Cucumber team is working on a platform shot::[32, "show page"] called https://reports.cucumber.io/[Cucumber Reports] that can be used to publish and share living documentation. At the time of the recording this is not yet available for SpecFlow, but hopefully it will be soon.

In this lesson we have enumerated a couple of options to share your results and your living documentation with the entire team. This is essential in order to facilitate a common understanding between people on the project -- which is our ultimate goal.

With that we finished this chapter. See you next time!