=== Formatter plugins
Let’s take a closer look at the `--format` option.

[source]
----
bundle exec cucumber --format help
----

shot::[1, show console output]
So far, every time we have run Cucumber, it has printed the features back to us - in the console. Cucumber can report results in other formats, and this is useful for generating reports.

shot::[2, run with html formatter]
Let’s try the HTML formatter.

When we use the html formatter we use dash-dash out to specify the file where the report should be written. Otherwise it will be written directly to the console.

shot::[3, open html output]

[source]
----
bundle exec cucumber --format html --out report.html
----

shot::[4, run with json formatter (although this may be deprecated)]
Let’s try another one - JSON.

shot::[5, show json output]
The JSON report outputs the results in a single file. You can write your own script or program to post-process this file to generate your own report.

shot::[6, run & highlight progress output]
There is also a progress formatter, which just prints out a single character for each step.

shot::[7, run & highlight JUnit output]
The JUnit formatter outputs results in an XML format, which many continuous integration servers will turn into a nice report.

shot::[8, multiple formatters]
We can specify multiple formatters like this. Only one formatter is allowed to output to the console -- all the others must have a dash-dash out specifying which file their output should be written to.

=== Rerun formatter

One of these formatter plugins is rather special - the rerun formatter. Before we try it out, let’s make one of our scenarios fail.

shot::[9, Changes “Two shouts” scenario’s “Sean shouts "Free bagels!"” step to “Sean shouts "Free cupcakes!" ]

We choose the rerun formatter and send the output to a file called rerun.txt.

Let’s look at what’s in that rerun.txt file. It’s a list of the scenarios that failed! And the format looks familiar doesn’t it? It’s using the line number filtering format we showed you earlier.

This is really useful when you have a few failing scenarios and you want to re-run only ones that failed. c:

This is a big time saver when you’re in the middle of a refactoring where you have broken a few scenarios and you are working yourself back to green.

=== Static configuration

It would be tedious if you had to write out these configuration options every time you run Cucumber. To make this easier you can write the options in a file called cucumber.yml that we showed you earlier.

In cucumber.yml file you can define one or more profiles that describe a set of configuration options for Cucumber.

For example, we can define a `dev` profile that runs only the @focus scenarios and uses the progress formatter.

We use the `--profile` option to choose this profile when running Cucumber.

To change the default behaviour of Cucumber, change the default profile. Let’s make Cucumber strict by default.

It’s common for teams to have a number of profiles defined, usually for the different environments where Cucumber runs. You can have a CI profile that behaves differently to the one you use on your dev machines, for example.

