=== Formatter plugins
Let’s take a closer look at the `--format` option.

[source]
----
npm test \-- --help
----

Now that we're using the @cucumber/pretty-formatter, Cucumber outputs the features - as it runs - in the console. Cucumber can report results in other formats, which can be useful for generating reports.

Let’s try the HTML formatter.


When we use the html formatter we append the filename that the report should be written to. Otherwise it will be written directly to the console.

[source]
----
npm test \-- --format html:report.html
----

Let’s try another one - JSON.

[source]
----
npm test \-- --format json:report.json
----

The JSON report outputs the results in a single file. You can write your own script or program to post-process this file to generate your own report. Additionally,  many continuous integration servers understand the json format and can turn it into a nicely formatted report.


[source]
----
npm test \-- --format progress
----

There is also a progress formatter, which just prints out a single character for each step. This is the default formatter, which we used in previous chapters.

We can specify multiple formatters like this.

[source]
----
npm test \-- -f html:report.html -f json:report.json -f progress
----

The one without a path appended will be written to the console. If you ask multiple formatters to output to the console, only the last one mentioned will actually produce any output.

=== Rerun formatter

One of these formatter plugins is rather special - the rerun formatter. Before we try it out, let’s make one of our scenarios fail.

shot::[1, Changes “Two shouts” scenario’s “Sean shouts "Free bagels!"” step to “Sean shouts "Free cupcakes!" ]

shot::[1, "run npm test and show failing output"]
We choose the rerun formatter and send the output to a file whose name is preceded by the `@` (at) sign. Let's call it @rerun.txt.

[source]
----
npm test \-- -f rerun:@rerun.txt
----

Let’s look at what’s in that @rerun.txt file. shot::[] It’s a list of the scenarios that failed! And the format looks familiar doesn’t it? It’s using the line number filtering format we showed you earlier.

This is really useful when you have a few failing scenarios and you want to re-run only ones that failed. We tell Cucumber to run only the failed scenarios by pointing it at the rerun file. shot::[]

[source]
----
npm test \-- @rerun.txt
----

This is a big time saver when you’re in the middle of a refactoring where you have broken a few scenarios and you are working yourself back to green.

Let's fix the scenario shot::[21, undo change in feature file]

.hear_shout.feature
[source,gherkin]
----
//include::../code/java/14-fix-error/shouty/src/test/resources/shouty/hear_shout.feature[lines=35..44]
----

and rerun the failing scenario again shot::[20, "run npm test from console"]

Great. We're back to green again.


