=== Formatter plugins

Cucumber can report results in other formats, which can be useful for generating reports. Let’s take a closer look at some of the formatter plugins that ship with Cucumber - starting with the HTML formatter.

When we use the html formatter we need to specify the filename that the report should be written to using the --out flag.shot::[1] Otherwise it will be written directly to the console.

[source]
----
bundle exec cucumber --format html --out report.html
----

Let's take a look at the html that has been generated. shot::[2, "Open target/my-report in the browser"] As you can see, this generates a nicely structured HTML page that details what scenarios were run and whether the system behaved as expected.

shot::[3, "run Cucumber"]
Next, we'll use the JSON formatter. We can use the abbreviated version of our `--format` and `--out` flags `-f` and `-o`.shot::[4]shot::[5]shot::[6]

[source]
----
bundle exec cucumber -f json -o report.json
----

The JSON report outputs the results in a single file. shot::[7, "open the json file"] You can write your own script or program to post-process this file to generate your own report. Additionally,  many continuous integration servers understand the json format and can turn it into a nicely formatted report.


There is also a progress formatter,shot::[8, run Cucumber] which just prints out a single character for each step.shot::[9]

[source]
----
bundle exec cucumber -f progress
----

shot::[10, "run cucumber with multiple formatters"]
We can specify multiple formatters like this.

[source]
----
bundle exec cucumber -f html -o  report.html -f json -o report.json -f progress
----

The one without a path appended will be written to the console. If you ask multiple formatters to output to the console, only the last one mentioned will actually produce any output.

==== Rerun formatter

One of the formatter plugins is rather special - the rerun formatter. Before we try it out, let’s make one of our scenarios fail. shot::[12, Changes “Two shouts” scenario’s “Sean shouts "Free bagels!"” step to “Sean shouts "Free cupcakes!" ]

[source,gherkin]
----
include::../code/js/13-introduce-an-error/features/hear_shout.feature[lines=38..46]
----

And see it fail on the terminal. shot::[13, "run npm test and show failing output"]

----
bundle exec cucumber
----

We choose the rerun formatter shot::[14] and send the output to a file. Let's call it `rerun.txt`.shot::[16] shot::[17, "run cucumber using rerun formatter"]

[source]
----
bundle exec cucumber -f rerun -o rerun.txt
----

Let’s look at what’s in that rerun.txt file. shot::[18, "open rerun.txt"] It’s a list of the scenarios that failed! And the format looks familiar doesn’t it? It’s using the line number filtering format that we showed you earlier.

This is really useful when you have a few failing scenarios and you want to re-run only ones that failed. We tell Cucumber to run only the failed scenarios by pointing it at the rerun file. shot::[19, "run Cucumber using the @rerun.txt file"]

[source]
----
bundle exec cucumber @rerun.txt
----

Using the `@`-sign in front of the filename tells Cucumber to read the rerun file's contents as though it was arguments on the command-line, just like we showed you in lesson 1.

This is a big time saver when you’re in the middle of a refactoring where you have broken a few scenarios and are working yourself back to green.

Let's fix the scenario shot::[20, undo change in feature file]

.hear_shout.feature
[source,gherkin]
----
include::../code/js/14-fix-introduced-error/features/hear_shout.feature[lines=38..46]
----

and rerun the failing scenario again shot::[21, "run npm test from console"]

Great. We're back to green again.


