include::./title.adoc[]

shot::[1, "show 'RunCucumberTest.java'"]
In the previous lesson, we ran Cucumber using Maven. Maven doesn't actually know how to run Cucumber, but it does know how to run JUnit tests. The RunCucumberTests class is called a Cucumber Runner and serves as a bridge between Cucumber and JUnit. This allows Cucumber to be integrated into any development environment or build server that understands JUnit -- which is most of them!

As you can see, there's not much in the Cucumber Runner class, but you can control how Cucumber runs by using the @CucumberOptions annotation. shot::[2, highlight annotation] We'll use this to show you how to filter using tags.

First, let's remove the filter from cucumber.properties. shot::[3] I'll explain the cucumber.publish.quiet property later in this chapter.

.cucumber.properties
[source]
----
include::../code/java/02-remove-properties-filter/shouty/src/test/resources/cucumber.properties[]
----

Now, Cucumber will run all scenarios. shot::[4, run Cucumber from IntelliJ by right clicking on RunCucumberTests]

shot::[5, "show 'Listener is out of range' scenario"]
We’ll put a focus tag right here, above this scenario. shot::[6, "add a @focus tag to the 'Listener is out of range' scenario"] Tags start with an at-sign and are case sensitive.

[source,gherkin]
----
include::../code/java/03-filter-by-tag-in-cucumber-options/shouty/src/test/resources/shouty/hear_shout.feature[lines=23..25]
----

Now let's add a tag expression to the @CucumberOptions annotation, which Cucumber will use to filter the scenarios run shot::[7]

.RunCucumberTest.java
[source,java]
----
include::../code/java/03-filter-by-tag-in-cucumber-options/shouty/src/test/java/shouty/RunCucumberTest.java[lines=8]
----

Now we can run only the scenarios tagged with focus - there should be only one... shot::[8, "run RunCucumberTest.java from IntelliJ, then highlight that only 'Listener is out of range' scenario was run"]

Yep.

It’s entirely up to you what you name your tags. When we’re working on a particular area of the application it is common to use a temporary tag like this - we’ll remove it before we check our code into source control.

Tags can be used for other purposes as well. If you have lots of scenarios it can be time-consuming to run them all every time. For example, you can tag a few of them with @smoke and run only those before you check in code to source control. shot::[9, tag first and third scenario with @smoke]

[source,gherkin]
----
include::../code/java/04-another-tag-example/shouty/src/test/resources/shouty/hear_shout.feature[lines=7..10]

    # ...

include::../code/java/04-another-tag-example/shouty/src/test/resources/shouty/hear_shout.feature[lines=24..27]
----

Running just the smoke tests will give you a certain level of confidence that nothing is broken without having to run them all. shot::[10]shot::[11]shot::[12, "run RunCucumberTest.java from IntelliJ, then highlight that only first and third scenarios were run"]

.RunCucumberTest.java
[source,java]
----
include::../code/java/04-another-tag-example/shouty/src/test/java/shouty/RunCucumberTest.java[lines=8]
----

If you’re running Cucumber on a Continuous Integration Server as well, you could run all the scenarios there, detecting any regressions you might have missed by only running the smoke tests.

Tags give you a way to organise your scenarios that cut across feature files. You can think of them like sticky labels you might put into a book to mark interesting pages that you want to refer back to.

Some teams also use tags to reference external documents, for example, tickets in an issue tracker or planning tool. Let’s pretend we are using an issue tracker while working on Shouty and all the behaviour we built so far is related to the issue number 11. We could tag the whole feature file with this single line at the top. shot::[13, tag feature with @SHOUTY-11]

.hear_shout.feature
[source,gherkin]
----
include::../code/java/05-tag-whole-feature-file/shouty/src/test/resources/shouty/hear_shout.feature[lines=1..2]
----

All the scenarios within that file now inherit that tag, so if we change the tag expression in @CucumberOptions, shot::[14, change CucumberOptions filter to @SHOUTY-11]

.RunCucumberTest.java
[source,java]
----
include::../code/java/05-tag-whole-feature-file/shouty/src/test/java/shouty/RunCucumberTest.java[lines=8]
----


Cucumber will run all the scenarios in the feature file. shot::[15, "run RunCucumberTest.java from IntelliJ, then show that all scenarios were run"]shot::[16]

You can use more complex tag expressions to select the scenarios you want to run. For example, you could use a tag expression to exclude all the scenarios tagged as @slow. shot::[17, "tag last two scenarios with @slow""]

.hear_shout.feature
[source,gherkin]
----
include::../code/java/06-logical-tag-expression/shouty/src/test/resources/shouty/hear_shout.feature[lines=34..]
----

Then rewrite the tag expression in CucumberOptions using the `not` keyword shot::[18, "modify CucumberOptions]

.RunCucumberTest.java
[source,java]
----
include::../code/java/06-logical-tag-expression/shouty/src/test/java/shouty/RunCucumberTest.java[lines=8]
----

Now when you run Cucumber, the "@slow" scenarios won't be run. shot::[19, "run RunCucumberTest.java from IntelliJ, then show that the slow scenarios were not run"]shot::[20]

Let's tidy up be removing the tag filter from CucumberOptions. shot::[21]

.RunCucumberTest.java
[source,java]
----
include::../code/java/07-remove-logical-tag-filter/shouty/src/test/java/shouty/RunCucumberTest.java[lines=8]
----

You can read about how to build more complicated tag expressions on the https://cucumber.io/docs/cucumber/api/#tag-expressions[Cucumber website] shot::[22, "open the link and show the Cucumber website"]

There's one more thing to learn about tags. They can be combined with hooks, so that you can be selective about which hooks to run when. We'll cover that in a future chapter.
