include::./title.adoc[]

shot::[1, "show 'Listener is out of range' scenario"]
Cucumber has a third filtering mechanism that uses tags. Tags start with an at-sign. We’ll put a focus tag right here, above this scenario. shot::[2, "add a @focus tag to the 'Listener is out of range' scenario"]

shot::[3, "run mvn from console, then highlight that only 'Listener is out of range' scenario was run"]
Now we can run only the scenarios tagged with focus - there should be only one...

[source]
----
mvn test -Dcucumber.filter.tags="@focus"
----

Yep.

It’s entirely up to you what you name your tags. When we’re working on a particular area of the application it is common to use a temporary tag like this - we’ll remove it before we check our code into source control.

Tags can be used for other purposes as well. If you have lots of scenarios it can be time-consuming to run them all every time. For example, you can tag a few of them with @smoke and run only those before you check in code to source control. shot::[4, tag first and third scenario with @smoke] Running just the smoke tests will give you a certain level of confidence that nothing is broken without having to run them all. shot::[5, "run mvn from console, then highlight that only first and third scenarios were run"]

[source]
----
mvn test -Dcucumber.filter.tags="@smoke"
----

If you’re running Cucumber on a Continuous Integration Server as well, you could run all the scenarios there, detecting any regressions you might have missed by only running the smoke tests.

Tags give you a way to organise your scenarios that cut across feature files. You can think of them like sticky labels you might put into a book to mark interesting pages that you want to refer back to.

Some teams also use tags to reference external documents, for example, tickets in an issue tracker or planning tool. Let’s pretend we are using an issue tracker while working on Shouty and all the behaviour we built so far is related to the issue number 11. We could tag the whole feature file with this single line at the top. shot::[6, tag feature with @SHOUTY-11] All the scenarios within that file now inherit that tag, so this command will run all the scenarios. shot::[7, "run mvn from console, then show that all scenarios were run"]

You can use more complex tag expressions to select the scenarios you want to run. For example, you could use a tag expression to exclude all the scenarios tagged as @slow. shot::[8, "tag last two scenarios with @slow""] Then pass a tag expression using the `not` keyword to Cucumber and the "@slow" scenarios won't be run. shot::[9, "run mvn from console, then show that the slow scenarios were not run"]

[source]
----
mvn test -Dcucumber.filter.tags="not @slow"
----

You can read about how to build more complicated tag expressions on the https://cucumber.io/docs/cucumber/api/#tag-expressions[Cucumber website] shot::[9, "open the link and show the Cucumber website"]

There's one more thing to learn about tags. They can be combined with hooks, so that you can be selective about which hooks to run when. We'll cover that in a future chapter.
