==== Lesson 2 - Questions

===== What language should be used in Feature files?

* Problem domain language (*Correct*)
* Solution domain language
* Language from both problem and solution domains

Explanation:

Feature files should try to avoid using language from the _solution_ domain, because that will exclude anyone who doesn't write code from being able to read them and give you feedback.

It can sometimes be hard, because we have to really learn the way our users and customers talk about their problems. But in the end that's one of the most beneficial things you can do for your project.

===== Examine the following scenarios. Which is using more problem domain language?

Scenario A:

```
Given database table "tblTasks" has data "Pay rent,Fetch milk"
When I visit "/"
And I click "ui.todos input[type='checkbox' value='Pay rent']"
Then there should be 1 item in "ul.done input[type='checkbox' value='Pay rent']"
Then there should be 1 item in "ul.not-done input[type='checkbox' value='Fetch milk']"
```

Scenario B:

```
Given a task "Pay rent"
And a task "Fetch milk"
When I complete the task "Pay rent"
Then the task "Pay rent" should be complete
Then the task "Fetch milk" should be incomplete
```

* Scenario A is using problem domain language
* Secnario B is using problem domain language (*Correct*)

Explanation:

The first scenario has details like the name of a database table, a browser URL, some CSS selectors. All of these are solution domain artefacts.

===== When you use problem-domain language in your scenarios, what is the trade-off?

* You may end up with more complex step definition code behind the features (*Correct*)
* You may alienate business people who prefer to read scenarios written in solution-domain language
* You end up having to write more scenarios
* Your scenarios can't be read by everyone on the team anymore

Explanation:

When you really think of your feature files as documentation first, tests second, you will prioritise readability over everything else. As a consequence, sometimes you'll end up needing to push some complexity down into your step definitions.

That's why building a support API can be useful, to help you manage this complexity.

The whole reason for using problem-domain language is that your whole team can understand them, meaning they can act as a shared source of truth.

You shouldn't need any more scenarios just because you use problem-domain language.