=== Removing redundant scenarios

Welcome back to Cucumber School.

shot::[1,feature file from end of Ch 4]

Last time we worked on cleaning up the Shouty features to keep them in sync with the current status of the project. We stripped the scenarios back to only specify the behaviour of passing messages between people. We made it clear that the proximity rule had not yet been implemented.

You’ll already remember from the Cucumber expressions chapter how important it is to be expressive in your scenarios, and keep them readable. In this episode we’re going to learn some new tricks with Gherkin that will give you even more flexibility about how you write scenarios.

Once again the Shouty developers -- have been hard at work implementing that proximity rule. Let’s have a look at how they got on.

shot::[2,Runs cucumber]

Right, so those two scenarios we just left as just placeholders: the one where the listener is within range, and the one where the listener is out of range have been fleshed out, and are passing. Fantastic!

Let’s review the changes to the feature file in more detail.

shot::[3,Show all four scenarios in feature file]

We now have four scenarios: our original two from the last time we looked at the code, and the two placeholders we wrote as reminders.

shot::[3a,Highlight second scenario]
We used the second scenario - Listener hears a different message - to triangulate and force us to replace the hard-coded message output with a proper implementation. Now we have a domain model that uses a variable for the message, there's an insignificant chance of this behaviour regressing, so we can safely remove the second scenario.

shot::[4,removes second scenario: Listener hears a different message]

Keeping excess scenarios is wasteful: they clutter up your feature files, distracting your readers. When you run your features as tests, excess scenarios make them take longer to run than necessary. The one where the listener is within range is a perfectly good way of checking that the message has been sent correctly.
