==== Lesson 4 - Questions

===== Where can you use a World object?

* In your step definitions (*Correct*)
* In a custom parameter type (*Correct*)
* In a `Before` / `After` hook (*Correct*)
* In your application code

Explanation:

Support code, like the World, is created by Cucumber and made available to your step definitions, parameter types and hooks. It doesn't make sense to have your application code depend on it.

===== Why would we put code into a World object?

* Move complexity out of our step definitions (*Correct*)
* Hide duplication
* Share code (*Correct*)
* Increase the readability of our step definitions (*Correct*)
* Optimizing performance
* To share state between steps (*Correct*)
* Reduce the coupling from the step defintions to the system under test (*Correct*)

Explanation:

There are many reasons to move code into a support layer!

Adding fields to store state allows us to pass context between steps, so we can make them feel more natural to read. 

If we have step definitions spread across multiple files, they can all access the same fields and methods on a shared World object.

Creating an API of methods on the World for interacting with our system makes the step definitions simpler, have less duplication between them, and easier to read. You'll end up being happy to have many similar step definitions - to match the wording you want to use in your scenarios - because they all delegate to the same underlying code.