include::./title.adoc[]

Cucumber is first and foremost a tool that facilitates a common understanding between people on a project. Imagine our customers were cats. We could write our features in English, but the cats would obviously not understand that, so I'll show you how to write a scenario in LOLCAT instead.

You can get a list of all the supported languages with --i18n-languages. shot::[1]

[source]
----
bundle exec cucumber --i18n-languages
----

Cucumber supports over 70 different languages, thanks to contributions from people from all over the world.

To see the translation of the Gherkin keywords for a particular language, just use the '--i18n' option with the language code. shot::[2]

[source]
----
bundle exec cucumber --i18n-keywords en-lol
----

Now create a new feature file in the `features` directory called `cat.feature` shot::[3]

The first line tells Cucumber which language the feature file is written in. shot::[4]
[source, gherkin]
----
# language: en-lol
----

Cucumber then expects the Gherkin keywords to be in LOLCAT shot::[5]

[source, gherkin]
----
# language: en-lol

OH HAI: HEAR SHOUT

  MISHUN: MESAGE IZ 2 LONG
    I CAN HAZ A KAT CALLD SHOUTR


----

The step is undefined, but we can quickly generate it by running Cucumber shot::[6, run new scenario] Cucumber has generated a step definition.

We could copy and use this step definition in our `steps.rb` file the same way we do with regular English. But let's remove the `cat.feature` file and continue.shot::[7]

Notice that when we run Cucumber, the scenarios run in the order that the occur in the feature file shot::[8, expand/highlight the test results] That's fine, but there's a chance that since they always run in the same order we might accidentally make one scenario dependent on some other scenario.

Each scenario should be isolated - it's result should not depend on the outcome of any other scenario. To help you catch any dependencies between your scenarios, Cucumber can be told to run your scenarios in a random order.

To do this, we can use the random flag in the profile file. shot::[9]

[source]
----
default: --quiet --order random
----

Now when we run Cucumber, the scenarios are run in a random order shot::[10, run Cucumber & show new order of scenario execution]. Now there's almost no chance of a dependency between scenarios slipping through without being noticed.

shot::[11, "show 'List configuration options' section of"]
A full list of Cucumber's configuration properties can be found by passing the `--help` flag on the command line. shot::[12, highlight top of output] The same can be accomblished by using the abbreviated version `-h` shot::[13]

[source]
----
bundle exec cucumber --help
bundle exec cucumber -h
----

That's quite a lot to digest, but to make Cucumber really useful to your team, it’s good to spend some time learning the details of how to configure it. In this lesson, we showcased two of Cucumber’s configuration options and you learned how to write your scenarios in different spoken languages.
