==== Lesson 2 - Questions

===== Why did we confirm the business rules with our product owner, Paula?

* Paula will fire us if we get the business rules wrong
* As Product Owner, it's Paula's responsibilty to decide which rules we should implement in our code (*Correct*)
* We want to as confident as we can that they're correct before we proceed (*Correct*)
* We don't want Paula to feel left out

Explanation:

Teams should collaborate to discover and decide on the business rules their code should implement but ultimately, on most teams, it's the Product Owner's decision what is "correct" or incorrect behaviour.

Getting this clarified only takes a few minuutes, and can save us potentially wasting our time further down the line building upon an earlier misunderstanding.

===== Why did we not use the Rule: keyword as described in chapter 4?

* The version of Cucumber we're using doesn't support it
* Paula doesn't like that way of writing Rules in Gherkin
* The big scenario is covering multiple rules, so we couldn't place it under a single Rule (*Correect*)

Explanation:

Before we had the `Rule` keyword in Gherkin, we always used to recommend to teams to write their rules down at the top of the feature file. This works great, but using the `Rule` keyword to make an explicit link between each scenario and the rule it illustrates is even better. As soon as we've broken this scenario down into smaller ones that only illustrate one rule, we can do that.

===== Which of these statements are true?

* Using real details in your scenario can help with divergent thinking (*Correct*)
* Divergent thinking closes our minds to the possiblity of scenarios we haven't thought of
* Details are things like real names of people or products, dates, or amounts (*Correct*)
* Finding the right level of detail to use in a scenario is easy
* Incidental details are details that aren't relevent to the purpose of the scenario (*Correct*)
* If your team can't agree on the right level of detail then you should give up on BDD

Explanation:

Finding the right level of detail, and discerning which details are incidential to your scenario is a difficult, subjective process. The key thing to do is keep trying. Each time you talk about it as a team, you will better align your perspectives (as long as you listen to each other!) and hone your own domain language.