include::./title.adoc[]

shot::[1,"open step def"]

.StepDefinitions.cs
[source,c#]
----
include::../code/dotnet/10--step10-use-whereabouts-class/Shouty/Shouty.Specs/StepDefinitions/StepDefinitions.cs[lines=54..61]
----

We separated the Data Table conversion from the step definition. The step definition is nice and clean now, but our conversion method is still fairly complex as it needs to handle the table headers and the cell data conversion. shot::[2,"open conversion"]

.StepDefinitions.cs
[source,c#]
----
include::../code/dotnet/10--step10-use-whereabouts-class/Shouty/Shouty.Specs/StepDefinitions/StepDefinitions.cs[lines=24..34]
----

But even though it is complex, we can notice a pattern in it. We take the "name" cell and update the `Name` property of the Whereabouts object. We take the "location" cell and update the `Location` property... This is not a big surprise for us, because we let the domain terms in the scenarios drive our domain model.

When this happens, this sort of consistency allows us to simplify the code further. SpecFlow defines an extension method on the Table class, called `CreateSet`. `CreateSet` can do exactly what we need here: create instances of a particular class and update its properties based on the table cells. shot::[3,"change DefineWhereabouts to use CreateSet"]

.StepDefinitions.cs
[source,c#]
----
include::../code/dotnet/11--step11-use-createset/Shouty/Shouty.Specs/StepDefinitions/StepDefinitions.cs[lines=25..29]
----

The `CreateSet` extension method is defined in the `TechTalk.SpecFlow.Assist` namespace, so we have to add a using statement for that. shot::[4,"add using statement"]

.StepDefinitions.cs
[source,c#]
----
include::../code/dotnet/11--step11-use-createset/Shouty/Shouty.Specs/StepDefinitions/StepDefinitions.cs[lines=5]
----

shot::[5,"run tests"] With that change our conversion method is also clean and our tests still pass.

shot::[6, show data tables in feature file]
Data tables are very useful for setting up data in Given steps, but you can also use them for specifying outcomes.

One rule that we’ve been implying, but have never actually explored with an example, is that people can hear more than one shout. So far we’ve only specified a single message, so let’s try writing a scenario where Sean shouts more than once: shot::[6, "write two-shouts scenario"]

.HearShout.feature
[source,gherkin]
----
include::../code/dotnet/12--step12-outcome-data-table/Shouty/Shouty.Specs/Features/HearShout.feature[lines=35..45]
----

See how natural it is to use a Data Table here?

So how do we implement this step definition? First, let's paste the generated snippet into the StepDefinitions class and rename the parameter. shot::[7, "define steps, copy, paste snippet, rename parameter to expectedMessagesTable"] What we want to do in this step definition is compare the messages that are actually heard with the messages we expected to hear. Getting the actual messages is easy, we just need to call the `GetMessagesHeard` method. shot::[8, "add actualMessages"] For the expected messages, we need to take the "message" cell from each table row like this. shot::[9, "add expectedMessages"] And finally we can make sure they are the same using an assert statement. shot::[10, "add assert"]

.StepDefinitions.cs
[source,c#]
----
include::../code/dotnet/13--step13-use-collection-assert/Shouty/Shouty.Specs/StepDefinitions/StepDefinitions.cs[lines=89..95]
----

shot::[11,"runs tests"] Oops! It looks like there is a problem. The two lists are different. By checking the error message we can see that there is a typo in our scenario. shot::[12,"highlight error message"] But let's not fix this yet. Instead, let's look at another typical pattern for a data table related assertion.

shot::[13,"show type of actualResults"] The `GetMessagesHeard` method returned a list of strings, but in many cases the list that we want to compare the Data Table with is a list of objects. Let's imagine that later we will extend the `GetMessagesHeard` method to not only return the message but also the person who shouted it. shot::[14,"add HeardMessage and GetMessagesHeardEx"] To simulate that let's add an alternative version of `GetMessagesHeard`, called `GetMessagesHeardEx`. The new method returns a list of `HeardMessage` instances. shot::[14.2,"highlight method return type"] The HeardMessage class has only one property, the message, shot::[15,"highlight Message property"] but later we might extend it.

.Person.cs
[source,c#]
----
include::../code/dotnet/14--step14-use-comparetoset/Shouty/Shouty/Person.cs[lines=30..40]
----

Let's first change the part of the step definition that calculates the actual messages by calling our extended method. shot::[16,"change actualMessages calculation, show type of the result"]

.StepDefinitions.cs
[source,c#]
----
include::../code/dotnet/14--step14-use-comparetoset/Shouty/Shouty.Specs/StepDefinitions/StepDefinitions.cs[lines=92..92]
----

To compare this with the expected messages in the table, we need to check if the "message" cell matches the `Message` property for each row. If there was a "shouter name" cell we would have to match that to a `ShouterName` property and so on. This is the same consistency that we had when we used CreateSet. For such assertions, we can use another helper method, called `CompareToSet`.

It works similarly to CreateSet. shot::[17,"add CompareToSet call"] The CompareToSet is an extension method on the Table class from the Assist namespace, and you need to pass the list of objects that you would like to compare the table with. shot::[18,"highlight actualMessages argument"]

.StepDefinitions.cs
[source,c#]
----
include::../code/dotnet/14--step14-use-comparetoset/Shouty/Shouty.Specs/StepDefinitions/StepDefinitions.cs[lines=89..94]
----

Both CreateSet and CompareToSet can be further customized, but this is just enough for us. Let's run the tests and look at the error message.

shot::[19,"run tests"]

Oh! We've found the typo: we should have included exclamation marks on the expected messages. shot::[20] Well, at least this gives you a chance to see the nice diff output from CompareToSet when the table and the list are different. We see the expected values prefixed with a minus, and the actual values prefixed with a plus.

Let’s fix just one of these shot::[21,add an exclamation mark] so you can see how the diff output changes.

.HearShout.feature
[source,gherkin]
----
include::../code/dotnet/15--step15-fix-first-typo/Shouty/Shouty.Specs/Features/HearShout.feature[lines=44..44]
----

shot::[22,run tests]
The matching bagels! line no longer has a minus, and for the mismatched row, the actual value still has a minus, and the expected value has a plus.

Let’s fix this last typo shot::[23,add another exclamation mark], and we should be green again.

.HearShout.feature
[source,gherkin]
----
include::../code/dotnet/16--step16-fix-second-typo/Shouty/Shouty.Specs/Features/HearShout.feature[lines=45..45]
----

shot::[24,run tests]

Great.
