== Epilogue

This concludes our epic journey to get you started using Cucumber as it was intended - a tool to help you and your team decide what to build, build it, and maintain it for years to come.

I've been working with these techniques for 20 years now, and I'm still learning new stuff every day. So don't get disheartened if it seems overwhelming sometimes.

There's a great supportive community of other practitioners waiting for you in our https://cucumber.io/community#slack[Community Slack] and there are a wealth of great books you can pick up for further study.

There's the classic Cucumber Book, which has versions in both https://pragprog.com/titles/hwcuc2/the-cucumber-book-second-edition/[Ruby] and https://pragprog.com/titles/srjcuc/the-cucumber-for-java-book/[Java].

There's John Fergusson Smart's https://www.manning.com/books/bdd-in-action[BDD in Action].

There's Richard Lawrence and Paul Rayner's book https://www.pearson.com/store/p/behavior-driven-development-with-cucumber-better-collaboration-for-better-software/P200000009515/9780321772633[Behavior-Driven Development with Cucumber]

And last but definitely not least, there's Seb Rose and Gaspar Nagy's series of three, https://bddbooks.com/[The BDD Books: Discovery, Formulation and Automation].

If you're keep to see more courses here on Cucumber School on other topics, or you'd just like to give us some feedback on this course, please come into the Slack and let us know. We'd love to hear from you.