=== Running the scenario with Cucumber
==== Installation

// shot()
Before we get started make sure you have a modern version of Ruby installed,
// shot()
and the Bundler gem. Open a command-prompt and type:

[source,bash]
----
$ ruby -v
$ bundle -v
----
If you see an error message when you run these commands, you’ll need to fix your Ruby installation.

Go back to the command prompt and create a new directory for our project:

[source,bash]
----
$ mkdir shouty
----

// TODO: remove reference to editor
Go use cd to go into that directory, and open it up in your editor:

First we’ll create a Gemfile that describes the Ruby gems we need for our project. We’ll add Cucumber and RSpec-Expectations.

Now go back to the command-line and run `bundle install` to install those gems.

[source,bash]
----
$ bundle install
----

Now we’re ready! If we run `cucumber` at this point, we’ll see it’s telling us to create a features directory.

// TODO: add output
[source,bash]
----
$ bundle exec cucumber
----

Good, we've installed Cucumber.

This failed, but it did it for the right reason. Now we need to write our specification.
