= Chapter 1

== Lesson 1

=== What does BDD stand for?

* Business driven development
* Behaviour-Driven Development
* Behaviour-Driven Design - TRUE
* Bug-Driven Development
* Business-Driven Design

Explanation: BDD is an approach that collaboratively specifies the system's desired behaviour. Each time a piece of behaviour is agreed, we use that specification to "drive" the development of the code that will implement that behaviour.

=== What are the three practices of BDD, and in what order do you apply them to a story?

* Exploration - Conversation - Specification
* Discovery - Conversation - Specification
* Formulation - Specification - Automation
* Discovery - Formulation - Automation - TRUE
* Discovery - Specification - Formulation

Explanation: We start by collaboratively discovering the scope of the behaviour required by the story. Once we have agreed on that behaviour, we formulate the specification in business-readable language. Finally, we automate the formulated specification to verify that the system actually behaves as expected.

<Java, JS, Ruby>
=== How are Cucumber and BDD related?

* BDD is a collaborative way of working for teams that can include using Cucumber - TRUE
* Cucumber is required for you to do BDD
* If you're using Cucumber you're doing BDD
* Cucumber was invented before BDD came along

Explanation:

Cucumber is a tool that understands your documentation and turns it into automated tests.

BDD is a collaborative approach, made up of three practices. BDD practitioners may use Cucumber to automate their documentation.

</Java, JS, Ruby>

<C#>
=== How are SpecFlow and BDD related?

* BDD is a collaborative way of working for teams that can include using SpecFlow - TRUE
* SpecFlow is required for you to do BDD
* If you're using SpecFlow you're doing BDD
* SpecFlow was invented before BDD came along

Explanation:

SpecFlow is a tool that understands your documentation and turns it into automated tests.

BDD is a collaborative approach, made up of three practices. BDD practitioners may use SpecFlow to automate their documentation.

</C#>

=== What do we mean by “living documentation”

* Documentation that can be automatically verified against the application - TRUE
* Documentation that is reviewed as part of the "definition of done"
* Documentation generated by running automated tests
* Documentation that tells you when it's out of date - TRUE
* Documentation that is kept up-to-date on a wiki

Explanation:
"Living documentation" automatically tells us when the system and the documentation are out of sync. This may be for one of several reasons:

    the behaviour specified has not yet been implemented
    the implementation contains a defect
    the documentation is out of date

== Lesson 2

=== BDD practitioners prefer comprehensive documentation over collaboration

* True - TRUE
* False

Explanation:
BDD is a collaborative activity. Living documentation is a secondary, valuable, output of applying BDD practices.

=== What’s the relationship between BDD and agile?
* BDD is part of Agile
* They’re completely unrelated
* BDD complements your agile process - TRUE
* You can’t start doing Agile until you’ve got the hang of BDD

Explanation:
BDD is a collection of practices that build upon agile ways of working, helping teams succeed. For these practices to deliver value, you'll need to be working in an agile way.

=== What is it about User Stories that helps a team to do BDD?

* BDD practitioners like telling stories to each other
* User stories guarantee that the team will properly understand their requirements
* User stories come with acceptance criteria that can be translated into scenarios
* User stories let you defer getting into the details of a requirement until the right time, so you don’t waste effort - TRUE

Explanation:
User stories were created to be "placeholders for a conversation." They allow us to defer detailed analysis until we're confident that the behaviour they describe actually needs to be developed.

== Lesson 3

=== Why do we call it “Three Amigos”?

* At least three people should attend
* Only three people should be in the meeting
* It’s mandatory for the people in the meeting to be friends
* We want to have at least three different perspectives from the team represented - TRUE

Explanation:
The goal of a three amigos meeting is to ensure that the team fully understand the scope of the story being discussed. For this to be effective, we need to have at least three different perspectives represented at the meeting.

More than three people might attend a three amigos meeting, because:

    some stories are broad enough to require the input of more than three perspectives
    more than one representative of each perspective may attend

=== Who are the three amigos?

* Product Owner, Tester and Developer - TRUE
* Three of the best developers on the team
* An architect, the project manager and a tester
* Customer representative, Product Owner and the Lead Developer

Explanation:
The essential three perspectives required are:

    customer / business perspective - usually provided by the Product Owner
    development perspective - usually provided by a Developer
    test perspective - usually provided by a Tester

=== The group discovered a new business rule during the meeting. Why?

* The Product Owner hadn’t prepared properly
* Darren has more experience than the others
* Discovery is a natural part of the process - TRUE
* The team were in too much of a hurry to notice it before

Explanation:
The whole purpose of the three amigos meeting is to _discover_ things about the story that weren't previously obvious. We should expect to learn new things during a three amigos meeting.

== Lesson 4

=== Why are questions a valuable output from a discovery session?

* We get a sense of how ready we are to work on this User Story - TRUE
* They give us something valuable to work on - TRUE
* We have turned unknown unknowns into known unknowns - TRUE
* They show that the customer has not thought things through

Explanation:
We want to discover our areas of ignorance before we start developing the next piece of functionality. If we still have unanswered questions about a piece of functionality, it's unlikely that we're in a position to start working on it.

Before the discovery workshop, the question hadn't been asked. That means it was an _unknown unknown_ - it was something that we were completely unaware of. Now that we have asked the question, it is a _known unknown_ - we are aware that it is an area that we need to learn more about.

Having discovered the question, the team now has a concrete area to investigate, learning more about the problem they're being asked to solve.

=== Why are testing skills valuable during discovery?

* Discovery is not for testers
* Testers can decide what to automate
* It helps testers know what to put in the test plan
* We can test ideas as well as code by asking questions - TRUE

Explanation:
The test perspective is essential during the discovery process. It allows us to ask difficult "what if " style questions that ensure that we have thought about the story in detail. The team use concrete examples to test their understanding of what they're being asked to deliver, while also testing the product owner's understanding of the functionality they're asking for.


== Lesson 5

=== What is Gherkin?

* A pickled cucumber
* A style of writing that uses Given/When/Then
* A way of writing business-readable executable specifications - TRUE
* A programming language for test automation

Explanation:
Gherkin is a simple syntax that allows teams to write business readable, executable specifications.

Some of the Gherkin keywords are Given, When, and Then, but not all text that uses these words is Gherkin.

Gherkin is understood by a large number of tools, notably Cucumber and Specflow, that effectively turn the specification into automated tests.

=== What’s the relationship between a scenario and an example?

* A scenario can contain multiple examples
* Examples are not related to scenarios
* Cucumber understands scenarios, but doesn’t understand examples
* A scenario is an example formulated into Gherkin - TRUE

Explanation:
During three amigos the team uses concrete examples to ensure that they have a shared understanding of the functionality they're about to develop. Those concrete examples are _formulated_ into Gherkin scenarios.

So, each scenario is an example.

Scenario and Example are both keywords in Gherkin.
