==== Lesson 5 - Questions

===== If we find an untested edge case we didn't expect in our code, what should we do?

* Remove the behaviour; it shouldn't be there
* Leave it where it is, and walk away, slowly; hope nobody notices
* Talk to the product owner to find out whether the code is doing what's expected (*Correct*)
* Add a unit test for the current behaviour and move on

Explanation:

Ultimately, unless this code is never going to change again, we'll probably want to retro-fit 
a new test to the behaviour, but first we need to determine what that behaviour should be.

===== Once we get an answer, what do we do next?

* Refactor the code in order to make it more readable
* Add a test to ensure we don't have regresions (*Correct*)
* File a complaint about the developer who came before us
* Debate with the product owner to get them to change their mind

Explanation:

Unless we're really confident that the behaviour we've discovered is correct, we'd always
want to check with our product owner first, before we make a decision what to do next.

===== Is it necessary to run the whole test suite once we know the unit tests are passing with the new feature in?

* Yes, we always want to make sure we didn't break something else by accident (*Correct*)
* Nah, we only changed a small amount of code
* No, if the unit tests passed, that's enough for us
* It will take too long. Better leave it to someone else to run them.

Explanation:

Running the whole suite of tests is a great way to give yourself a calm feeling that
everything is working. It's a good thing to do before you call anything done, and check
in your code.
