=== Another edge case

One nice thing about working with unit tests (or microtests as Mike Hill likes to call them) is that they bring your focus down to a very narrow part of the code. Wheras a Cucumber scenario is for zooming out and thinking abou the big picture, a unit test puts a microscope on one tiny part of the system.

Sometimes that helps us to see things we hadn't anticipated.

Let's take a look at the `deduct_credits` method. shot::[1]

[source,java]
----
include::../code/java/10-remove-scenario-from-feature-file/shouty/src/main/java/shouty/Network.java[lines=33..43]
----

There's something on this method that caught our attention: the regex we're using is case sensitive.shot::[2]

[source,java]
----
include::../code/java/10-remove-scenario-from-feature-file/shouty/src/main/java/shouty/Network.java[lines=9]
----

Which raises the question, what should happen if the word has a different capitalization? What if they literally shout "BUY" in capitals?

To answer this question, we have a quick chat with Paula, who confirms that it should have the same effect as if it were lowercased: deduct 5 credits.

So lets first add a test.shot::[3]

We'll copy the same test we copied last time,shot::[4] and capitalize the word "Buy".shot::[5]

[source,java]
----
include::../code/java/11-add-test-for-capitalized-buy/shouty/src/test/java/shouty/NetworkTest.java[lines=107..118]
----

Now we run the test to watch it fail.shot::[6]

[source,sh]
----
$ mvn test
----

Now we write the code that'll make it pass.shot::[7]

[source,java]
----
include::../code/java/12-make-capitalized-buy-test-pass/shouty/src/main/java/shouty/Network.java[lines=9]
----

And finally, we run the entire test suite to watch that beautiful green.shot::[8]

[source,sh]
----
$ mvn test
----

Great. So working with unit tests here has helped us to notice and fix another small edge-case. Normally if we were doing test-driven development, we'd have spotted this at the time this code was written, especially if we were doing ensemble programming and had some other folks thinking about and reviewing the code as we wrote it.
