==== Lesson 3 - Questions

===== What is the name of the Gherkin syntax that allows you to specify pipe-separated, tabular data for a step?

* Array
* Data Matrix
* Data Table -- TRUE
* Example Table
* Table

Explanation:
The Gherkin syntax is called a Data Table. It represents a 2-dimensional array, with cell boundaries indicated by pipe characters `|`

===== What value would be retieved from cell (1, 2) in the following table?

| 0 | 1 | 2 |
| 3 | 4 | 5 |
| 6 | 7 | 8 |

* 0
* 1
* 2
* 3
* 4
* 5 -- TRUE
* 6
* 7
* 8

Explanation:
The data table is indexed, starting from 0. The first coordinate indicates which _row_ to access, the second indicates the _column_.

===== Which of the answers correctly shows how Cucumber will convert the following data table into a list of maps?

| A | B | C |
| D | 0 | 1 |
| E | 2 | 3 |

* [{A=A, B=B, C=C}, {A=D, B=0, C=1}, {A=E, B=2, C=3}]
* [{A=D, B=2, C=1}, {A=E, B=0, C=3}]
* [{A=B, D=0, E=2}, {A=C, D=1, E=3}]
* [{A=D, B=0, C=1}, {A=E, B=2, C=3}] -- TRUE

Explanation:
When Cucumber converts a Data Table into a list of maps, it treats the first row as the labels (or indexes), and each subsequent row provides the values for the next map within the list.

So, in this example, since there are three rows, we end up with two maps in the list -- the first row providing the indexes into each map, the next two rows providing the values for the two maps that are added to the list.

===== What does it mean to annotate a method with @DataTableType?

*

Explanation:
