include::./title.adoc[]

Let's look at the two scenarios that illustrate the rule about range again shot::[1,"show the range rule & scenarios"]. Notice how the steps shot::[2,"compare the two scenarios"] that create the Sean, Lucy, and Larry are very similar.

When we see steps like this, Gherkin’s Given When Then syntax starts to feel a bit clunky. Imagine if we could just write out a table, like this:

shot::[3,feature file]

.hear_shout.feature
[source,gherkin]
----
include::../code/js/05-location-specified-in-data-table/features/hear_shout.feature[lines=17..20]
----

Well, we’re in luck. You can!

Gherkin has a special syntax called Data Tables, that allows you to specify tabular data for a step, using pipe characters to mark the boundary between cells.

shot::[4,"run cucumber, copy snippet, paste into StepDefinition.java"]

.steps.js
[source,js]
----
include::../code/js/06-table-snippet-added/features/step_definitions/steps.js[lines=25..28]
----

As you can see, the step definition implicitly takes a single argument shot::[5,"highlight stepdef parameters"], which as this comment explains is a DataTable. This object has a rich API for using the tabular data.

At its most basic, the table is just a two-dimensional array. So, Lucy's location can be accessed shot::[6,"Print out a single cell value"] by getting the value from array cell (2, 1)

.steps.js
[source,js]
----
include::../code/js/07-use-datatable-raw-to-demonstrate-2d-array/features/step_definitions/steps.js[lines=25..27]
----

shot::[7,"run Cucumber, highlight 'Lucy's location'"]

You can also turn the table into a List of Maps shot::[8,"Print out data table"], where the first row is used for the map keys, and each following row is used for the map values.

.steps.js
[source,js]
----
include::../code/js/08-table-as-hashes/features/step_definitions/steps.js[lines=25..27]
----

shot::[9,"run Cucumber, highlight data table output"]

Now we can easily iterate shot::[10,"write the loop"] over these maps and turn them into instances of Person:

.steps.js
[source,js]
----
include::../code/js/09-iterate-over-people-in-table/features/step_definitions/steps.js[lines=25..29]
----

shot::[11,"run cucumber -- all green"]


With that done, we can update the other scenario shot::[12,"update other scenario"] ...

.hear_shout.feature
[source,gherkin]
----
include::../code/java/10--step10-changed-other-scenario-and-deleted-unused-stepdef/shouty/src/test/resources/shouty/hear_shout.feature[lines=24..31]
----

... and delete our old step definition shot::[13,"delete unused step def"], which is now unused.

.steps.js
[source,js]
----
include::../code/js/09-iterate-over-people-in-table/features/step_definitions/steps.js[lines=21..23]
----

shot::[14,"run cucumber"]

Cucumber strips all the white space surrounding each cell shot::[15,"show lining up of pipe characters"], so we can have a nice neat table in the Gherkin but still get clean values in the step definition underneath.

Notice we’ve still had to convert the location from a string to an integer shot::[16,"Conversion in step def"], because Cucumber can’t know that’s the type of value in our table.

.steps.js
[source,js]
----
include::../code/js/10-changed-other-scenario-and-deleted-unused-stepdef/features/step_definitions/steps.js[lines=21..25]
----

That looks much nicer - shot::[20,"hear_shout.feature data tables"] people positioned using a table in the feature file and shot::[21,"people_are_located_at()"] really clean code that creates and positions people according to the data.

.hear_shout.feature
[source,gherkin]
----
include::../code/java/10--step10-changed-other-scenario-and-deleted-unused-stepdef/shouty/src/test/resources/shouty/hear_shout.feature[lines=24..31]
----
