include::./title.adoc[]

Let's look at the Shouty scenario from the last chapter. shot::[1, "initial zoom 150%"]

.HearShout.feature
[source,gherkin]
----
include::../code/dotnet/01--step01-literal-match/Shouty/Shouty.Specs/Features/HearShout.feature[lines=1..6]
----

As SpecFlow starts to execute this feature, it will come to the first step of the scenario `Given Lucy is located 15 metres from Sean` shot::[2] and say to itself "now - do I have any step definitions that match the phrase `Lucy is located 15 metres from Sean`?"

shot::[3, "new text file, zoom 200%, full screen, make text left aligned in line 7"]
The most simple cucumber expression that would match that step is this one:

----
Lucy is located 15 metres from Sean
----

That’s pretty simple isn't it? Cucumber expressions are just string patterns, and the most simple pattern you can use is a perfect match.

In C#, we can use this pattern to make a step definition like this: shot::[4]

[source, c#]
----
include::../code/dotnet/01--step01-literal-match/Shouty/Shouty.Specs/StepDefinitions/StepDefinitions.cs[lines=14..18]
----

We use a normal C# string to pass the cucumber expression to SpecFlow.
