include::./title.adoc[]

audio::02.06.audio.mp3[]

So we have our failing scenario: shot::[1]

[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty
> cucumber-js -f node_modules/cucumber-pretty

Feature: Hear shout

  Scenario: Listener is within range
    Given Lucy is located 15m from Sean
    When Sean shouts "free bagels at Sean's"
    Then Lucy hears Sean’s message
    ✖ failed
      AssertionError: 
      Expected: is ["free bagels at Sean's"]
           but: was []
          + expected - actual
      
          -[]
          +[
          +  "free bagels at Sean's"
          +]
      
          at World.<anonymous> (/home/fedex/code/shouty/features/step_definitions/steps.js:19:3)

Failures:

1) Scenario: Listener is within range # features/hear_shout.feature:2
   ✔ Given Lucy is located 15m from Sean # features/step_definitions/steps.js:7
   ✔ When Sean shouts "free bagels at Sean's" # features/step_definitions/steps.js:13
   ✖ Then Lucy hears Sean’s message # features/step_definitions/steps.js:18
       AssertionError: 
       Expected: is ["free bagels at Sean's"]
            but: was []
           + expected - actual

           -[]
           +[
           +  "free bagels at Sean's"
           +]
       
           at World.<anonymous> (/home/fedex/code/shouty/features/step_definitions/steps.js:19:3)

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
0m00.002s
npm ERR! Test failed.  See above for more details.
----

Lucy is expected to hear Sean's message, but she hasn't heard anything: we got an empty Array back from the `messagesHeard` method.

shot::[2]
In this case, we’re going to cheat. We have a one-line fix that will make this scenario pass, but it’s not a particularly future-proof implementation. Can you guess what it is?

[source,js]
----
class Person {
  move_to() {
    
  }

  shout(message) {
    
  }

  messagesHeard() {
    return ["free bagels at Sean's"]
  }
}
----

I told you it wasn’t very future proof!

shot::[3]
[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty
> cucumber-js -f node_modules/cucumber-pretty

Feature: Hear shout

  Scenario: Listener is within range
    Given Lucy is located 15m from Sean
    When Sean shouts "free bagels at Sean's"
    Then Lucy hears Sean’s message

1 scenario (1 passed)
3 steps (3 passed)
0m00.002s
----

Woohoo! Our scenario is passing for the first time. As long as this is the only message anyone ever shouts, we're good to ship this thing!

Now, the fact that such a poor implementation can pass our tests shows us that we need to work on our tests. A more comprehensive set of scenarios would force us to write a better implementation.

It's also a good habit to look for the most simple solution. We can trust that, as our scenarios evolve, so will our solution.

This is the essence of Behaviour-Driven Development. Examples of behaviour drive the development. We do just enough to make the next scenario pass, and no more.

shot::[4]
Instead of writing a note on our TODO list, let's write another scenario that shouts a different message. 

[source,gherkin]
----
Feature: Hear shout
  Scenario: Listener is within range
    Given Lucy is located 15m from Sean
    When Sean shouts "free bagels at Sean's"
    Then Lucy hears Sean’s message

  Scenario: Listener hears a different message
    Given Lucy is 15m from Sean
    When Sean shouts "Free coffee!"
    Then Lucy hears Sean's message
----

shot::[5]
It fails, reminding us we need to find a solution that doesn't rely on hard-coding the message.
Now when we come back to this code, we can just run the tests and Cucumber will remind us what we need to do next. We’re done for today!

[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty
> cucumber-js -f node_modules/cucumber-pretty

Feature: Hear shout

  Scenario: Listener is within range
    Given Lucy is located 15m from Sean
    When Sean shouts "free bagels at Sean's"
    Then Lucy hears Sean’s message

  Scenario: Listener hears a different message
    Given Lucy is 15m from Sean
    ? undefined
    When Sean shouts "Free coffee!"
    - skipped
    Then Lucy hears Sean's message
    ? undefined

Warnings:

1) Scenario: Listener hears a different message # features/hear_shout.feature:7
   ? Given Lucy is 15m from Sean
       Undefined. Implement with the following snippet:

         Given('Lucy is 15m from Sean', function () {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });

   - When Sean shouts "Free coffee!" # features/step_definitions/steps.js:13
   ? Then Lucy hears Sean's message
       Undefined. Implement with the following snippet:

         Then('Lucy hears Sean\'s message', function () {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });


2 scenarios (1 undefined, 1 passed)
6 steps (2 undefined, 1 skipped, 3 passed)
0m00.002s
npm ERR! Test failed.  See above for more details.
----
