include::./title.adoc[]

So we have our failing scenario: shot::[1]

[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty-js/shouty
> cucumber-js

..F

Failures:

1) Scenario: Listener is within range # features/hear_shout.feature:2
   ✔ Given Lucy is located 15 metres from Sean # features/step_definitions/steps.js:5
   ✔ When Sean shouts "free bagels at Sean's" # features/step_definitions/steps.js:11
   ✖ Then Lucy hears Sean's message # features/step_definitions/steps.js:16
       AssertionError: 
       Expected: is ["free bagels at Sean's"]
            but: was []
           + expected - actual

           -[]
           +[
           +  "free bagels at Sean's"
           +]

           at World.<anonymous> (/home/fedex/code/shouty-js/shouty/features/step_definitions/steps.js:17:3)

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
0m00.014s (executing steps: 0m00.003s)
npm ERR! Test failed.  See above for more details.
----

Lucy is expected to hear Sean's message, but she hasn't heard anything: we got an empty Array back from the `messagesHeard` method.

shot::[2]
In this case, we’re going to cheat. We have a one-line fix that will make this scenario pass, but it’s not a particularly future-proof implementation. Can you guess what it is?

[source,js]
----
include::../code/js/11-passing-scenario/src/shouty.js[lines=1..13]
----

I told you it wasn’t very future proof!

shot::[3]
[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty-js/shouty
> cucumber-js

...

1 scenario (1 passed)
3 steps (3 passed)
0m00.010s (executing steps: 0m00.002s)
----

Woohoo! Our scenario is passing for the first time. As long as this is the only message anyone ever shouts, we're good to ship this thing!

Now, the fact that such a poor implementation can pass our tests shows us that we need to work on our tests. A more comprehensive set of scenarios would force us to write a better implementation.

It's also a good habit to look for the most simple solution. We can trust that, as our scenarios evolve, so will our solution.

This is the essence of Behaviour-Driven Development. Examples of behaviour drive the development. We do just enough to make the next scenario pass, and no more.

shot::[4]
Instead of writing a note on our TODO list, let's write another scenario that shouts a different message. 

[source,gherkin]
----
include::../code/js/12-add-second-scenario-see-it-fail/features/hear_shout.feature[]
----

shot::[5]
It fails, reminding us we need to find a solution that doesn't rely on hard-coding the message.
Now when we come back to this code, we can just run the tests and Cucumber will remind us what we need to do next. We’re done for today!

[source,bash]
----
$ npm test

> shouty@1.0.0 test /home/fedex/code/shouty-js/shouty
> cucumber-js

.....F

Failures:

1) Scenario: Listener hears a different message # features/hear_shout.feature:7
   ✔ Given Lucy is located 15 metres from Sean # features/step_definitions/steps.js:5
   ✔ When Sean shouts "Free coffee!" # features/step_definitions/steps.js:11
   ✖ Then Lucy hears Sean's message # features/step_definitions/steps.js:16
       AssertionError: 
       Expected: is ["Free coffee!"]
            but: was ["free bagels at Sean's"]
           + expected - actual

            [
           -  "free bagels at Sean's"
           +  "Free coffee!"
            ]

           at World.<anonymous> (/home/fedex/code/shouty-js/shouty/features/step_definitions/steps.js:17:3)

2 scenarios (1 failed, 1 passed)
6 steps (1 failed, 5 passed)
0m00.015s (executing steps: 0m00.004s)
npm ERR! Test failed.  See above for more details.
----
