=== Flexibility

Although it’s important to try to use consistent terminology in our Gherkin scenarios, to help develop the ubiquitous language of your domain, we also want scenarios to read naturally, which means allowing a bit of flexibility.

Ideally, the language used in scenarios should never be constrained by your step definitions. Otherwise they’ll end up sounding like they were written by robots.

One common example is the problem of plurals. Suppose we want to place Lucy and Sean just 1 metre apart. This step would not match:

[source, gherkin]
----
Given Lucy is 1 metre from Sean
----

Because we’ve used the singular `metre` instead of the plural `metres` we don’t have a match. What a pain!
Fear not. We can just surround the `s` in parentheses to make it optional, like this:

[source, ruby]
----
Given 'Lucy is {int} metre(s) from Sean' do |distance|
----

This is one way to smooth off some of the rough edges in your cucumber expressions.

Another is to allow alternates - different ways of saying the same thing. For example, to accept this step:

[source, gherkin]
----
Given Lucy stands 15 metres from Sean
----

...we can use this Cucumber Expression:
[source, ruby]
----
Given 'Lucy is/stands {int} metre(s) from Sean' do |distance|
----

Now we can use either phrasing in our scenarios, and both will match just fine.
