=== Document the Rule about Running out of Credit
We use a scenario to frame the discussion with Paula, our product owner.
[Show the half-written scenario:]
Given Lucy and Sean are within range of each other - that’s what these background steps do - and Sean has bought 4 credits, when Sean shouts a message containing the word “buy” then… what?
Sean doesn’t have enough credits, so presumably Lucy does not hear his message, is that right?
Right, says Paula.
[writes the step]
And so in that case, Sean should still have his four credits, correct?
Right again, says Paula.
[writes the step]
OK, thanks Paula. So the rule is that we’ll only send shouts that you can afford. Is that right?
[writes the rule, deletes the question]
Correct! says Paula. A person can’t send a premium shout unless they have enough credits to pay for it.
Now we understand the business rule, let’s automate this scenario and drive out the behaviour.
Decide what happens when you run out of credit

=== Automate the scenario
First we need to match this new step where we check Lucy does not hear Sean’s message.
We have a very similar one here for Larry. We can use a capture group to make it more generic. Instead of a wildcard though, we can use pipes to specify the alternative values we expect here.
We capture the listener name, then use that here when fetching the instance of Person.
Make step more generic
Right, now we have a failing acceptance test which should be passing once we’ve resolved this. Let’s have a think about where this behaviour should go.
Only shout what you can afford: Failing unit test
If we give the responsibility for checking affordability to the Person doing the shouting, then Network doesn’t need to care about credits at all, which will simplify things nicely.
Let’s start with a new unit test for Person then.
We’ll set up Sean with only one credit - not enough to afford to send a long message - and assert that the broadcast method is not called on Network. Then we try to shout the long message.
This fails of course, because at the moment Person doesn’t make this check, so the broadcast method is called every time.
We’re at Red in the TDD cycle. Next stop: green!
COMMIT
Only shout what you can afford: Green
To make this pass we need to know how much the shout is going to cost before we send it. That knowledge is in the deduct_credits method, which actually does two tasks at the same time: it works out the cost of the message, and it deducts that cost from the person’s balance.
Let’s tease those two tasks apart, first calculating the cost of the shout, then deducting that cost from the credits.
Red: split responsibilities in Person#deduct_credits
Now we can extract a method that calculates the cost of the message.
Red: Extract method to calculate cost of message
Then finally we can use that method to check whether the message is affordable.
Green: Use cost_of to check message is affordable
...and our unit test is passing. Great.
And I suppose our acceptance test for the affordability rule should be passing now too. It is!

