=== Beginning the refactoring
Instead of rewriting this code, let’s see if we can refactor it. When refactoring, it’s crucial not to break existing functionality, so we’ll rely on our tests to warn us if we make a mistake.
<ruby>
cucumber --tags ~@todo && rspec -f doc
</ruby>
<java>
mvn test -Dcucumber.options=”--tags ~@todo”
</java>
We’ll work in small steps. We may temporarily break some unit tests as the implementation shifts, but the acceptance tests should be passing all the way through if everything goes according to plan.
Ready? We’ll start by moving the deduct_credits method onto Person.
As a baby-step, we’ll make it public, so we can just continue to call it from Network’s broadcast method for now. That should keep the acceptance tests passing... Good.
[move method, run tests. cucumber passes, unit tests fail]
Now let’s make Sean responsible for deducting his own credits, as he shouts. We can move over this whole responsibility of charging for shouts from the network specs to the person specs.
[move charging for shouts tests from network tests to person tests file]
We’ll need to adjust the test like this… 
[amend test to use a real instance of Person, and assert on the value of credits]
Move `deduct_credits` onto Person
...and we’re back to green!
Green: move the call to deduct credits over to the shouter.
Let’s refactor some more.
Because all this code is running within the shouter object now, we don’t need to pass around this instance of Person anymore, and we can access the credits instance variable here, directly.
We can make deduct credits private now.
Make Person#deduct_credits private
We don’t need to pass short enough around as a variable, we can just do the logic inline here.
Refactor: inline `short_enough`

=== Clean up Person unit tests
Great, now the code in Network#broadcast is much cleaner.
We still have these pending unit tests we need to sort out. Let’s start in Person, by fleshing out this test about charging for long messages.
Retro-fit unit test for charging for long messages
That’s better. Let’s just make it fail quickly, to check that we can trust it.

=== Discuss the remaining Network unit tests
OK, now we can tackle these two <ruby>pending</ruby><java>ignored</java> unit tests in Network.
Let’s step back for a second and consider the rule we’re implementing here. This original unit test was simply there to ensure that long messages were not broadcast: remember we originally started out without premium accounts.
With the addition of premium accounts, the rule has changed: We will broadcast long messages, but only if the person shouting has sufficient credits.
To implement it, we’ve ended up with this mind-bending boolean logic in the broadcast method.  It doesn’t have to be like this. This complexity is a sign that we haven’t modelled the problem well enough yet.
Recall that right at the end of lesson 7, we discovered a known unknown in our problem domain and documented it with this question: what happens when you run out of credits? 
We know you can’t send a long message when you run out of credits, but what about a message containing the word ‘buy’? Perhaps having a complete answer to this question will help us to resolve this complexity.
Let’s check with our product owner.

