include::./title.adoc[]

shot::[0,"Show feature file"] When writing scenarios, occasionally we want to use a really long piece of data.

shot::[1,"New rule"] For example, let’s introduce a new rule about the maximum length of a message

.hear_shout.feature
[source,gherkin]
----
include::../code/java/17--step17-max-length-rule/shouty/src/test/resources/shouty/hear_shout.feature[lines=42..42]
----

...and add a scenario to illustrate it shot::[2,"New scenario"], making the string just over the boundary of the rule:

[source,gherkin]
----
include::../code/java/17--step17-max-length-rule/shouty/src/test/resources/shouty/hear_shout.feature[lines=44..48]
----

That’s pretty ugly isn’t it!

Still, we’ll press on and get it to green, then we’ll show you how to clean it up.

shot::[3,"run Cucumber"] Our existing step definition handles that ugly step with the long message just fine, but the last outcome step is undefined. We could either add a new step definition, or paramterise "Larry should not hear a shout". shot::[4,"Modify stepdef"] Let's modify the existing step definition

.StepDefinitions.java
[source,java]
----
include::../code/java/18--step18-parameterise-stepdef/shouty/src/test/java/shouty/StepDefinitions.java[lines=87..90]
----

shot::[5,"run cucumber"]

OK, so we have a failing acceptance test. Let’s dive down into our solution and implement this new rule. It seems like the Network should be responsible for implementing this rule, shot::[5a,show NetworkTest] so let’s go to its unit tests and shot::[5b, start creating new unit test] add a new example to specify this extra responsibility.

We’ll create a 181-character message like this shot::[6,finish implementing unit test] and then assert that the message should not be heard when it’s broadcast.

.NetworkTest.java
[source,java]
----
include::../code/java/19--step19-add-test-to-networktest/shouty/src/test/java/shouty/NetworkTest.java[lines=49..62]
----

Let’s run that test shot::[7,"run Cucumber - show the unit test results"]. Good, it fails. Lucy’s still getting the message at the moment. Now how are we going to implement this?

It looks like we’re already shot::[8,"show Network proximity logic"] implementing the proximity rule here in the broadcast method. Let’s shot::[8a,"add message length logic"] add another if statement here about the message length.

.Network.java
[source,java]
----
include::../code/java/20--step20-implement-maximum-length/shouty/src/main/java/shouty/Network.java[lines=21..23]
----

shot::[9,"run cucumber"] Run the unit test again… and it’s passing. Great.

shot::[9a,"show the modified logic in the Network class"]
The code here has got a little bit messy and hard to read. One very basic move we could make to improve it would be to just shot::[9b,"extract temporary variables"] extract a couple of temporary variables.

.Network.java
[source,java]
----
include::../code/java/21--step21-tidy-up-network-logic/shouty/src/main/java/shouty/Network.java[lines=20..24]
----

That’s better. This code could be improved even further of course, but at least we haven’t made it any worse.

shot::[10,"run cucumber"] Let’s just run the tests to check. Great - everything’s still green.

shot::[10a,"show message length scenario in feature file"]
Now we have everything passing again, we can tidy up the Gherkin to use a new piece of syntax we’ve been wanting to tell you about: a DocString.

DocStrings allow you to specify a text argument for a step that spans over multiple lines. shot::[10b,"convert message to DocString"] We could change our step to look like this instead:

[source,gherkin]
----
include::../code/java/22--step22-docstring/shouty/src/test/resources/shouty/hear_shout.feature[lines=44..55]
----

Now the scenario is much more readable.

shot::[10c,"show existing stepdef code"]
We have to add a new step definition too shot::[11,"add sean_shouts_the_following_message stepdef"]. It doesn't need a parameter in the Cucumber Expression -- the DocString gets passed as a string argument to the step definition automatically.

.StepDefinitions.java
[source,java]
----
include::../code/java/22--step22-docstring/shouty/src/test/java/shouty/StepDefinitions.java[lines=77..82]
----

Let's check that we're still green shot::[12,"run cucumber"] -- and we are!

We don’t use DocStrings very often - having such a lot of data in a test can often make it quite brittle. But when you do need it, it's useful to know about.
