include::./title.adoc[]

When writing scenarios, occasionally we want to use a really long piece of data.

For example, let’s introduce a new rule about the maximum length of a message shot::[1,"New rule"]

.hear_shout.feature
[source,gherkin]
----
include::../code/ruby/16-max-length-rule/features/hear_shout.feature[lines=42]
----

...and add a scenario to illustrate it shot::[2,"New scenario"], making the string just over the boundary of the rule:

[source,gherkin]
----
include::../code/ruby/16-max-length-rule/features/hear_shout.feature[lines=44..48]
----

That’s pretty ugly isn’t it!

Still, we’ll press on and get it to green, then we’ll show you how to clean it up.

shot::[3,"run Cucumber"] Our existing step definition handles that ugly step with the long message just fine, but the last outcome step is undefined. We could either add a new step definition, or paramterise "Larry should not hear a shout". Let's modify the existing step definition shot::[4,"Modify stepdef"]

.steps.rb
[source,ruby]
----
include::../code/ruby/17-parameterise-stepdef/features/step_definitions/steps.rb[lines=45..47]
----

shot::[5,"run cucumber"]

OK, so we have a failing acceptance test. Let’s dive down into our solution and implement this new rule. It seems like the Network should be responsible for implementing this rule, so let’s go to its unit tests and add a new example to specify this extra responsibility.

We’ll create a 181-character message like this shot::[6,] and then assert that the message should not be heard when it’s broadcast.

.network_spec.rb
[source,ruby]
----
include::../code/ruby/18-add-test-to-networktest/spec/network_spec.rb[lines=36..46]
----

Let’s run that test shot::[7,"run Cucumber - show the unit test results"]. Good, it fails. Lucy’s still getting the message at the moment. Now how are we going to implement this?

It looks like we’re already implementing the proximity rule here shot::[8,"Network proximity logic"] in the broadcast method. Let’s add another if statement here about the message length.

.shouty.rb
[source,ruby]
----
include::../code/ruby/19-implement-maximum-length/lib/shouty.rb[lines=35..37]
----

shot::[9,"run cucumber"] Run the unit test again… and it’s passing. Great.

The code here has got a little bit messy and hard to read. One very basic move we could make to improve it would be to just extract a couple of temporary variables.

.shouty.rb
[source,ruby]
----
include::../code/ruby/20-tidy-up-network-logic/lib/shouty.rb[lines=33..42]
----

That’s better. This code could be improved even further of course, but at least we haven’t made it any worse.

shot::[10,"run cucumber"] Let’s just run the tests to check. Great - everything’s still green.

Now we have everything passing again, we can tidy up the Gherkin to use a new piece of syntax we’ve been wanting to tell you about: a DocString.

DocStrings allow you to specify a text argument for a step that spans over multiple lines. We could change our step to look like this instead:

[source,gherkin]
----
include::../code/ruby/21-docstring/features/hear_shout.feature[lines=44..55]
----

Now the scenario is much more readable.

We have to add a new step definition too shot::[11,"sean_shouts_the_following_message"]. It doesn't need a parameter in the Cucumber Expression -- the DocString gets passed as a string argument to the step definition automatically.

.steps.rb
[source,ruby]
----
include::../code/ruby/21-docstring/features/step_definitions/steps.rb[lines=54..58]
----

Let's check that we're still green shot::[12,"run cucumber"] -- and we are!

We don’t use DocStrings very often - having such a lot of data in a test can often make it quite brittle. But when you do need it, it's useful to know about.
