include::./title.adoc[]

When writing scenarios, occasionally we want to use a really long piece of data. shot::[1,"Show feature file"]

For example, let’s introduce a new rule about the maximum length of a message shot::[2,"New rule"]

.hear_shout.feature
[source,gherkin]
----
include::../code/js/16-max-length-rule/features/hear_shout.feature[lines=42]
----

...and add a scenario to illustrate it shot::[3,"New scenario"], making the string just over the boundary of the rule:

[source,gherkin]
----
include::../code/js/16-max-length-rule/features/hear_shout.feature[lines=44..48]
----

That’s pretty ugly isn’t it!

Still, we’ll press on and get it to green, then we’ll show you how to clean it up.

shot::[4,"run Cucumber"] Our existing step definition handles that ugly step with the long message just fine, but the last outcome step is undefined. We could either add a new step definition, or parameterise "Larry should not hear a shout". Let's modify the existing step definition shot::[5,"Modify stepdef"]

.steps.js
[source,js]
----
include::../code/js/17-parameterise-stepdef/features/step_definitions/steps.js[lines=49..51]
----

shot::[6,"run cucumber"]

OK, so we have a failing acceptance test.shot::[7] Let’s dive down into our solution and implement this new rule. It seems like the Network should be responsible for implementing this rule,  so let’s go to its unit tests. shot::[8,show NetworkTest] As we explain in more detail in the next lesson, we start by adding a new example to specify this extra responsibility. shot::[9, start creating new unit test]

We’ll create a 181-character message like this shot::[10,finish implementing unit test] and then assert that the message should not be heard when it’s broadcast.shot::[11]

.network.test.js
[source,js]
----
include::../code/js/18-add-test-to-networktest/test/network.test.js[lines=48..58]
----

Let’s run that test shot::[12,"run Cucumber - show the unit test results"]. Good, it fails. Lucy’s still getting the message at the moment. Now how are we going to implement this?

It looks like we’re already implementing the proximity rule here shot::[13,"Network proximity logic"] in the broadcast method. Let’s add another if statement here about the message length. shot::[14,"add message length logic"] 

.shouty.rb
[source,js]
----
include::../code/js/19-implement-maximum-length/src/shouty.js[lines=37..39]
----

Run the unit test again… and it’s passing. And cucumber is green as well shot::[15,"run cucumber"]

Great.

The code here has got a little bit messy and hard to read. shot::[16,"show the modified logic in the Network class"]
One very basic move we could make to improve it would be to just extract a couple of temporary variables, one for the range rule shot::[17,"extract range temporary variable"] and one for the length rule. shot::[18,"extract length temporary variable"]

.shouty.js
[source,js]
----
include::../code/js/20-tidy-up-network-logic/src/shouty.js[lines=35..43]
----

That’s better. This code could be improved even further of course, but at least we haven’t made it any worse.

Let’s just run the tests to check. shot::[19,"run cucumber"] Great - everything’s still green.

Now we have everything passing again, we can tidy up the Gherkin to use a new piece of syntax we’ve been wanting to tell you about: a DocString. shot::[20,"show message length scenario in feature file"]

DocStrings allow you to specify a text argument for a step that spans over multiple lines. We could change our step to look like this instead: shot::[21,"convert message to DocString"]

[source,gherkin]
----
include::../code/js/21-docstring/features/hear_shout.feature[lines=44..55]
----

Now the scenario is much more readable.

shot::[22,"show existing stepdef code"]
We have to add a new step definition too shot::[23,"sean_shouts_the_following_message"]. It doesn't need a parameter in the Cucumber Expression -- the DocString gets passed as an argument to the step definition automatically.shot::[24]

Now we can fill out the rest of our new step definition. shot::[25]

.steps.js
[source,js]
----
include::../code/js/21-docstring/features/step_definitions/steps.js[lines=37..40]
----

Let's check that we're still green shot::[26,"run cucumber"] -- and we are!

We don’t use DocStrings very often - having such a lot of data in a test can often make it quite brittle. But when you do need it, it's useful to know about.
