include::./title.adoc[]

When writing scenarios, occasionally we want to use a really long piece of data. shot::[1,"Show feature file"]

For example, let’s introduce a new rule about the maximum length of a message shot::[2,"New rule"]

.hear_shout.feature
[source,gherkin]
----
include::../code/java/17--step17-max-length-rule/shouty/src/test/resources/shouty/hear_shout.feature[lines=42..42]
----

...and add a scenario to illustrate it shot::[3,"New scenario"], making the string just over the boundary of the rule:

[source,gherkin]
----
include::../code/java/17--step17-max-length-rule/shouty/src/test/resources/shouty/hear_shout.feature[lines=44..48]
----

That’s pretty ugly isn’t it!

Still, we’ll press on and get it to green, then we’ll show you how to clean it up.

shot::[4,"run Cucumber"] Our existing step definition handles that ugly step with the long message just fine, but the last outcome step is undefined. We could either add a new step definition, or paramterise "Larry should not hear a shout". Let's modify the existing step definition shot::[5,"Modify stepdef"]

.StepDefinitions.java
[source,java]
----
include::../code/java/18--step18-parameterise-stepdef/shouty/src/test/java/shouty/StepDefinitions.java[lines=87..90]
----

shot::[6,"run cucumber"]

OK, so we have a failing acceptance test.shot::[7] Let’s dive down into our solution and implement this new rule. It seems like the Network should be responsible for implementing this rule,  so let’s go to its unit tests. shot::[8,show NetworkTest] As we explain in more detail in the next lesson, we start by adding a new example to specify this extra responsibility. shot::[9, start creating new unit test]

We’ll create a 181-character message like this shot::[10,finish implementing unit test] and then assert that the message should not be heard when it’s broadcast.shot::[11]

.NetworkTest.java
[source,java]
----
include::../code/java/19--step19-add-test-to-networktest/shouty/src/test/java/shouty/NetworkTest.java[lines=49..62]
----

Let’s run that test. shot::[12,"run Cucumber - show the unit test results"]shot::[13] Good, it fails. Lucy’s still getting the message at the moment. Now how are we going to implement this?

It looks like we’re already implementing the proximity rule here in the broadcast method. shot::[14,"show Network proximity logic"] Let’s add another if statement here about the message length. shot::[15,"add message length logic"]

.Network.java
[source,java]
----
include::../code/java/20--step20-implement-maximum-length/shouty/src/main/java/shouty/Network.java[lines=21..23]
----

shot::[16,"run cucumber"]
Run the unit test again… and it’s passing. Great.


The code here has got a little bit messy and hard to read. shot::[17,"show the modified logic in the Network class"]
One very basic move we could make to improve it would be to just extract a couple of temporary variables, one for the range rule shot::[18,"extract range temporary variable"] and one for the length rule. shot::[19,"extract length temporary variable"]

.Network.java
[source,java]
----
include::../code/java/21--step21-tidy-up-network-logic/shouty/src/main/java/shouty/Network.java[lines=20..24]
----

That’s better. This code could be improved even further of course, but at least we haven’t made it any worse.

Let’s just run the tests to check. shot::[20,"run cucumber"] Great - everything’s still green.

Now we have everything passing again, we can tidy up the Gherkin to use a new piece of syntax we’ve been wanting to tell you about: a DocString. shot::[21,"show message length scenario in feature file"]

DocStrings allow you to specify a text argument for a step that spans over multiple lines.  We could change our step to look like this instead: shot::[22,"convert message to DocString"]

[source,gherkin]
----
include::../code/java/22--step22-docstring/shouty/src/test/resources/shouty/hear_shout.feature[lines=44..55]
----

Now the scenario is much more readable. 

shot::[23,"show existing stepdef code"]
We have to add a new step definition too shot::[24,"add sean_shouts_the_following_message stepdef"]. It doesn't need a parameter in the Cucumber Expression shot::[25] -- the DocString gets passed as a string argument to the step definition automatically.shot::[26]

Now we can fill out the rest of our new step definition. shot::[27]shot::[28]

.StepDefinitions.java
[source,java]
----
include::../code/java/22--step22-docstring/shouty/src/test/java/shouty/StepDefinitions.java[lines=77..82]
----

Let's check that we're still green shot::[29,"run cucumber"]shot::[30] -- and we are!

We don’t use DocStrings very often - having such a lot of data in a test can often make it quite brittle. But when you do need it, it's useful to know about.
