= Questions for chapter 3

== Lesson 1

=== Which of the following statements are true?

* Step definitions translate human-readable scenarios into concrete actions in code - TRUE
* BDD practitioners think of "step definitions" and "automation code" as distinct concepts - TRUE
* Cucumber only supports automation through the user interface - FALSE

Answer: A step definition is a piece of code that is called by Cucumber in response to a step in a scenario. You can write any code you like inside a step definition, but we've found it easier to maintain if we keep them short. This leads to step definitions calling dedicated automation code to perform concrete actions against the system under construction. That automation code can manipulate the user interface, make a REST call, or drive the domain model directly.

=== Which of the following statements are true?

* Regular Expressions are exactly the same as Cucumber Expressions - FALSE
* Modern versions of Cucumber only support both Cucumber Expressions and Rregular Expressions - TRUE
* Cucumber Expressions are more intimidating than Regular Expressions - FALSE

Answer: Regular Expressions are a powerful tool that have been in use in computer science for many decades. They can be hard understand and maintain, so the Cucumber team created a simplified mechanism, called Cucumber Expressions. However, Cucumber remains backwards compatible, so you can use both Regular Expressions and Cucumber Expressions with modern releases of Cucumber.

== Lesson 2

=== Which of the following Cucumber Expression will match the step "Given Lucy is 15 metres from Sean"?

* "lucy is 15 metres from sean" - FALSE
* "Given Lucy is 15 metres from Sean" - FALSE
* "Lucy is 15 metres from Sean" - TRUE
* "Lucy is 15 metres from Sean Smith" - FALSE

Answer: Cucumber Expressions look for a match of the whole step text EXCLUDING the Gherkin keyword (Given/When/Then/And/But). The match is case sensitive and matches whitespace as well.

== Lesson 3

=== Which of the following is NOT a built in Cucumber Expression parameter type?

* float - FALSE
* integer - TRUE
* string - FALSE
* word - FALSE

Answer: The Cucumber Expression parameter type that matches an integer is `{int}`, not `{integer}`

=== Which of the following statements is true?

* You cannot create your own Cucumber Expression parameter types - FALSE
* Cucumber discards the value that matches a Cucumber Expression parameter type - FALSE
* Your step definition code will be passed the value that matched the Cucumber Expression parameter type - TRUE
* Cucumber always passes the matched parameter as a string - FALSE

Answer: Cucumber will pass the step definition a parameter for each Cucumber Expression parameter type. Cucumber will attempt to convert the text that matched into a suitable format. Using the `{int}` parameter type will result in a number being passed to the step definition. You can extend the predefined Cucumber Expression parameter types, by creating your own.

== Lesson 4

=== How can you express in a Cucumber Expression that matching some text is optional?

* Enclose it in square brackets: [] - FALSE
* Enclose it in parentheses: () - TRUE
* Place a question mark after it: ? - FALSE
* Precede it with a slash: / - FALSE

Answer: Any text in a Cucumber Expression that is surrounded by parentheses `()` is considered optional.

=== What does a slash `/` separating words mean in a Cucumber Expression?

* The words are considered alternatives - the Cucumber Expression will match any of them - TRUE
* It doesn't mean anything special - the Cucumber Expression will match the slash as a literal character- FALSE
* The word that follows the slash is considered optional - FALSE

Answer: Words in a Cucumber Expression that are separated by a slash `/` are considered alternates. There must be no whitespace between the word and the slash.

=== Which of the following Cucumber Expressions would match both "it weighed 3 grammes" and "it weighed 1 gramme"?

* "it weighed {int} gramme(s)" - TRUE
* "it weighed 1/3 gramme/s" - FALSE
* "it weighed 1/3 gramme(s)" - TRUE
* "it weighed 1 / 3 gramme(s)" - FALSE
* "it weighed 1/2/3 gramme/grammes" - TRUE

Answer: Any text surrounded by parentheses `()` is considered optional. Any words separated by a slash `/` are considered to be alternates. You can find full documentation about Cucumber Expressions at https://cucumber.io/docs/cucumber/cucumber-expressions/

== Lesson 5

=== Java

==== What role do Regular Expressions play in Cucumber Expressions?

* None
* Cucumber Expressions provide a subset of Regular Expression syntax
* Cucumber Expressions are exactly the same as Regular Expressions
* A Regular Expression is used to define the text to be matched when using a custom Parameter Type - TRUE

Answer: We use a Regular Expression to specify the text that should be matched when a custom Parameter Type is used in a Cucumber Expression.

==== How would you use the custom Parameter Type defined by the following code?
@ParameterType("activated")
public Status state(String activationState) {
    return new Status(activationState);
}

* {activated}
* {activationState}
* {state} - TRUE
* {Status}

Answer: The name of a custom Parameter Type is defined by the name of the method that is decorated with the `@ParameterType` annotation.

=== Javascript

==== What role do Regular Expressions play in Cucumber Expressions?

* None
* Cucumber Expressions provide a subset of Regular Expression syntax
* Cucumber Expressions are exactly the same as Regular Expressions
* A Regular Expression is used to define the text to be matched when using a custom Parameter Type - TRUE

Answer: We use a Regular Expression to specify the text that should be matched when a custom Parameter Type is used in a Cucumber Expression.

==== How would you use the custom Parameter Type defined by the following code?
defineParameterType({
  name: 'state',
  regexp: /activated/,
  transformer: activationState => new Status(activationState)
})

* {activated}
* {activationState}
* {state} - TRUE
* {Status}

Answer: The name of a custom Parameter Type is defined by the `name` parameter passed to the `defineParameterType` method.

=== Ruby

==== What role do Regular Expressions play in Cucumber Expressions?

* None
* Cucumber Expressions provide a subset of Regular Expression syntax
* Cucumber Expressions are exactly the same as Regular Expressions
* A Regular Expression is used to define the text to be matched when using a custom Parameter Type - TRUE

Answer: We use a Regular Expression to specify the text that should be matched when a custom Parameter Type is used in a Cucumber Expression.

==== How would you use the custom Parameter Type defined by the following code?
ParameterType(
  name:        'state',
  regexp:      /activated/,
  transformer: -> (activationState) { Status.new(activationState) }
)

* {activated}
* {activationState}
* {state} - TRUE
* {Status}

Answer: The name of a custom Parameter Type is defined by the `name` parameter passed to the `ParameterType` method.


=== C#
