include::./title.adoc[]

shot::[1, "broken implementation"]
We now have two step definitions to implement, and that presents us with a bit of a problem. We need the same instance of Network available in both. We could just assume that the Lucy step will always run first and create it there, but that seems fragile. If someone wrote a new scenario that didn’t create people in the right order, they’d end up with no Network instance, and weird bugs. We want our steps to be as independent as possible, so they can be easily composed into new scenarios.

[source,java]
include::../code/java/06-broken-stepdef-implmentation/shouty/src/test/java/shouty/StepDefinitions.java[lines=24..32]

shot::[2, "Network as instance field"]
There are a couple of different ways to create this network instance in Java. The most straightforward is to create a network field and initialize it in the declaration. Every time Cucumber runs a scenario it creates a new instance of your steps class, so we’ll get a fresh instance of the Network for each scenario.

[source,java]
include::../code/java/07-network-as-an-instance-field/shouty/src/test/java/shouty/StepDefinitions.java[lines=10..15]

As an alternative, that can be useful if you have more complex setup to do, you can use a hook.

shot::[3, "Using a Before hook"]
We need an instance of Network in every scenario, so we can declare a Before Hook that creates one before each scenario starts, like this:
Now we can use that Network instance as we create Lucy and Sean in these two new steps.

[source,java]
include::../code/java/08-using-a-before-hook/shouty/src/test/java/shouty/StepDefinitions.java[lines=18..21]

[source,java]
include::../code/java/08-using-a-before-hook/shouty/src/test/java/shouty/StepDefinitions.java[lines=31..39]

shot::[4, "mvn test"]
It should be working again now. Let’s run cucumber to check.

shot::[5, "Copy and paste in feature file"]
Good. Let’s do the same with the other scenario.

include::../code/java/09-change-second-scenario/shouty/src/test/resources/shouty/shout.feature[lines=16..20]

shot::[6, "mvn test"]

shot::[7, "Delete lucy_is_located_m_from_Sean"]
Now we can remove this old step definition. We know we'll need something like this in the future when we implement the proximity rule, but we don't want to second-guess what that code will look like, so let's clean it out for now.

[source,java]
.include::../code/java/10-delete-unused-stepdef/shouty/src/test/java/shouty/StepDefinitions.java

shot::[8, "mvn test"]

shot::[9, "delete moveTo"]
Now we have one last bit of dead code left, the move_to method on Person. Let's clean that up too.

[source,java]
include::../code/java/11-delete-move_to/shouty/src/main/java/shouty/Person.java

shot::[10, "mvn test"]
