=== Example Mapping: Conclusions

shot::[1, "Animation of Matt talking to camera"]

As you’ve just seen, an example mapping session should go right across the breadth of the story, trying to get a complete picture of the behaviour. Inviting all three amigos - product owner, tester and developer - is important because each perspective adds something to the conversation.

shot::[2, "Diagram showing user story -> example mapping -> rules / examples"]

Although the apparent purpose of an example mapping session is to take a user story, and try to produce rules and examples that illustrate the behaviour, the underlying goal is to achieve a
shot::[3, "Show *shared understanding* appearing"]
 _shared understanding_ and agreement about the precise scope of a user story. Some people tell us that example mapping has helped to build empathy within their team!

With this goal in mind, make sure the session isn’t just a rubber-stamping exercise, where one person does all the talking. Notice how in our example, everyone in the group was asking questions and writing new cards.

In the conversation, we often end up 
shot::[4, "show feedback arrow going back to 'User Story'"]
refining, or even slicing out new user stories 
shot::[5, "show New user Stories"]
to make the current one smaller.  Deciding what a story is not - and maximising the amount of work not done - is one of the most useful things you can do in a three amigos session. Small stories are the secret of a successful agile team. 

Each time you come up with an example, try to understand what the underlying rule or rules are. If you discover an example that doesn’t fit your rules, you’ll need to reconsider your rules. In this way, the scope of the story is refined by the group.

Although there’s no doubt of the power of examples for exploring and talking through requirements, it’s the rules that will go into the code. If you understand the rules, you’ll be able to build an elegant solution.

shot::[6, "David West / Object Thinking quote"]
As Dr David West says in his excellent book "Object Thinking", _If you problem the solution well enough, the solution will take care of itself_.

shot::[7, "Return to diagram"]

Sometimes, you’ll come across questions that nobody can answer. Instead of getting stuck trying to come up with an answer, just write down the question. 
shot::[8, "show questions / assumptions as output"]

Congratulations! You’ve just turned an unknown unknown into a known unknown. That’s progress.

shot::[9, "Animation of Matt talking to camera"]

Many people think they need to produce formal Gherkin scenarios from their three amigos conversations, but in our experience that’s only occasionally necessary. In fact, it can often slow the discussion down.

The point of an example mapping session is to do the _discovery_ work. You can do _formulation_ as a separate activity, next.

One last tip is to run your example mapping sessions in a timebox. When you’re practiced at it, you should be able to analyse a story within 25 minutes. If you can’t, it’s either too big, or you don’t understand it well enough yet. Either way, it’s not ready to play.

At the end of the 25 minutes, you can check whether everyone thinks the story is ready to start work on. If lots of questions remain, it would be risky to start work, but people might be comfortable taking on a story with only a few minor questions to clear up. Check this with a quick thumb-vote.

==== Lesson 3 - Questions

===== Which of the following are direct outcomes you could expect if your team starts practcing Example Mapping?

* Less rework due to bugs found in your stories (*Correct*)
* Greater empathy and mutual respect between team members (*Correct*)
* Amazing Gherkin that reads really well
* Smaller user stories (*Correct*)
* A shared understanding of what you're going to build for the story (*Correct*)
* More predicatable delivery pace (*Correct*)
* A quick sense of whether a story is about the right size and ready to start writing code. (*Correct*)

**Explanation:**

We don't write Gherkin during an example mapping session, so that's not one of the direct outcomes, though a good example mapping session should leave the team ready to write their best Gherkin.

===== Which of the following presents the most risk to your project?

* Unknown unknowns (*Correct*)
* Known unknowns
* Known knowns

**Explanation:**

In project management, there are famously "uknown unknowns", "known unknowns" and "known knowns". The most dangerous are the "unknown unknows" because not only do we not know the answer to them, we have not even realised yet that there's a question!