==== Lesson 5 - Questions (Ruby, Java, JS)

===== Why should a step definition be short?

* Because the plain-language description of the domain in the Gherkin step should be close to the domain model in the code - TRUE
* Step definitions don't need to be short
* Cucumber limits the length of step definitions to five lines of code

Answer: Step definitions are a thin glue between the plain-language description in a scenario and the software that we're building. If the business domain and the solution domain are aligned, then there should be little translation to do in the step definition.

===== What does it mean when Cucumber compains about an _ambiguous_ step?

* Cucumber couldn't find a step definition that matches a step
* Cucumber only found one step definition that matches a step
* Cucumber found more than one step definition that matches a step - TRUE

Answer: If more than one step definition matches a step, then Cucumber doesn't know which one to call. When this ambiguity occurs, Cucumber issues an error, rather than try to choose between the matching step definitions.

